MauiKit: NotificationClient Class Reference
NotificationClient Class Reference
#include <notificationclient.h>
Signals
void notificationChanged ()
Public Member Functions
NotificationClient (QObject *parent=0)
void notify (const QString &notification)
QString notification () const
Private Slots
void updateAndroidNotification ()
Private Attributes
QString m_notification
Detailed Description
Definition at line 25 of file notificationclient.h.
Constructor & Destructor Documentation
NotificationClient()
NotificationClient::NotificationClient (QObject * parent = 0) explicit
Definition at line 41 of file notificationclient.cpp.
     : QObject(parent)
 {
     connect(this, SIGNAL(notificationChanged()), this, SLOT(updateAndroidNotification()));
 }
References notificationChanged(), and updateAndroidNotification().
Member Function Documentation
notification()
QString NotificationClient::notification () const
Definition at line 56 of file notificationclient.cpp.
 {
     return m_notification;
 }
References m_notification.
Referenced by notify().
notificationChanged
void NotificationClient::notificationChanged () signal
Referenced by NotificationClient(), and notify().
notify()
void NotificationClient::notify (const QString & notification)
Definition at line 47 of file notificationclient.cpp.
 {
     if (m_notification == notification)
         return;
     m_notification = notification;
     emit notificationChanged();
 }
References m_notification, notification(), and notificationChanged().
updateAndroidNotification
void NotificationClient::updateAndroidNotification () private slot
Definition at line 61 of file notificationclient.cpp.
 {
 #if defined(Q_OS_ANDROID)
     QAndroidJniEnvironment _env;
     QAndroidJniObject activity = QAndroidJniObject::callStaticObjectMethod("org/qtproject/qt5/android/QtNative", "activity", "()Landroid/app/Activity;");   //activity is valid
     if (_env->ExceptionCheck()) {
         _env->ExceptionClear();
         throw InterfaceConnFailedException();
     }
     if ( activity.isValid() )
     {
         QAndroidJniObject::callStaticMethod<void>("com/example/android/tools/NotificationClient",
                                                   "notify",
                                                   "(Landroid/content/Context;Ljava/lang/String;)V",
                                                   QtAndroid::androidContext().object(),
                                                   QAndroidJniObject::fromString(m_notification).object<jstring>());
         if (_env->ExceptionCheck()) {
             _env->ExceptionClear();
             throw InterfaceConnFailedException();
         }
     }else
         throw InterfaceConnFailedException();
 #endif
 }
References m_notification.
Referenced by NotificationClient().
Field Documentation
m_notification
QString NotificationClient::m_notification private
Definition at line 41 of file notificationclient.h.
Referenced by notification(), notify(), and updateAndroidNotification().
The documentation for this class was generated from the following files:
android/notificationclient.h
android/notificationclient.cpp