MauiKit: FMList Class Reference
FMList Class Reference
#include <fmlist.h>
Public Types
enum SORTBY : uint_fast8_t {
SIZE = FMH::MODEL_KEY::SIZE, MODIFIED = FMH::MODEL_KEY::MODIFIED, DATE = FMH::MODEL_KEY::DATE, LABEL = FMH::MODEL_KEY::LABEL,
MIME = FMH::MODEL_KEY::MIME, ADDDATE = FMH::MODEL_KEY::MIME, TITLE = FMH::MODEL_KEY::TITLE, PLACE = FMH::MODEL_KEY::PLACE,
FORMAT = FMH::MODEL_KEY::FORMAT
}
Public Slots
QVariantMap get (const int &index) const
void refresh ()
void createDir (const QString &name)
void copyInto (const QVariantList &files)
void cutInto (const QVariantList &files)
void test ()
Signals
void pathChanged ()
void pathTypeChanged ()
void filtersChanged ()
void filterTypeChanged ()
void hiddenChanged ()
void previewChanged ()
void onlyDirsChanged ()
void sortByChanged ()
void trackChangesChanged ()
void isBookmarkChanged ()
void foldersFirstChanged ()
void saveDirPropsChanged ()
void contentReadyChanged ()
void viewTypeChanged ()
void cloudDepthChanged ()
void pathEmptyChanged ()
void pathExistsChanged ()
void preItemAppended ()
void postItemAppended ()
void preItemRemoved (int index)
void postItemRemoved ()
void updateModel (int index, QVector< int > roles)
void preListChanged ()
void postListChanged ()
void warning (QString message)
void progress (int percent)
Public Member Functions
Q_ENUM(SORTBY) enum FILTER Q_ENUM(FILTER) enum PATHTYPE Q_ENUM(PATHTYPE) enum VIEW_TYPE Q_ENUM (VIEW_TYPE) FMList(QObject *parent
~FMList ()
FMH::MODEL_LIST items () const
FMList::SORTBY getSortBy () const
void setSortBy (const FMList::SORTBY &key)
QString getPath () const
void setPath (const QString &path)
FMList::PATHTYPE getPathType () const
QStringList getFilters () const
void setFilters (const QStringList &filters)
FMList::FILTER getFilterType () const
void setFilterType (const FMList::FILTER &type)
bool getHidden () const
void setHidden (const bool &state)
bool getPreview () const
void setPreview (const bool &state)
bool getOnlyDirs () const
void setOnlyDirs (const bool &state)
QString getParentPath ()
QString getPreviousPath ()
void setPreviousPath (const QString &path)
QString getPosteriorPath ()
void setPosteriorPath (const QString &path)
bool getPathEmpty () const
bool getPathExists () const
bool getTrackChanges () const
void setTrackChanges (const bool &value)
bool getIsBookmark () const
void setIsBookmark (const bool &value)
bool getFoldersFirst () const
void setFoldersFirst (const bool &value)
bool getSaveDirProps () const
void setSaveDirProps (const bool &value)
bool getContentReady () const
void setContentReady (const bool &value)
VIEW_TYPE getViewType () const
void setViewType (const VIEW_TYPE &value)
int getCloudDepth () const
void setCloudDepth (const int &value)
Properties
QString path = QString()
bool hidden = false
bool onlyDirs = false
bool preview = false
FMList::VIEW_TYPE viewType
int cloudDepth = 1
bool isBookmark = false
bool contentReady = false
QStringList filters = {}
FMList::FILTER filterType = FMList::FILTER::NONE
FMList::SORTBY sortBy
bool foldersFirst = false
FMList::PATHTYPE pathType = FMList::PATHTYPE::PLACES_PATH
bool trackChanges = true
bool saveDirProps = false
bool pathExists = false
bool pathEmpty = true
QString previousPath
QString posteriorPath
QString parentPath
Private Member Functions
void pre ()
void pos ()
void reset ()
void setList ()
void sortList ()
void watchPath (const QString &path, const bool &clear=true)
void search (const QString &query, const QString &path, const bool &hidden=false, const bool &onlyDirs=false, const QStringList &filters=QStringList())
Private Attributes
FM * fm
QFileSystemWatcher * watcher
FMH::MODEL_LIST list = {{}}
VIEW_TYPE viewType = VIEW_TYPE::ICON_VIEW
FMList::SORTBY sort = FMList::SORTBY::MODIFIED
QStringList prevHistory = {}
QStringList postHistory = {}
Detailed Description
Definition at line 27 of file fmlist.h.
Member Enumeration Documentation
SORTBY
enum FMList::SORTBY : uint_fast8_t
Enumerator
SIZE
MODIFIED
DATE
LABEL
MIME
ADDDATE
TITLE
PLACE
FORMAT
Definition at line 61 of file fmlist.h.
                     : uint_fast8_t
         {
             SIZE = FMH::MODEL_KEY::SIZE,
             MODIFIED = FMH::MODEL_KEY::MODIFIED,
             DATE = FMH::MODEL_KEY::DATE,
             LABEL = FMH::MODEL_KEY::LABEL,
             MIME = FMH::MODEL_KEY::MIME,
             ADDDATE = FMH::MODEL_KEY::MIME,
             TITLE = FMH::MODEL_KEY::TITLE,
             PLACE = FMH::MODEL_KEY::PLACE,
             FORMAT = FMH::MODEL_KEY::FORMAT
         }; Q_ENUM(SORTBY)
Constructor & Destructor Documentation
~FMList()
FMList::~FMList ()
Definition at line 81 of file fmlist.cpp.
 {}
Member Function Documentation
cloudDepthChanged
void FMList::cloudDepthChanged () signal
contentReadyChanged
void FMList::contentReadyChanged () signal
copyInto
void FMList::copyInto (const QVariantList & files) slot
Definition at line 556 of file fmlist.cpp.
 {
     if(this->pathType == FMList::PATHTYPE::PLACES_PATH ||  this->pathType == FMList::PATHTYPE::CLOUD_PATH)
         this->fm->copy(files, this->path);
 }
References FMH::CLOUD_PATH, and FMH::PLACES_PATH.
createDir
void FMList::createDir (const QString & name) slot
Definition at line 546 of file fmlist.cpp.
 {
     if(this->pathType == FMList::PATHTYPE::PLACES_PATH)
         this->fm->createDir(this->path, name);
     else if(this->pathType == FMList::PATHTYPE::CLOUD_PATH)
     {
         this->fm->createCloudDir(QString(this->path).replace(FMH::PATHTYPE_NAME[FMH::PATHTYPE_KEY::CLOUD_PATH]+"/"+this->fm->sync->getUser(), ""), name);
     }
 }
References FMH::CLOUD_PATH, FMH::PATHTYPE_NAME, and FMH::PLACES_PATH.
cutInto
void FMList::cutInto (const QVariantList & files) slot
Definition at line 567 of file fmlist.cpp.
 {
     if(this->pathType == FMList::PATHTYPE::PLACES_PATH)
         this->fm->cut(files, this->path);
 //  else if(this->pathType == FMList::PATHTYPE::CLOUD_PATH)
 //  {
 //      this->fm->createCloudDir(QString(this->path).replace(FMH::PATHTYPE_NAME[FMList::PATHTYPE::CLOUD_PATH]+"/"+this->fm->sync->getUser(), ""), name);
 //  }
 }
References FMH::PLACES_PATH.
filtersChanged
void FMList::filtersChanged () signal
filterTypeChanged
void FMList::filterTypeChanged () signal
foldersFirstChanged
void FMList::foldersFirstChanged () signal
get
QVariantMap FMList::get (const int & index) const slot
Definition at line 527 of file fmlist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return QVariantMap();
     QVariantMap res;
     const auto model = this->list.at(index);
     for(auto key : model.keys())
         res.insert(FMH::MODEL_NAME[key], model[key]);
     return res;
 }
References FMH::MODEL_NAME.
getCloudDepth()
int FMList::getCloudDepth () const
Definition at line 770 of file fmlist.cpp.
 {
     return this->cloudDepth;
 }
getContentReady()
bool FMList::getContentReady () const
Definition at line 716 of file fmlist.cpp.
 {
     return this->contentReady;
 }
getFilters()
QStringList FMList::getFilters () const
Definition at line 438 of file fmlist.cpp.
 {
     return this->filters;
 }
getFilterType()
FMList::FILTER FMList::getFilterType () const
Definition at line 454 of file fmlist.cpp.
 {
     return this->filterType;
 }
getFoldersFirst()
bool FMList::getFoldersFirst () const
Definition at line 668 of file fmlist.cpp.
 {
     return this->foldersFirst;
 }
getHidden()
bool FMList::getHidden () const
Definition at line 470 of file fmlist.cpp.
 {
     return this->hidden;
 }
getIsBookmark()
bool FMList::getIsBookmark () const
Definition at line 645 of file fmlist.cpp.
 {
     return this->isBookmark;
 }
getOnlyDirs()
bool FMList::getOnlyDirs () const
Definition at line 511 of file fmlist.cpp.
 {
     return this->onlyDirs;
 }
getParentPath()
QString FMList::getParentPath ()
Definition at line 577 of file fmlist.cpp.
 {
     switch(this->pathType)
     {
         case FMList::PATHTYPE::PLACES_PATH:
             return FM::parentDir(this->path);
         default:
             return this->getPreviousPath();
     }
 }
References FM::parentDir(), and FMH::PLACES_PATH.
getPath()
QString FMList::getPath () const
Definition at line 364 of file fmlist.cpp.
 {
     return this->path;
 }
getPathEmpty()
bool FMList::getPathEmpty () const
Definition at line 621 of file fmlist.cpp.
 {
     return this->pathEmpty;
 }
getPathExists()
bool FMList::getPathExists () const
Definition at line 626 of file fmlist.cpp.
 {
     return this->pathExists;
 }
getPathType()
FMList::PATHTYPE FMList::getPathType () const
Definition at line 433 of file fmlist.cpp.
 {
     return this->pathType;
 }
getPosteriorPath()
QString FMList::getPosteriorPath ()
Definition at line 589 of file fmlist.cpp.
 {
     if(this->postHistory.isEmpty())
         return this->path;
     return this->postHistory.takeAt(this->postHistory.length()-1);
 }
getPreview()
bool FMList::getPreview () const
Definition at line 491 of file fmlist.cpp.
 {
     return this->preview;
 }
getPreviousPath()
QString FMList::getPreviousPath ()
Definition at line 602 of file fmlist.cpp.
 {
     if(this->prevHistory.isEmpty())
         return this->path;
     if(this->prevHistory.length() < 2)
         return this->prevHistory.at(0);
     auto post = this->prevHistory.takeAt(this->prevHistory.length()-1);
     this->setPosteriorPath(post);
     return this->prevHistory.takeAt(this->prevHistory.length()-1);
 }
getSaveDirProps()
bool FMList::getSaveDirProps () const
Definition at line 705 of file fmlist.cpp.
 {
     return this->saveDirProps;
 }
getSortBy()
FMList::SORTBY FMList::getSortBy () const
Definition at line 221 of file fmlist.cpp.
 {
     return this->sort;
 }
getTrackChanges()
bool FMList::getTrackChanges () const
Definition at line 631 of file fmlist.cpp.
 {
     return this->trackChanges;
 }
getViewType()
FMList::VIEW_TYPE FMList::getViewType () const
Definition at line 721 of file fmlist.cpp.
 {
     return this->viewType;
 }
hiddenChanged
void FMList::hiddenChanged () signal
isBookmarkChanged
void FMList::isBookmarkChanged () signal
items()
FMH::MODEL_LIST FMList::items () const
Definition at line 215 of file fmlist.cpp.
 {
     return this->list;
 }
Referenced by FMModel::data(), FMModel::rowCount(), and FMModel::setList().
onlyDirsChanged
void FMList::onlyDirsChanged () signal
pathChanged
void FMList::pathChanged () signal
pathEmptyChanged
void FMList::pathEmptyChanged () signal
pathExistsChanged
void FMList::pathExistsChanged () signal
pathTypeChanged
void FMList::pathTypeChanged () signal
pos()
void FMList::pos () private
Definition at line 90 of file fmlist.cpp.
 {
     //  this->setContentReady(true);
     emit this->postListChanged();
 }
postItemAppended
void FMList::postItemAppended () signal
Referenced by FMModel::setList().
postItemRemoved
void FMList::postItemRemoved () signal
Referenced by FMModel::setList().
postListChanged
void FMList::postListChanged () signal
Referenced by FMModel::setList().
pre()
void FMList::pre () private
Definition at line 84 of file fmlist.cpp.
 {
     emit this->preListChanged();
     //  this->setContentReady(false);
 }
preItemAppended
void FMList::preItemAppended () signal
Referenced by FMModel::setList().
preItemRemoved
void FMList::preItemRemoved (int index) signal
Referenced by FMModel::setList().
preListChanged
void FMList::preListChanged () signal
Referenced by FMModel::setList().
previewChanged
void FMList::previewChanged () signal
progress
void FMList::progress (int percent) signal
Q_ENUM()
Q_ENUM (SORTBY) enum FILTER Q_ENUM (FILTER) enum PATHTYPE Q_ENUM (PATHTYPE) enum VIEW_TYPE FMList::Q_ENUM (VIEW_TYPE)
refresh
void FMList::refresh () slot
Definition at line 541 of file fmlist.cpp.
 {
     emit this->pathChanged();
 }
reset()
void FMList::reset () private
Definition at line 150 of file fmlist.cpp.
 {
     this->pre();
     switch(this->pathType)
     {
         case FMList::PATHTYPE::APPS_PATH:
             this->hidden = false;
             this->preview = false;
             break;
         case FMList::PATHTYPE::CLOUD_PATH:
         case FMList::PATHTYPE::SEARCH_PATH:
         case FMList::PATHTYPE::TAGS_PATH:
             this->hidden = false;
             this->preview = true;
             break;
         case FMList::PATHTYPE::PLACES_PATH:
         {
             if(this->saveDirProps)
             {
                 auto conf = FMH::dirConf(this->path+"/.directory");
                 this->hidden = conf[FMH::MODEL_NAME[FMH::MODEL_KEY::HIDDEN]].toBool();
                 this->preview = conf[FMH::MODEL_NAME[FMH::MODEL_KEY::SHOWTHUMBNAIL]].toBool();
                 this->foldersFirst = conf[FMH::MODEL_NAME[FMH::MODEL_KEY::FOLDERSFIRST]].toBool();
             }else
             {
                 this->hidden = UTIL::loadSettings("HiddenFilesShown", "SETTINGS", this->hidden).toBool();
                 this->preview = UTIL::loadSettings("ShowThumbnail", "SETTINGS", this->preview).toBool();
                 this->foldersFirst = UTIL::loadSettings("FoldersFirst", "SETTINGS", this->foldersFirst).toBool();
             }
             break;
         }
         case FMList::PATHTYPE::TRASH_PATH:
         case FMList::PATHTYPE::DRIVES_PATH:
         case FMList::PATHTYPE::BOOKMARKS_PATH:
             break;
     }
     if(this->saveDirProps)
     {
         auto conf = FMH::dirConf(this->path+"/.directory");
         this->sort = static_cast<FMList::SORTBY>(conf[FMH::MODEL_NAME[FMH::MODEL_KEY::SORTBY]].toInt());
         this->viewType = static_cast<FMList::VIEW_TYPE>(conf[FMH::MODEL_NAME[FMH::MODEL_KEY::VIEWTYPE]].toInt());
     }else
     {
         this->sort = static_cast<FMList::SORTBY>(UTIL::loadSettings("SortBy", "SETTINGS", this->sort).toInt());
         this->viewType = static_cast<FMList::VIEW_TYPE>(UTIL::loadSettings("ViewType", "SETTINGS", this->viewType).toInt());
     }
     emit this->sortByChanged();
     emit this->viewTypeChanged();
     emit this->hiddenChanged();
     emit this->previewChanged();
     this->setList();
     this->pos();
 }
References FMH::APPS_PATH, FMH::BOOKMARKS_PATH, FMH::CLOUD_PATH, FMH::dirConf(), FMH::DRIVES_PATH, FMH::FOLDERSFIRST, FMH::HIDDEN, UTIL::loadSettings(), FMH::MODEL_NAME, FMH::PLACES_PATH, FMH::SEARCH_PATH, FMH::SHOWTHUMBNAIL, FMH::SORTBY, FMH::TAGS_PATH, FMH::TRASH_PATH, and FMH::VIEWTYPE.
saveDirPropsChanged
void FMList::saveDirPropsChanged () signal
search()
void FMList::search (const QString & query, const QString & path, const bool & hidden = false, const bool & onlyDirs = false, const QStringList & filters = QStringList()) private
Definition at line 741 of file fmlist.cpp.
 {
     FMH::MODEL_LIST content;
     if (FM::isDir(path))
     {
         QDir::Filters dirFilter;
         dirFilter = (onlyDirs ? QDir::AllDirs | QDir::NoDotDot | QDir::NoDot :
         QDir::Files | QDir::AllDirs | QDir::NoDotDot | QDir::NoDot);
         if(hidden)
             dirFilter = dirFilter | QDir::Hidden | QDir::System;
         QDirIterator it (path, filters, dirFilter, QDirIterator::NoIteratorFlags);
         while (it.hasNext())
         {
             auto url = it.next();
             auto info = it.fileInfo();
             if(info.completeBaseName().contains(query, Qt::CaseInsensitive))
             {
                 emit preItemAppended();
                 this->list << FMH::getFileInfoModel(url);
                 emit postItemAppended();
             }
         }
     }
 }
References FMH::getFileInfoModel(), and FM::isDir().
setCloudDepth()
void FMList::setCloudDepth (const int & value)
Definition at line 775 of file fmlist.cpp.
 {
     if(this->cloudDepth == value)
         return;
     this->cloudDepth = value;
     emit this->cloudDepthChanged();
     this->reset();
 }
setContentReady()
void FMList::setContentReady (const bool & value)
Definition at line 710 of file fmlist.cpp.
 {
     this->contentReady = value;
     emit this->contentReadyChanged();
 }
setFilters()
void FMList::setFilters (const QStringList & filters)
Definition at line 443 of file fmlist.cpp.
 {
     if(this->filters == filters)
         return;
     this->filters = filters;
     emit this->filtersChanged();
     this->reset();
 }
setFilterType()
void FMList::setFilterType (const FMList::FILTER & type)
Definition at line 459 of file fmlist.cpp.
 {
     this->filterType = type;
     this->filters = FMH::FILTER_LIST[static_cast<FMH::FILTER_TYPE>(this->filterType)];
     emit this->filtersChanged();
     emit this->filterTypeChanged();
     this->reset();
 }
References FMH::FILTER_LIST.
setFoldersFirst()
void FMList::setFoldersFirst (const bool & value)
Definition at line 673 of file fmlist.cpp.
 {
     if(this->foldersFirst == value)
         return;
     this->pre();
     this->foldersFirst = value;
     if(this->pathType == FMList::PATHTYPE::PLACES_PATH && this->trackChanges && this->saveDirProps)
         FMH::setDirConf(this->path+"/.directory", "MAUIFM", "FoldersFirst", this->foldersFirst);
     else
         UTIL::saveSettings("FoldersFirst", this->foldersFirst, "SETTINGS");
     emit this->foldersFirstChanged();
     this->sortList();
     this->pos();
 }
References FMH::PLACES_PATH, UTIL::saveSettings(), and FMH::setDirConf().
setHidden()
void FMList::setHidden (const bool & state)
Definition at line 475 of file fmlist.cpp.
 {
     if(this->hidden == state)
         return;
     this->hidden = state;
     if(this->pathType == FMList::PATHTYPE::PLACES_PATH && this->trackChanges && this->saveDirProps)
         FMH::setDirConf(this->path+"/.directory", "Settings", "HiddenFilesShown", this->hidden);
     else
         UTIL::saveSettings("HiddenFilesShown", this->hidden, "SETTINGS");
     emit this->hiddenChanged();
     this->reset();
 }
References FMH::PLACES_PATH, UTIL::saveSettings(), and FMH::setDirConf().
setIsBookmark()
void FMList::setIsBookmark (const bool & value)
Definition at line 650 of file fmlist.cpp.
 {
     if(this->isBookmark == value)
         return;
     if(this->pathType != FMList::PATHTYPE::PLACES_PATH)
         return;
     this->isBookmark = value;
     if(value)
         this->fm->bookmark(this->path);
     else
         this->fm->removeBookmark(this->path);
     emit this->isBookmarkChanged();
 }
References FMH::PLACES_PATH.
setList()
void FMList::setList () private
Definition at line 107 of file fmlist.cpp.
 {
     this->setContentReady(true);
     switch(this->pathType)
     {
         case FMList::PATHTYPE::SEARCH_PATH:
             this->list.clear();
             this->search(QString(this->path).right(this->path.length()- 1 - this->path.lastIndexOf("/")), this->prevHistory.length() > 1 ? this->prevHistory[this->prevHistory.length()-2] : this->path);
             return;
         case FMList::PATHTYPE::APPS_PATH:
             this->list = FM::getAppsContent(this->path);
             break;
         case FMList::PATHTYPE::TAGS_PATH:
             this->list = this->fm->getTagContent(QString(this->path).right(this->path.length()- 1 - this->path.lastIndexOf("/")));
             break;
         case FMList::PATHTYPE::PLACES_PATH:
             this->list = FM::getPathContent(this->path, this->hidden, this->onlyDirs, this->filters);
             break;
         case FMList::PATHTYPE::CLOUD_PATH:
             this->list.clear();
             if(this->fm->getCloudServerContent(this->path, this->filters, this->cloudDepth))
             {
                 this->setContentReady(false);
                 return;
             }else break;
         case FMList::PATHTYPE::TRASH_PATH:
         case FMList::PATHTYPE::DRIVES_PATH:
         case FMList::PATHTYPE::BOOKMARKS_PATH:
             this->list = FMH::MODEL_LIST();
             break;
     }
     this->pathEmpty = this->list.isEmpty() && FM::fileExists(this->path);
     emit this->pathEmptyChanged();
     this->sortList();
 }
References FMH::APPS_PATH, FMH::BOOKMARKS_PATH, FMH::CLOUD_PATH, FMH::DRIVES_PATH, FM::fileExists(), FM::getAppsContent(), FM::getPathContent(), FMH::PLACES_PATH, FMH::SEARCH_PATH, FMH::TAGS_PATH, and FMH::TRASH_PATH.
setOnlyDirs()
void FMList::setOnlyDirs (const bool & state)
Definition at line 516 of file fmlist.cpp.
 {
     if(this->onlyDirs == state)
         return;
     this->onlyDirs = state;
     emit this->onlyDirsChanged();
     this->reset();
 }
setPath()
void FMList::setPath (const QString & path)
Definition at line 369 of file fmlist.cpp.
 {
     if(this->path == path)
         return;
     this->path = path;
     this->setPreviousPath(this->path);
     qDebug()<< "Prev History" << this->prevHistory;
     if(path.startsWith(FMH::PATHTYPE_NAME[FMH::PATHTYPE_KEY::SEARCH_PATH]+"/"))
     {
         this->pathExists = true;
         this->pathType = FMList::PATHTYPE::SEARCH_PATH;
         this->isBookmark = false;
         emit this->pathExistsChanged();
         emit this->pathTypeChanged();
         emit this->isBookmarkChanged();
         this->watchPath(QString());
     }else if(path.startsWith(FMH::PATHTYPE_NAME[FMH::PATHTYPE_KEY::CLOUD_PATH]+"/"))
     {
         this->pathExists = true;
         this->pathType = FMList::PATHTYPE::CLOUD_PATH;
         this->isBookmark = false;
         emit this->pathExistsChanged();
         emit this->pathTypeChanged();
         emit this->isBookmarkChanged();
         this->watchPath(QString());
     }else if(path.startsWith(FMH::PATHTYPE_NAME[FMH::PATHTYPE_KEY::APPS_PATH]+"/"))
     {
         this->pathExists = true;
         this->pathType = FMList::PATHTYPE::APPS_PATH;
         this->isBookmark = false;
         emit this->pathExistsChanged();
         emit this->pathTypeChanged();
         emit this->isBookmarkChanged();
         this->watchPath(QString());
     }else if(path.startsWith(FMH::PATHTYPE_NAME[FMH::PATHTYPE_KEY::TAGS_PATH]+"/"))
     {
         this->pathExists = true;
         this->isBookmark = false;
         this->pathType = FMList::PATHTYPE::TAGS_PATH;
         emit this->pathExistsChanged();
         emit this->pathTypeChanged();
         emit this->isBookmarkChanged();
         this->watchPath(QString());
     }else
     {
         this->watchPath(this->path);
         this->isBookmark = this->fm->isBookmark(this->path);
         this->pathExists = FMH::fileExists(this->path);
         this->pathType = FMList::PATHTYPE::PLACES_PATH;
         emit this->pathExistsChanged();
         emit this->pathTypeChanged();
         emit this->isBookmarkChanged();
     }
     emit this->pathChanged();
 }
References FMH::APPS_PATH, FMH::CLOUD_PATH, FMH::fileExists(), FMH::PATHTYPE_NAME, FMH::PLACES_PATH, FMH::SEARCH_PATH, and FMH::TAGS_PATH.
setPosteriorPath()
void FMList::setPosteriorPath (const QString & path)
Definition at line 597 of file fmlist.cpp.
 {
     this->postHistory.append(path);
 }
setPreview()
void FMList::setPreview (const bool & state)
Definition at line 496 of file fmlist.cpp.
 {
     if(this->preview == state)
         return;
     this->preview = state;
     if(this->pathType == FMList::PATHTYPE::PLACES_PATH && this->trackChanges && this->saveDirProps)
         FMH::setDirConf(this->path+"/.directory", "MAUIFM", "ShowThumbnail", this->preview);
     else
         UTIL::saveSettings("ShowThumbnail", this->preview, "SETTINGS");
     emit this->previewChanged();
 }
References FMH::PLACES_PATH, UTIL::saveSettings(), and FMH::setDirConf().
setPreviousPath()
void FMList::setPreviousPath (const QString & path)
Definition at line 616 of file fmlist.cpp.
 {
     this->prevHistory.append(path);
 }
setSaveDirProps()
void FMList::setSaveDirProps (const bool & value)
Definition at line 694 of file fmlist.cpp.
 {
     if(this->saveDirProps == value)
         return;
     this->saveDirProps = value;
     UTIL::saveSettings("SaveDirProps", this->saveDirProps, "SETTINGS");
     emit this->saveDirPropsChanged();
 }
References UTIL::saveSettings().
setSortBy()
void FMList::setSortBy (const FMList::SORTBY & key)
Definition at line 226 of file fmlist.cpp.
 {
     if(this->sort == key)
         return;
     this->pre();
     this->sort = key;
     this->sortList();
     if(this->pathType == FMList::PATHTYPE::PLACES_PATH && this->trackChanges && this->saveDirProps)
         FMH::setDirConf(this->path+"/.directory", "MAUIFM", "SortBy", this->sort);
     else
         UTIL::saveSettings("SortBy", this->sort, "SETTINGS");
     emit this->sortByChanged();
     this->pos();
 }
References FMH::PLACES_PATH, UTIL::saveSettings(), and FMH::setDirConf().
setTrackChanges()
void FMList::setTrackChanges (const bool & value)
Definition at line 636 of file fmlist.cpp.
 {
     if(this->trackChanges == value)
         return;
     this->trackChanges = value;
     emit this->trackChangesChanged();
 }
setViewType()
void FMList::setViewType (const VIEW_TYPE & value)
Definition at line 726 of file fmlist.cpp.
 {
     if(this->viewType == value)
         return;
     this->viewType = value;
     if(this->trackChanges && this->saveDirProps)
         FMH::setDirConf(this->path+"/.directory", "MAUIFM", "ViewType", this->viewType);
     else
         UTIL::saveSettings("ViewType", this->viewType, "SETTINGS");
     emit this->viewTypeChanged();
 }
References UTIL::saveSettings(), and FMH::setDirConf().
sortByChanged
void FMList::sortByChanged () signal
sortList()
void FMList::sortList () private
Definition at line 246 of file fmlist.cpp.
 {
     FMH::MODEL_KEY key = static_cast<FMH::MODEL_KEY>(this->sort);
     auto index = 0;
     if(this->foldersFirst)
     {
         qSort(this->list.begin(), this->list.end(), [](const FMH::MODEL& e1, const FMH::MODEL& e2) -> bool
         {
             const auto key = FMH::MODEL_KEY::MIME;
             if(e1[key] == "inode/directory")
                 return true;
             return false;
         });
         for(auto item : this->list)
             if(item[FMH::MODEL_KEY::MIME] == "inode/directory")
                 index++;
             else break;
         qSort(this->list.begin(),this->list.begin() + index, [key](const FMH::MODEL& e1, const FMH::MODEL& e2) -> bool
         {
             auto role = key;
             switch(role)
             {
                 case FMH::MODEL_KEY::SIZE:
                 {
                     if(e1[role].toDouble() > e2[role].toDouble())
                         return true;
                     break;
                 }
                 case FMH::MODEL_KEY::MODIFIED:
                 case FMH::MODEL_KEY::DATE:
                 {
                     auto currentTime = QDateTime::currentDateTime();
                     auto date1 = QDateTime::fromString(e1[role], Qt::TextDate);
                     auto date2 = QDateTime::fromString(e2[role], Qt::TextDate);
                     if(date1.secsTo(currentTime) <  date2.secsTo(currentTime))
                         return true;
                     break;
                 }
                 case FMH::MODEL_KEY::LABEL:
                 {
                     const auto str1 = QString(e1[role]).toLower();
                     const auto str2 = QString(e2[role]).toLower();
                     if(str1 < str2)
                         return true;
                     break;
                 }
                 default:
                     if(e1[role] < e2[role])
                         return true;
             }
             return false;
         });
     }
     qSort(this->list.begin() + index, this->list.end(), [key](const FMH::MODEL& e1, const FMH::MODEL& e2) -> bool
     {
         auto role = key;
         switch(role)
         {
             case FMH::MODEL_KEY::MIME:
                 if(e1[role] == "inode/directory")
                     return true;
                 break;
             case FMH::MODEL_KEY::SIZE:
             {
                 if(e1[role].toDouble() > e2[role].toDouble())
                     return true;
                 break;
             }
             case FMH::MODEL_KEY::MODIFIED:
             case FMH::MODEL_KEY::DATE:
             {
                 auto currentTime = QDateTime::currentDateTime();
                 auto date1 = QDateTime::fromString(e1[role], Qt::TextDate);
                 auto date2 = QDateTime::fromString(e2[role], Qt::TextDate);
                 if(date1.secsTo(currentTime) <  date2.secsTo(currentTime))
                     return true;
                 break;
             }
             case FMH::MODEL_KEY::LABEL:
             {
                 const auto str1 = QString(e1[role]).toLower();
                 const auto str2 = QString(e2[role]).toLower();
                 if(str1 < str2)
                     return true;
                 break;
             }
             default:
                 if(e1[role] < e2[role])
                     return true;
         }
         return false;
     });
 }
References FMH::DATE, FMH::LABEL, FMH::MIME, FMH::MODIFIED, and FMH::SIZE.
test
void FMList::test () slot
Definition at line 562 of file fmlist.cpp.
 {
     this->fm->sync->upload("", "");
 }
trackChangesChanged
void FMList::trackChangesChanged () signal
updateModel
void FMList::updateModel (int index, QVector< int > roles) signal
Referenced by FMModel::setList().
viewTypeChanged
void FMList::viewTypeChanged () signal
warning
void FMList::warning (QString message) signal
watchPath()
void FMList::watchPath (const QString & path, const bool & clear = true) private
Definition at line 96 of file fmlist.cpp.
 {
     if(!this->watcher->directories().isEmpty() && clear)
         this->watcher->removePaths(this->watcher->directories());
     if(path.isEmpty() || !FMH::fileExists(path))
         return;
     this->watcher->addPath(path);
 }
References FMH::fileExists().
Field Documentation
fm
FM* FMList::fm private
Definition at line 167 of file fmlist.h.
list
FMH::MODEL_LIST FMList::list = {{}} private
Definition at line 177 of file fmlist.h.
postHistory
QStringList FMList::postHistory = {} private
Definition at line 200 of file fmlist.h.
prevHistory
QStringList FMList::prevHistory = {} private
Definition at line 199 of file fmlist.h.
sort
FMList::SORTBY FMList::sort = FMList::SORTBY::MODIFIED private
Definition at line 195 of file fmlist.h.
viewType
VIEW_TYPE FMList::viewType = VIEW_TYPE::ICON_VIEW private
Definition at line 194 of file fmlist.h.
watcher
QFileSystemWatcher* FMList::watcher private
Definition at line 168 of file fmlist.h.
Property Documentation
cloudDepth
int FMList::cloudDepth = 1 read write
Definition at line 37 of file fmlist.h.
contentReady
bool FMList::contentReady = false read
Definition at line 40 of file fmlist.h.
filters
QStringList FMList::filters = {} read write
Definition at line 42 of file fmlist.h.
filterType
FMList::FILTER FMList::filterType = FMList::FILTER::NONE read write
Definition at line 43 of file fmlist.h.
foldersFirst
bool FMList::foldersFirst = false read write
Definition at line 46 of file fmlist.h.
hidden
bool FMList::hidden = false read write
Definition at line 33 of file fmlist.h.
isBookmark
bool FMList::isBookmark = false read write
Definition at line 39 of file fmlist.h.
onlyDirs
bool FMList::onlyDirs = false read write
Definition at line 34 of file fmlist.h.
parentPath
QString FMList::parentPath read
Definition at line 57 of file fmlist.h.
path
QString FMList::path = QString() read write
Definition at line 31 of file fmlist.h.
pathEmpty
bool FMList::pathEmpty = true read
Definition at line 53 of file fmlist.h.
pathExists
bool FMList::pathExists = false read
Definition at line 52 of file fmlist.h.
pathType
FMList::PATHTYPE FMList::pathType = FMList::PATHTYPE::PLACES_PATH read
Definition at line 47 of file fmlist.h.
posteriorPath
QString FMList::posteriorPath read
Definition at line 56 of file fmlist.h.
preview
bool FMList::preview = false read write
Definition at line 35 of file fmlist.h.
previousPath
QString FMList::previousPath read
Definition at line 55 of file fmlist.h.
saveDirProps
bool FMList::saveDirProps = false read write
Definition at line 50 of file fmlist.h.
sortBy
FMList::SORTBY FMList::sortBy read write
Definition at line 45 of file fmlist.h.
trackChanges
bool FMList::trackChanges = true read write
Definition at line 49 of file fmlist.h.
viewType
FMList::VIEW_TYPE FMList::viewType read write
Definition at line 36 of file fmlist.h.
The documentation for this class was generated from the following files:
fm/fmlist.h
fm/fmlist.cpp