MauiKit: SyncingList Class Reference
SyncingList Class Reference
#include <syncinglist.h>
Public Slots
QVariantMap get (const int &index) const
void insert (const QVariantMap &data)
void removeAccount (const QString &server, const QString &user)
void removeAccountAndFiles (const QString &server, const QString &user)
void refresh ()
Signals
void preItemAppended ()
void postItemAppended ()
void preItemRemoved (int index)
void postItemRemoved ()
void updateModel (int index, QVector< int > roles)
void preListChanged ()
void postListChanged ()
Public Member Functions
SyncingList (QObject *parent=nullptr)
FMH::MODEL_LIST items () const
Private Member Functions
void setList ()
Private Attributes
FMH::MODEL_LIST list
FM * fm
Detailed Description
Definition at line 8 of file syncinglist.h.
Constructor & Destructor Documentation
SyncingList()
SyncingList::SyncingList (QObject * parent = nullptr) explicit
Definition at line 4 of file syncinglist.cpp.
                                         : QObject(parent)
 {
     this->fm = new FM(this);
     this->setList();
 }
References fm, and setList().
Member Function Documentation
get
QVariantMap SyncingList::get (const int & index) const slot
Definition at line 20 of file syncinglist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return QVariantMap();
     const auto folder = this->list.at(index);
     QVariantMap res;
     for(auto key : folder.keys())
         res.insert(FMH::MODEL_NAME[key], folder[key]);
     return res;
 }
References list, and FMH::MODEL_NAME.
insert
void SyncingList::insert (const QVariantMap & data) slot
Definition at line 39 of file syncinglist.cpp.
 {
     FMH::MODEL model;
     for(auto key : data.keys())
         model.insert(FMH::MODEL_NAME_KEY[key], data[key].toString());
     if(this->fm->addCloudAccount(model[FMH::MODEL_KEY::SERVER], model[FMH::MODEL_KEY::USER], model[FMH::MODEL_KEY::PASSWORD]))
     {
         this->setList();
     }
 }
References FM::addCloudAccount(), fm, FMH::MODEL_NAME_KEY, FMH::PASSWORD, FMH::SERVER, setList(), and FMH::USER.
items()
FMH::MODEL_LIST SyncingList::items () const
Definition at line 71 of file syncinglist.cpp.
 {
     return this->list;
 }
References list.
Referenced by SyncingModel::data(), SyncingModel::rowCount(), and SyncingModel::setList().
postItemAppended
void SyncingList::postItemAppended () signal
Referenced by SyncingModel::setList().
postItemRemoved
void SyncingList::postItemRemoved () signal
Referenced by SyncingModel::setList().
postListChanged
void SyncingList::postListChanged () signal
Referenced by setList(), and SyncingModel::setList().
preItemAppended
void SyncingList::preItemAppended () signal
Referenced by SyncingModel::setList().
preItemRemoved
void SyncingList::preItemRemoved (int index) signal
Referenced by SyncingModel::setList().
preListChanged
void SyncingList::preListChanged () signal
Referenced by setList(), and SyncingModel::setList().
refresh
void SyncingList::refresh () slot
Definition at line 34 of file syncinglist.cpp.
 {
     this->setList();
 }
References setList().
Referenced by removeAccount(), and removeAccountAndFiles().
removeAccount
void SyncingList::removeAccount (const QString & server, const QString & user) slot
Definition at line 51 of file syncinglist.cpp.
 {
     if(this->fm->removeCloudAccount(server, user))
     {
         this->refresh();
     }
 }
References fm, refresh(), and FM::removeCloudAccount().
removeAccountAndFiles
void SyncingList::removeAccountAndFiles (const QString & server, const QString & user) slot
Definition at line 59 of file syncinglist.cpp.
 {
     if(this->fm->removeCloudAccount(server, user))
     {
         this->refresh();
     }
     this->fm->removeDir(FM::resolveUserCloudCachePath(server, user));
 }
References fm, refresh(), FM::removeCloudAccount(), FM::removeDir(), and FM::resolveUserCloudCachePath().
setList()
void SyncingList::setList () private
Definition at line 10 of file syncinglist.cpp.
 {
     emit this->preListChanged();
     this->list = this->fm->getCloudAccounts();
     qDebug()<< "SYNCIGN LIST"<< list;
     emit this->postListChanged();
 }
References fm, FM::getCloudAccounts(), list, postListChanged(), and preListChanged().
Referenced by insert(), refresh(), and SyncingList().
updateModel
void SyncingList::updateModel (int index, QVector< int > roles) signal
Referenced by SyncingModel::setList().
Field Documentation
fm
FM* SyncingList::fm private
Definition at line 19 of file syncinglist.h.
Referenced by insert(), removeAccount(), removeAccountAndFiles(), setList(), and SyncingList().
list
FMH::MODEL_LIST SyncingList::list private
Definition at line 17 of file syncinglist.h.
Referenced by get(), items(), and setList().
The documentation for this class was generated from the following files:
utils/syncing/syncinglist.h
utils/syncing/syncinglist.cpp