MauiKit: FMDB Class Reference
FMDB Class Reference
#include <fmdb.h>
Public Member Functions
Q_INVOKABLE bool checkExistance (const QString &tableName, const QString &searchId, const QString &search)
Q_INVOKABLE bool checkExistance (const QString &queryStr)
Protected Member Functions
FMDB (QObject *parent=nullptr)
~ FMDB ()
QSqlQuery getQuery (const QString &queryTxt)
void openDB (const QString &name)
void prepareCollectionDB () const
bool insert (const QString &tableName, const QVariantMap &insertData)
bool update (const QString &tableName, const FMH::DB &updateData, const QVariantMap &where)
bool update (const QString &table, const QString &column, const QVariant &newValue, const QVariant &op, const QString &id)
bool remove (const QString &tableName, const FMH::DB &removeData)
Private Attributes
QString name
QSqlDatabase m_db
Detailed Description
Definition at line 29 of file fmdb.h.
Constructor & Destructor Documentation
FMDB()
FMDB::FMDB (QObject * parent = nullptr) protected
Definition at line 6 of file fmdb.cpp.
                           : QObject(parent)
 {
     QDir collectionDBPath_dir(FMH::FMPath);
     if (!collectionDBPath_dir.exists())
         collectionDBPath_dir.mkpath(".");
     this->name = QUuid::createUuid().toString();
     if(!UTIL::fileExists(FMH::FMPath + FMH::DBName))
     {
         this->openDB(this->name);
         this->prepareCollectionDB();
     }else this->openDB(this->name);
 }
References FMH::DBName, UTIL::fileExists(), FMH::FMPath, name, openDB(), and prepareCollectionDB().
~ FMDB()
FMDB::~ FMDB () protected
Member Function Documentation
checkExistance() [1/2]
bool FMDB::checkExistance (const QString & tableName, const QString & searchId, const QString & search)
Definition at line 100 of file fmdb.cpp.
 {
     auto queryStr = QString("SELECT %1 FROM %2 WHERE %3 = \"%4\"").arg(searchId, tableName, searchId, search);
     auto query = this->getQuery(queryStr);
     if (query.exec())
     {
         if (query.next()) return true;
     }else qDebug()<<query.lastError().text();
     return false;
 }
References getQuery().
Referenced by FM::isBookmark().
checkExistance() [2/2]
bool FMDB::checkExistance (const QString & queryStr)
Definition at line 113 of file fmdb.cpp.
 {
     auto query = this->getQuery(queryStr);
     if (query.exec())
     {
         if (query.next()) return true;
     }else qDebug()<<query.lastError().text();
     return false;
 }
References getQuery().
getQuery()
QSqlQuery FMDB::getQuery (const QString & queryTxt) protected
Definition at line 125 of file fmdb.cpp.
 {
     QSqlQuery query(queryTxt, this->m_db);
     return query;
 }
References m_db.
Referenced by checkExistance(), FM::get(), openDB(), remove(), and update().
insert()
bool FMDB::insert (const QString & tableName, const QVariantMap & insertData) protected
Definition at line 131 of file fmdb.cpp.
 {
     if (tableName.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The table name is empty!");
         return false;
     } else if (insertData.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The insertData is empty!");
         return false;
     }
     QStringList strValues;
     QStringList fields = insertData.keys();
     QVariantList values = insertData.values();
     int totalFields = fields.size();
     for (int i = 0; i < totalFields; ++i)
         strValues.append("?");
     QString sqlQueryString = "INSERT INTO " + tableName + " (" + QString(fields.join(",")) + ") VALUES(" + QString(strValues.join(",")) + ")";
     QSqlQuery query(this->m_db);
     query.prepare(sqlQueryString);
     int k = 0;
     foreach (const QVariant &value, values)
         query.bindValue(k++, value);
     return query.exec();
 }
References m_db.
Referenced by FM::addCloudAccount(), and FM::bookmark().
openDB()
void FMDB::openDB (const QString & name) protected
Definition at line 25 of file fmdb.cpp.
 {
     if(!QSqlDatabase::contains(name))
     {
         this->m_db = QSqlDatabase::addDatabase(QStringLiteral("QSQLITE"), name);
         this->m_db.setDatabaseName(FMH::FMPath + FMH::DBName);
     }
     if (!this->m_db.isOpen())
     {
         if(!this->m_db.open())
             qDebug()<<"ERROR OPENING DB"<<this->m_db.lastError().text()<<m_db.connectionName();
     }
     auto query = this->getQuery("PRAGMA synchronous=OFF");
     query.exec();
 }
References FMH::DBName, FMH::FMPath, getQuery(), m_db, and name.
Referenced by FMDB().
prepareCollectionDB()
void FMDB::prepareCollectionDB () const protected
Definition at line 42 of file fmdb.cpp.
 {
     QSqlQuery query(this->m_db);
     QFile file(":/fm/script.sql");
     if (!file.exists())
     {
         QString log = QStringLiteral("Fatal error on build database. The file '");
         log.append(file.fileName() + QStringLiteral("' for database and tables creation query cannot be not found!"));
         qDebug()<<log;
         return;
     }
     if (!file.open(QIODevice::ReadOnly))
     {
         qDebug()<<QStringLiteral("Fatal error on try to create database! The file with sql queries for database creation cannot be opened!");
         return;
     }
     bool hasText;
     QString line;
     QByteArray readLine;
     QString cleanedLine;
     QStringList strings;
     while (!file.atEnd())
     {
         hasText     = false;
         line        = "";
         readLine    = "";
         cleanedLine = "";
         strings.clear();
         while (!hasText)
         {
             readLine    = file.readLine();
             cleanedLine = readLine.trimmed();
             strings     = cleanedLine.split("--");
             cleanedLine = strings.at(0);
             if (!cleanedLine.startsWith("--") && !cleanedLine.startsWith("DROP") && !cleanedLine.isEmpty())
                 line += cleanedLine;
             if (cleanedLine.endsWith(";"))
                 break;
             if (cleanedLine.startsWith("COMMIT"))
                 hasText = true;
         }
         if (!line.isEmpty())
         {
             if (!query.exec(line))
             {
                 qDebug()<<"exec failed"<<query.lastQuery()<<query.lastError();
             }
         } else qDebug()<<"exec wrong"<<query.lastError();
     }
     file.close();
 }
References m_db.
Referenced by FMDB().
remove()
bool FMDB::remove (const QString & tableName, const FMH::DB & removeData) protected
Definition at line 195 of file fmdb.cpp.
 {
     if (tableName.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on removing! The table name is empty!");
         return false;
     } else if (removeData.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The removeData is empty!");
         return false;
     }
     QString strValues;
         auto i = 0;
     for (auto key : removeData.keys())
     {
         strValues.append(QString("%1 = \"%2\"").arg(FMH::MODEL_NAME[key], removeData[key]));
         i++;
         if(removeData.keys().size() > 1 && i<removeData.keys().size())
             strValues.append(" AND ");
     }
     QString sqlQueryString = "DELETE FROM " + tableName + " WHERE " + strValues;
     qDebug()<< sqlQueryString;
     return this->getQuery(sqlQueryString).exec();
 }
References getQuery(), and FMH::MODEL_NAME.
Referenced by FM::removeBookmark(), and FM::removeCloudAccount().
update() [1/2]
bool FMDB::update (const QString & tableName, const FMH::DB & updateData, const QVariantMap & where) protected
Definition at line 162 of file fmdb.cpp.
 {
     if (tableName.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The table name is empty!");
         return false;
     } else if (updateData.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The insertData is empty!");
         return false;
     }
     QStringList set;
     for (auto key : updateData.keys())
         set.append(FMH::MODEL_NAME[key]+" = '"+updateData[key]+"'");
     QStringList condition;
     for (auto key : where.keys())
         condition.append(key+" = '"+where[key].toString()+"'");
     QString sqlQueryString = "UPDATE " + tableName + " SET " + QString(set.join(",")) + " WHERE " + QString(condition.join(",")) ;
     auto query = this->getQuery(sqlQueryString);
     qDebug()<<sqlQueryString;
     return query.exec();
 }
References getQuery(), and FMH::MODEL_NAME.
update() [2/2]
bool FMDB::update (const QString & table, const QString & column, const QVariant & newValue, const QVariant & op, const QString & id) protected
Definition at line 188 of file fmdb.cpp.
 {
     auto queryStr = QString("UPDATE %1 SET %2 = \"%3\" WHERE %4 = \"%5\"").arg(table, column, newValue.toString().replace("\"","\"\""), op.toString(), id);
     auto query = this->getQuery(queryStr);
     return query.exec();
 }
References getQuery().
Field Documentation
m_db
QSqlDatabase FMDB::m_db private
Definition at line 36 of file fmdb.h.
Referenced by getQuery(), insert(), openDB(), and prepareCollectionDB().
name
QString FMDB::name private
Definition at line 35 of file fmdb.h.
Referenced by FM::createCloudDir(), FM::createDir(), FM::createFile(), FMDB(), openDB(), and FM::rename().
The documentation for this class was generated from the following files:
fm/fmdb.h
fm/fmdb.cpp