MauiKit: DocumentHandler Class Reference
DocumentHandler Class Reference
#include <documenthandler.h>
Public Slots
void load (const QUrl &fileUrl)
void saveAs (const QUrl &fileUrl)
Signals
void documentChanged ()
void cursorPositionChanged ()
void selectionStartChanged ()
void selectionEndChanged ()
void fontFamilyChanged ()
void textColorChanged ()
void alignmentChanged ()
void boldChanged ()
void uppercaseChanged ()
void italicChanged ()
void underlineChanged ()
void isRichChanged ()
void fontSizeChanged ()
void textChanged ()
void fileUrlChanged ()
void loaded (const QString &text)
void error (const QString &message)
Public Member Functions
DocumentHandler (QObject *parent=nullptr)
QQuickTextDocument * document () const
void setDocument (QQuickTextDocument *document)
int cursorPosition () const
void setCursorPosition (int position)
int selectionStart () const
void setSelectionStart (int position)
int selectionEnd () const
void setSelectionEnd (int position)
QString fontFamily () const
void setFontFamily (const QString &family)
QColor textColor () const
void setTextColor (const QColor &color)
Qt::Alignment alignment () const
void setAlignment (Qt::Alignment alignment)
bool bold () const
void setBold (bool bold)
bool uppercase () const
void setUppercase (bool uppercase)
bool italic () const
void setItalic (bool italic)
bool underline () const
void setUnderline (bool underline)
bool isRich () const
int fontSize () const
void setFontSize (int size)
QString fileName () const
QString fileType () const
QUrl fileUrl () const
Properties
QQuickTextDocument document
int cursorPosition
int selectionStart
int selectionEnd
QColor textColor
QString fontFamily
Qt::Alignment alignment
bool bold
bool uppercase
bool italic
bool underline
bool isRich
int fontSize
QString fileName
QString fileType
QUrl fileUrl
Private Member Functions
void reset ()
QTextCursor textCursor () const
QTextDocument * textDocument () const
void mergeFormatOnWordOrSelection (const QTextCharFormat &format)
Private Attributes
QQuickTextDocument * m_document
int m_cursorPosition
int m_selectionStart
int m_selectionEnd
QFont m_font
int m_fontSize
QUrl m_fileUrl
Detailed Description
Definition at line 64 of file documenthandler.h.
Constructor & Destructor Documentation
DocumentHandler()
DocumentHandler::DocumentHandler (QObject * parent = nullptr) explicit
Definition at line 65 of file documenthandler.cpp.
     : QObject(parent)
     , m_document(nullptr)
     , m_cursorPosition(-1)
     , m_selectionStart(0)
     , m_selectionEnd(0)
 {
 }
Member Function Documentation
alignment()
Qt::Alignment DocumentHandler::alignment () const
Referenced by setAlignment().
alignmentChanged
void DocumentHandler::alignmentChanged () signal
Referenced by reset(), and setAlignment().
bold()
bool DocumentHandler::bold () const
Referenced by setBold().
boldChanged
void DocumentHandler::boldChanged () signal
Referenced by reset(), and setBold().
cursorPosition()
int DocumentHandler::cursorPosition () const
cursorPositionChanged
void DocumentHandler::cursorPositionChanged () signal
Referenced by setCursorPosition().
document()
QQuickTextDocument* DocumentHandler::document () const
Referenced by setDocument().
documentChanged
void DocumentHandler::documentChanged () signal
Referenced by setDocument().
error
void DocumentHandler::error (const QString & message) signal
Referenced by saveAs().
fileName()
QString DocumentHandler::fileName () const
Referenced by load().
fileType()
QString DocumentHandler::fileType () const
fileUrl()
QUrl DocumentHandler::fileUrl () const
Referenced by load(), and saveAs().
fileUrlChanged
void DocumentHandler::fileUrlChanged () signal
Referenced by load(), and saveAs().
fontFamily()
QString DocumentHandler::fontFamily () const
fontFamilyChanged
void DocumentHandler::fontFamilyChanged () signal
Referenced by reset(), and setFontFamily().
fontSize()
int DocumentHandler::fontSize () const
fontSizeChanged
void DocumentHandler::fontSizeChanged () signal
Referenced by reset(), and setFontSize().
isRich()
bool DocumentHandler::isRich () const
isRichChanged
void DocumentHandler::isRichChanged () signal
italic()
bool DocumentHandler::italic () const
Referenced by setItalic().
italicChanged
void DocumentHandler::italicChanged () signal
Referenced by reset(), and setItalic().
load
void DocumentHandler::load (const QUrl & fileUrl) slot
Definition at line 303 of file documenthandler.cpp.
 {
     qDebug()<< "TRYING TO LOAD FILE << " << fileUrl;
     if (fileUrl == m_fileUrl)
         return;
     QQmlEngine *engine = qmlEngine(this);
     if (!engine) {
         qWarning() << "load() called before DocumentHandler has QQmlEngine";
         return;
     }
     const QUrl path = QQmlFileSelector::get(engine)->selector()->select(fileUrl);
     const QString fileName = QQmlFile::urlToLocalFileOrQrc(path);
     if (QFile::exists(fileName))
     {
         qDebug()<< "LOAD FILE EXISTS << ";
         QFile file(fileName);
         if (file.open(QFile::ReadOnly))
         {
             qDebug()<< "LOAD FILE OPENDED << ";
             QByteArray data = file.readAll();
             QTextCodec *codec = QTextCodec::codecForHtml(data);
             if (QTextDocument *doc = textDocument())
                 doc->setModified(false);
             emit loaded(codec->toUnicode(data));
             reset();
         }
     }
     m_fileUrl = fileUrl;
     emit fileUrlChanged();
 }
References fileName(), fileUrl(), fileUrlChanged(), loaded(), m_fileUrl, reset(), and textDocument().
loaded
void DocumentHandler::loaded (const QString & text) signal
Referenced by load().
mergeFormatOnWordOrSelection()
void DocumentHandler::mergeFormatOnWordOrSelection (const QTextCharFormat & format) private
Definition at line 402 of file documenthandler.cpp.
 {
     QTextCursor cursor = textCursor();
     if (!cursor.hasSelection())
         cursor.select(QTextCursor::WordUnderCursor);
     cursor.mergeCharFormat(format);
 }
References textCursor().
Referenced by setBold(), setFontFamily(), setFontSize(), setItalic(), setTextColor(), setUnderline(), and setUppercase().
reset()
void DocumentHandler::reset () private
Definition at line 367 of file documenthandler.cpp.
 {
     emit fontFamilyChanged();
     emit alignmentChanged();
     emit boldChanged();
     emit italicChanged();
     emit underlineChanged();
     emit fontSizeChanged();
     emit textColorChanged();
 }
References alignmentChanged(), boldChanged(), fontFamilyChanged(), fontSizeChanged(), italicChanged(), textColorChanged(), and underlineChanged().
Referenced by load(), and setCursorPosition().
saveAs
void DocumentHandler::saveAs (const QUrl & fileUrl) slot
Definition at line 344 of file documenthandler.cpp.
 {
     QTextDocument *doc = textDocument();
     if (!doc)
         return;
     const QString filePath = fileUrl.toLocalFile();
     const bool isHtml = QFileInfo(filePath).suffix().contains(QLatin1String("htm"));
     QFile file(filePath);
     if (!file.open(QFile::WriteOnly | QFile::Truncate | (isHtml ? QFile::NotOpen : QFile::Text))) {
         emit error(tr("Cannot save: ") + file.errorString());
         return;
     }
     file.write((isHtml ? doc->toHtml() : doc->toPlainText()).toUtf8());
     file.close();
     if (fileUrl == m_fileUrl)
         return;
     m_fileUrl = fileUrl;
     emit fileUrlChanged();
 }
References error(), fileUrl(), fileUrlChanged(), m_fileUrl, and textDocument().
selectionEnd()
int DocumentHandler::selectionEnd () const
selectionEndChanged
void DocumentHandler::selectionEndChanged () signal
Referenced by setSelectionEnd().
selectionStart()
int DocumentHandler::selectionStart () const
selectionStartChanged
void DocumentHandler::selectionStartChanged () signal
Referenced by setSelectionStart().
setAlignment()
void DocumentHandler::setAlignment (Qt::Alignment alignment)
Definition at line 173 of file documenthandler.cpp.
 {
     QTextBlockFormat format;
     format.setAlignment(alignment);
     QTextCursor cursor = textCursor();
     cursor.mergeBlockFormat(format);
     emit alignmentChanged();
 }
References alignment(), alignmentChanged(), and textCursor().
setBold()
void DocumentHandler::setBold (bool bold)
Definition at line 190 of file documenthandler.cpp.
 {
     QTextCharFormat format;
     format.setFontWeight(bold ? QFont::Bold : QFont::Normal);
     mergeFormatOnWordOrSelection(format);
     emit boldChanged();
 }
References bold(), boldChanged(), and mergeFormatOnWordOrSelection().
setCursorPosition()
void DocumentHandler::setCursorPosition (int position)
Definition at line 93 of file documenthandler.cpp.
 {
     if (position == m_cursorPosition)
         return;
     m_cursorPosition = position;
     reset();
     emit cursorPositionChanged();
 }
References cursorPositionChanged(), m_cursorPosition, and reset().
setDocument()
void DocumentHandler::setDocument (QQuickTextDocument * document)
Definition at line 79 of file documenthandler.cpp.
 {
     if (document == m_document)
         return;
     m_document = document;
     emit documentChanged();
 }
References document(), documentChanged(), and m_document.
setFontFamily()
void DocumentHandler::setFontFamily (const QString & family)
Definition at line 140 of file documenthandler.cpp.
 {
     QTextCharFormat format;
     format.setFontFamily(family);
     mergeFormatOnWordOrSelection(format);
     emit fontFamilyChanged();
 }
References fontFamilyChanged(), and mergeFormatOnWordOrSelection().
setFontSize()
void DocumentHandler::setFontSize (int size)
Definition at line 263 of file documenthandler.cpp.
 {
     if (size <= 0)
         return;
     QTextCursor cursor = textCursor();
     if (cursor.isNull())
         return;
     if (!cursor.hasSelection())
         cursor.select(QTextCursor::WordUnderCursor);
     if (cursor.charFormat().property(QTextFormat::FontPointSize).toInt() == size)
         return;
     QTextCharFormat format;
     format.setFontPointSize(size);
     mergeFormatOnWordOrSelection(format);
     emit fontSizeChanged();
 }
References fontSizeChanged(), mergeFormatOnWordOrSelection(), and textCursor().
setItalic()
void DocumentHandler::setItalic (bool italic)
Definition at line 222 of file documenthandler.cpp.
 {
     QTextCharFormat format;
     format.setFontItalic(italic);
     mergeFormatOnWordOrSelection(format);
     emit italicChanged();
 }
References italic(), italicChanged(), and mergeFormatOnWordOrSelection().
setSelectionEnd()
void DocumentHandler::setSelectionEnd (int position)
Definition at line 122 of file documenthandler.cpp.
 {
     if (position == m_selectionEnd)
         return;
     m_selectionEnd = position;
     emit selectionEndChanged();
 }
References m_selectionEnd, and selectionEndChanged().
setSelectionStart()
void DocumentHandler::setSelectionStart (int position)
Definition at line 108 of file documenthandler.cpp.
 {
     if (position == m_selectionStart)
         return;
     m_selectionStart = position;
     emit selectionStartChanged();
 }
References m_selectionStart, and selectionStartChanged().
setTextColor()
void DocumentHandler::setTextColor (const QColor & color)
Definition at line 157 of file documenthandler.cpp.
 {
     QTextCharFormat format;
     format.setForeground(QBrush(color));
     mergeFormatOnWordOrSelection(format);
     emit textColorChanged();
 }
References mergeFormatOnWordOrSelection(), and textColorChanged().
setUnderline()
void DocumentHandler::setUnderline (bool underline)
Definition at line 238 of file documenthandler.cpp.
 {
     QTextCharFormat format;
     format.setFontUnderline(underline);
     mergeFormatOnWordOrSelection(format);
     emit underlineChanged();
 }
References mergeFormatOnWordOrSelection(), underline(), and underlineChanged().
setUppercase()
void DocumentHandler::setUppercase (bool uppercase)
Definition at line 206 of file documenthandler.cpp.
 {
     QTextCharFormat format;
     format.setFontCapitalization(uppercase ? QFont::AllUppercase : QFont::AllLowercase);
     mergeFormatOnWordOrSelection(format);
     emit uppercaseChanged();
 }
References mergeFormatOnWordOrSelection(), uppercase(), and uppercaseChanged().
textChanged
void DocumentHandler::textChanged () signal
textColor()
QColor DocumentHandler::textColor () const
textColorChanged
void DocumentHandler::textColorChanged () signal
Referenced by reset(), and setTextColor().
textCursor()
QTextCursor DocumentHandler::textCursor () const private
Definition at line 378 of file documenthandler.cpp.
 {
     QTextDocument *doc = textDocument();
     if (!doc)
         return QTextCursor();
     QTextCursor cursor = QTextCursor(doc);
     if (m_selectionStart != m_selectionEnd) {
         cursor.setPosition(m_selectionStart);
         cursor.setPosition(m_selectionEnd, QTextCursor::KeepAnchor);
     } else {
         cursor.setPosition(m_cursorPosition);
     }
     return cursor;
 }
References m_cursorPosition, m_selectionEnd, m_selectionStart, and textDocument().
Referenced by mergeFormatOnWordOrSelection(), setAlignment(), and setFontSize().
textDocument()
QTextDocument * DocumentHandler::textDocument () const private
Definition at line 394 of file documenthandler.cpp.
 {
     if (!m_document)
         return nullptr;
     return m_document->textDocument();
 }
References m_document.
Referenced by load(), saveAs(), and textCursor().
underline()
bool DocumentHandler::underline () const
Referenced by setUnderline().
underlineChanged
void DocumentHandler::underlineChanged () signal
Referenced by reset(), and setUnderline().
uppercase()
bool DocumentHandler::uppercase () const
Referenced by setUppercase().
uppercaseChanged
void DocumentHandler::uppercaseChanged () signal
Referenced by setUppercase().
Field Documentation
m_cursorPosition
int DocumentHandler::m_cursorPosition private
Definition at line 170 of file documenthandler.h.
Referenced by setCursorPosition(), and textCursor().
m_document
QQuickTextDocument* DocumentHandler::m_document private
Definition at line 168 of file documenthandler.h.
Referenced by setDocument(), and textDocument().
m_fileUrl
QUrl DocumentHandler::m_fileUrl private
Definition at line 176 of file documenthandler.h.
Referenced by load(), and saveAs().
m_font
QFont DocumentHandler::m_font private
Definition at line 174 of file documenthandler.h.
m_fontSize
int DocumentHandler::m_fontSize private
Definition at line 175 of file documenthandler.h.
m_selectionEnd
int DocumentHandler::m_selectionEnd private
Definition at line 172 of file documenthandler.h.
Referenced by setSelectionEnd(), and textCursor().
m_selectionStart
int DocumentHandler::m_selectionStart private
Definition at line 171 of file documenthandler.h.
Referenced by setSelectionStart(), and textCursor().
Property Documentation
alignment
Qt::Alignment DocumentHandler::alignment read write
Definition at line 75 of file documenthandler.h.
bold
bool DocumentHandler::bold read write
Definition at line 77 of file documenthandler.h.
cursorPosition
int DocumentHandler::cursorPosition read write
Definition at line 69 of file documenthandler.h.
document
QQuickTextDocument * DocumentHandler::document read write
Definition at line 68 of file documenthandler.h.
fileName
QString DocumentHandler::fileName read
Definition at line 85 of file documenthandler.h.
fileType
QString DocumentHandler::fileType read
Definition at line 86 of file documenthandler.h.
fileUrl
QUrl DocumentHandler::fileUrl read
Definition at line 87 of file documenthandler.h.
fontFamily
QString DocumentHandler::fontFamily read write
Definition at line 74 of file documenthandler.h.
fontSize
int DocumentHandler::fontSize read write
Definition at line 83 of file documenthandler.h.
isRich
bool DocumentHandler::isRich read
Definition at line 81 of file documenthandler.h.
italic
bool DocumentHandler::italic read write
Definition at line 79 of file documenthandler.h.
selectionEnd
int DocumentHandler::selectionEnd read write
Definition at line 71 of file documenthandler.h.
selectionStart
int DocumentHandler::selectionStart read write
Definition at line 70 of file documenthandler.h.
textColor
QColor DocumentHandler::textColor read write
Definition at line 73 of file documenthandler.h.
underline
bool DocumentHandler::underline read write
Definition at line 80 of file documenthandler.h.
uppercase
bool DocumentHandler::uppercase read write
Definition at line 78 of file documenthandler.h.
The documentation for this class was generated from the following files:
utils/editor/documenthandler.h
utils/editor/documenthandler.cpp