MauiKit: MAUIKDE Class Reference
MAUIKDE Class Reference
#include <mauikde.h>
Public Member Functions
MAUIKDE (QObject *parent=nullptr)
~MAUIKDE ()
Static Public Member Functions
static Q_INVOKABLE QVariantList services (const QUrl &url)
static Q_INVOKABLE QVariantList devices ()
static Q_INVOKABLE bool sendToDevice (const QString &device, const QString &id, const QStringList &urls)
static Q_INVOKABLE void openWithApp (const QString &exec, const QStringList &urls)
static Q_INVOKABLE void attachEmail (const QStringList &urls)
static Q_INVOKABLE void email (const QString &to="", const QString &cc="", const QString &bcc="", const QString &subject="", const QString &body="", const QString &messageFile="", const QStringList &urls=QStringList())
static Q_INVOKABLE void setColorScheme (const QString &schemeName, const QString &bg=QString(), const QString &fg=QString())
static FMH::MODEL_LIST getApps ()
static FMH::MODEL_LIST getApps (const QString &groupStr)
static void launchApp (const QString &app)
Detailed Description
Definition at line 27 of file mauikde.h.
Constructor & Destructor Documentation
MAUIKDE()
MAUIKDE::MAUIKDE (QObject * parent = nullptr)
Definition at line 45 of file mauikde.cpp.
                                 : QObject(parent)
 {
 }
~MAUIKDE()
MAUIKDE::~MAUIKDE ()
Definition at line 49 of file mauikde.cpp.
 {
 }
Member Function Documentation
attachEmail()
void MAUIKDE::attachEmail (const QStringList & urls) static
Definition at line 117 of file mauikde.cpp.
 {
     if(urls.isEmpty()) return;
     QFileInfo file(urls[0]);
     KToolInvocation::invokeMailer("", "", "", file.baseName(), "Files shared... ", "", urls);
     //    QDesktopServices::openUrl(QUrl("mailto:?subject=test&body=test&attachment;="
     //    + url));
 }
devices()
QVariantList MAUIKDE::devices () static
Definition at line 106 of file mauikde.cpp.
 {
     return KdeConnect::getDevices();
 }
References KdeConnect::getDevices().
email()
void MAUIKDE::email (const QString & to = "", const QString & cc = "", const QString & bcc = "", const QString & subject = "", const QString & body = "", const QString & messageFile = "", const QStringList & urls = QStringList()) static
Definition at line 128 of file mauikde.cpp.
 {
     KToolInvocation::invokeMailer(to, cc, bcc, subject, body, messageFile, urls);
     //    QDesktopServices::openUrl(QUrl("mailto:?subject=test&body=test&attachment;="
     //    + url));
 }
getApps() [1/2]
FMH::MODEL_LIST MAUIKDE::getApps () static
Definition at line 225 of file mauikde.cpp.
 {
     FMH::MODEL_LIST res;
     KServiceGroup::Ptr group = KServiceGroup::root();
     bool sortByGenericName = false;
     KServiceGroup::List list = group->entries(true /* sorted */, true /* excludeNoDisplay */,
                                               true /* allowSeparators */, sortByGenericName /* sortByGenericName */);
     for (KServiceGroup::List::ConstIterator it = list.constBegin(); it != list.constEnd(); it++)
     {
         const KSycocaEntry::Ptr p = (*it);
         if (p->isType(KST_KServiceGroup))
         {
             KServiceGroup::Ptr s(static_cast<KServiceGroup*>(p.data()));
             if (!s->noDisplay() && s->childCount() > 0)
             {
                 qDebug()<< "Getting app"<<s->icon();
                 res << FMH::MODEL
                 {
                     {FMH::MODEL_KEY::ICON, s->icon()},
                     {FMH::MODEL_KEY::LABEL, s->name()},
                     {FMH::MODEL_KEY::PATH, FMH::PATHTYPE_NAME[FMH::PATHTYPE_KEY::APPS_PATH]+"/"+s->entryPath()}
                 };
             }
         }
     }
     return res;
 }
References FMH::APPS_PATH, FMH::ICON, FMH::LABEL, FMH::PATH, and FMH::PATHTYPE_NAME.
Referenced by getApps(), and FM::getAppsContent().
getApps() [2/2]
FMH::MODEL_LIST MAUIKDE::getApps (const QString & groupStr) static
Definition at line 259 of file mauikde.cpp.
 {
     if(groupStr.isEmpty()) return getApps();
     FMH::MODEL_LIST res;
     //    const KServiceGroup::Ptr group(static_cast<KServiceGroup*>(groupStr));
     auto group = new KServiceGroup(groupStr);
     KServiceGroup::List list = group->entries(true /* sorted */,
                                               true /* excludeNoDisplay */,
                                            false /* allowSeparators */,
                                            true /* sortByGenericName */);
     for (KServiceGroup::List::ConstIterator it = list.constBegin(); it != list.constEnd(); it++)
     {
         const KSycocaEntry::Ptr p = (*it);
         if (p->isType(KST_KService))
         {
             const KService::Ptr s(static_cast<KService*>(p.data()));
             if (s->noDisplay())
                 continue;
             res << FMH::MODEL {
                 {FMH::MODEL_KEY::ICON, s->icon()},
                 {FMH::MODEL_KEY::LABEL, s->name()},
                 {FMH::MODEL_KEY::PATH, s->entryPath()}
             };
         } else if (p->isType(KST_KServiceSeparator))
         {
             qDebug()<< "separator wtf";
         } else if (p->isType(KST_KServiceGroup))
         {
             const KServiceGroup::Ptr s(static_cast<KServiceGroup*>(p.data()));
             if (s->childCount() == 0)
                 continue;
             res <<  FMH::MODEL {
                 {FMH::MODEL_KEY::ICON, s->icon()},
                 {FMH::MODEL_KEY::LABEL, s->name()},
                 {FMH::MODEL_KEY::PATH, FMH::PATHTYPE_NAME[FMH::PATHTYPE_KEY::APPS_PATH]+"/"+s->entryPath()}
             };
         }
     }
     return res;
 }
References FMH::APPS_PATH, getApps(), FMH::ICON, FMH::LABEL, FMH::PATH, and FMH::PATHTYPE_NAME.
launchApp()
void MAUIKDE::launchApp (const QString & app) static
Definition at line 312 of file mauikde.cpp.
 {
     KService service(app);
     KRun::runApplication(service,{}, nullptr);
 }
References UTIL::app.
Referenced by FM::runApplication().
openWithApp()
void MAUIKDE::openWithApp (const QString & exec, const QStringList & urls) static
Definition at line 111 of file mauikde.cpp.
 {
     KService service(exec);
     KRun::runApplication(service, QUrl::fromStringList(urls), nullptr);
 }
sendToDevice()
bool MAUIKDE::sendToDevice (const QString & device, const QString & id, const QStringList & urls) static
Definition at line 98 of file mauikde.cpp.
 {
     for(auto url : urls)
         KdeConnect::sendToDevice(device, id, url);
     return true;
 }
References KdeConnect::sendToDevice().
services()
QVariantList MAUIKDE::services (const QUrl & url) static
Definition at line 68 of file mauikde.cpp.
 {
     qDebug()<<"trying to get mimes";
     QVariantList list;
     if (url.isValid())
     {
         auto fileItem = new KFileItem(url);
         fileItem->determineMimeType();
         KService::List services = KMimeTypeTrader::self()->query(fileItem->mimetype(), "Application");
         if (!services.isEmpty())
             foreach (const KService::Ptr service, services)
             {
                 const QString text = service->name().replace('&', "&&");
                 QVariantMap item = createActionItem(text, "_kicker_fileItem_openWith", service->entryPath());
                 item["icon"] = service->icon();
                 item["serviceExec"] = service->exec();
                 list << item;
             }
             list << createActionItem(i18n("Properties"), "_kicker_fileItem_properties");
             return list;
     } else return list;
 }
References createActionItem().
setColorScheme()
void MAUIKDE::setColorScheme (const QString & schemeName, const QString & bg = QString(), const QString & fg = QString()) static
Definition at line 135 of file mauikde.cpp.
 {
     const QString colorSchemeDir = FMH::DataPath+"/color-schemes/";
     const QString colorsFile = colorSchemeDir+schemeName+".colors";
     if(!FMH::fileExists(colorSchemeDir))
         QDir(colorSchemeDir).mkpath(".");
     if(!FMH::fileExists(colorsFile))
     {
         QFile color_scheme_file(":/assets/maui-app.colors");
         if(color_scheme_file.copy(colorsFile))
         {
             QFile copied_scheme_file(colorsFile);
             copied_scheme_file.setPermissions(QFile::ReadOwner|QFile::WriteOwner|QFile::ExeOwner|QFile::ReadGroup|QFile::ExeGroup|QFile::ReadOther|QFile::ExeOther);
             KConfig new_scheme_file(colorsFile);
             auto new_scheme_name = new_scheme_file.group("General");
             new_scheme_name.writeEntry("Name",  QVariant(schemeName));
             new_scheme_name.writeEntry("ColorScheme",  QVariant(schemeName));
         }
     }
     KColorSchemeManager manager;
     auto schemeModel = manager.indexForScheme(schemeName);
     if(!schemeModel.isValid() && FMH::fileExists(colorsFile))
     {
         qDebug()<< "COLROS FILE EXISTS BUT IS INVALID";
         KConfig scheme_file(colorsFile);
         auto scheme_name = scheme_file.group("General");
         scheme_name.writeEntry("Name", QVariant(schemeName));
         scheme_name.writeEntry("ColorScheme",  QVariant(schemeName));
     }
     schemeModel = manager.indexForScheme(schemeName);
     if(schemeModel.isValid())
     {
         qDebug()<<"COLRO SCHEME IS VALID";
         if(!bg.isEmpty() || !fg.isEmpty())
         {
             qDebug()<<"COLRO SCHEME FILE EXISTS"<< colorsFile;
             KConfig file(colorsFile);
             auto group = file.group("WM");
             QColor color;
             if(!bg.isEmpty())
             {
                 color.setNamedColor(bg);
                 QVariantList rgb = {color.red(), color.green(), color.blue()};
                 group.writeEntry("activeBackground", QVariant::fromValue(rgb));
                 group.writeEntry("inactiveBackground", QVariant::fromValue(rgb));
             }
             if(!fg.isEmpty())
             {
                 color.setNamedColor(fg);
                 QVariantList rgb = {color.red(), color.green(), color.blue()};
                 group.writeEntry("activeForeground", QVariant::fromValue(rgb));
                 group.writeEntry("inactiveForeground", QVariant::fromValue(rgb));
             }
             file.group("Colors:Window");
             if(!bg.isEmpty())
             {
                 color.setNamedColor(bg);
                 QVariantList rgb = {color.red(), color.green(), color.blue()};
                 group.writeEntry("BackgroundNormal", QVariant::fromValue(rgb));
                 group.writeEntry("BackgroundAlternate", QVariant::fromValue(rgb));
             }
             if(!fg.isEmpty())
             {
                 color.setNamedColor(fg);
                 QVariantList rgb = {color.red(), color.green(), color.blue()};
                 group.writeEntry("ForegroundActive", QVariant::fromValue(rgb));
                 group.writeEntry("ForegroundInactive", QVariant::fromValue(rgb));
             }
         }
         manager.activateScheme(schemeModel);
     }
 }
References FMH::DataPath, and FMH::fileExists().
The documentation for this class was generated from the following files:
kde/mauikde.h
kde/mauikde.cpp