MauiKit: FMH::Downloader Class Reference
FMH::Downloader Class Reference
#include <fmh.h>
Signals
void progress (int percent)
void downloadReady ()
void fileSaved (QString path)
void warning (QString warning)
void dataReady (QByteArray array)
Public Member Functions
Downloader (QObject *parent=0)
virtual ~Downloader ()
void setFile (const QString &fileURL, const QString &fileName=QString())
void getArray (const QString &fileURL, const QMap< QString, QString > &headers={})
Private Slots
void onDownloadProgress (qint64 bytesRead, qint64 bytesTotal)
void onFinished (QNetworkReply *reply)
void onReadyRead ()
void onReplyFinished ()
Private Attributes
QNetworkAccessManager * manager
QNetworkReply * reply
QFile * file
Detailed Description
Definition at line 652 of file fmh.h.
Constructor & Destructor Documentation
Downloader()
FMH::Downloader::Downloader (QObject * parent = 0) inline explicit
Definition at line 657 of file fmh.h.
                                                  : QObject(parent)
         {
             this->manager = new QNetworkAccessManager;
         }
References manager.
~Downloader()
virtual FMH::Downloader::~Downloader () inline virtual
Definition at line 662 of file fmh.h.
         {
             this->manager->deleteLater();
         }
References manager.
Member Function Documentation
dataReady
void FMH::Downloader::dataReady (QByteArray array) signal
downloadReady
void FMH::Downloader::downloadReady () signal
Referenced by onFinished().
fileSaved
void FMH::Downloader::fileSaved (QString path) signal
Referenced by Store::downloadLink(), and onFinished().
getArray()
void FMH::Downloader::getArray (const QString & fileURL, const QMap< QString, QString > & headers = {}) inline
Definition at line 688 of file fmh.h.
                                                                                       {})
         {
             if(fileURL.isEmpty())
                 return;
             qDebug()<< "request from" << fileURL;
             QNetworkRequest request;
             request.setUrl(QUrl(fileURL));
             if(!headers.isEmpty())
                 for(auto key: headers.keys())
                     request.setRawHeader(key.toLocal8Bit(), headers[key].toLocal8Bit());
             reply = manager->get(request);
             connect(manager, &QNetworkAccessManager::finished, [this](QNetworkReply* reply)
             {
                 switch(reply->error())
                 {
                     case QNetworkReply::NoError:
                     {
                         qDebug("file is downloaded successfully.");
                         emit this->dataReady(reply->readAll());
                         break;
                     }
                     default:
                     {
                         qDebug() << reply->errorString();
                         emit this->warning(reply->errorString());
                     };
                 }
             });
         }
onDownloadProgress
void FMH::Downloader::onDownloadProgress (qint64 bytesRead, qint64 bytesTotal) inline private slot
Definition at line 737 of file fmh.h.
         {
             emit this->progress((bytesRead * bytesTotal) / 100);
         }
References progress().
Referenced by setFile().
onFinished
void FMH::Downloader::onFinished (QNetworkReply * reply) inline private slot
Definition at line 742 of file fmh.h.
         {
             switch(reply->error())
             {
                 case QNetworkReply::NoError:
                 {
                     qDebug("file is downloaded successfully.");
                     emit this->downloadReady();
                     break;
                 }
                 default:
                 {
                     emit this->warning(reply->errorString());
                 };
             }
             if(file->isOpen())
             {
                 file->close();
                 emit this->fileSaved(file->fileName());
                 file->deleteLater();
             }
         }
References downloadReady(), file, fileSaved(), reply, and warning().
Referenced by setFile().
onReadyRead
void FMH::Downloader::onReadyRead () inline private slot
Definition at line 767 of file fmh.h.
         {
             file->write(reply->readAll());
 //          emit this->fileSaved(file->fileName());
         }
References file, and reply.
Referenced by setFile().
onReplyFinished
void FMH::Downloader::onReplyFinished () inline private slot
Definition at line 773 of file fmh.h.
         {
             if(file->isOpen())
             {
                 file->close();
 //              emit this->fileSaved(file->fileName());
                 file->deleteLater();
             }
         }
References file.
Referenced by setFile().
progress
void FMH::Downloader::progress (int percent) signal
Referenced by onDownloadProgress().
setFile()
void FMH::Downloader::setFile (const QString & fileURL, const QString & fileName = QString()) inline
Definition at line 667 of file fmh.h.
         {
             QString filePath = fileURL;
             if(fileName.isEmpty() || fileURL.isEmpty())
                 return;
             QNetworkRequest request;
             request.setUrl(QUrl(fileURL));
             reply = manager->get(request);
             file = new QFile;
             file->setFileName(fileName);
             file->open(QIODevice::WriteOnly);
             connect(reply,SIGNAL(downloadProgress(qint64,qint64)),this,SLOT(onDownloadProgress(qint64,qint64)));
             connect(manager,SIGNAL(finished(QNetworkReply*)),this,SLOT(onFinished(QNetworkReply*)));
             connect(reply,SIGNAL(readyRead()),this,SLOT(onReadyRead()));
             connect(reply,SIGNAL(finished()),this,SLOT(onReplyFinished()));
         }
References file, manager, onDownloadProgress(), onFinished(), onReadyRead(), onReplyFinished(), and reply.
Referenced by Store::downloadLink().
warning
void FMH::Downloader::warning (QString warning) signal
Referenced by Store::downloadLink(), and onFinished().
Field Documentation
file
QFile* FMH::Downloader::file private
Definition at line 727 of file fmh.h.
Referenced by onFinished(), onReadyRead(), onReplyFinished(), and setFile().
manager
QNetworkAccessManager* FMH::Downloader::manager private
Definition at line 725 of file fmh.h.
Referenced by Downloader(), setFile(), and ~Downloader().
reply
QNetworkReply* FMH::Downloader::reply private
Definition at line 726 of file fmh.h.
Referenced by onFinished(), onReadyRead(), and setFile().
The documentation for this class was generated from the following file:
fm/fmh.h