MauiKit: WebDAVReply Class Reference
WebDAVReply Class Reference
#include <WebDAVReply.hpp>
Signals
void listDirResponse (QNetworkReply *listDirReply, QList< WebDAVItem > items)
void downloadResponse (QNetworkReply *downloadReply)
void downloadProgressResponse (qint64 bytesReceived, qint64 bytesTotal)
void uploadFinished (QNetworkReply *uploadReply)
void createDirFinished (QNetworkReply *createDirReply)
void copyFinished (QNetworkReply *copyReply)
void moveFinished (QNetworkReply *moveReply)
void removeFinished (QNetworkReply *removeReply)
void error (QNetworkReply::NetworkError err)
Public Member Functions
void sendListDirResponseSignal (QNetworkReply *listDirReply, QList< WebDAVItem > items)
void sendDownloadResponseSignal (QNetworkReply *downloadReply)
void sendDownloadProgressResponseSignal (qint64 bytesReceived, qint64 bytesTotal)
void sendUploadFinishedResponseSignal (QNetworkReply *uploadReply)
void sendDirCreatedResponseSignal (QNetworkReply *createDirReply)
void sendCopyResponseSignal (QNetworkReply *copyReply)
void sendMoveResponseSignal (QNetworkReply *moveReply)
void sendRemoveResponseSignal (QNetworkReply *removeReply)
void sendError (QNetworkReply::NetworkError err)
Detailed Description
Definition at line 18 of file WebDAVReply.hpp.
Member Function Documentation
copyFinished
void WebDAVReply::copyFinished (QNetworkReply * copyReply) signal
Referenced by sendCopyResponseSignal(), and TestWebDAVClient::testCopyDir().
createDirFinished
void WebDAVReply::createDirFinished (QNetworkReply * createDirReply) signal
Referenced by Syncing::createDir(), sendDirCreatedResponseSignal(), and TestWebDAVClient::testCreateDir().
downloadProgressResponse
void WebDAVReply::downloadProgressResponse (qint64 bytesReceived, qint64 bytesTotal) signal
Referenced by Syncing::download(), sendDownloadProgressResponseSignal(), and TestWebDAVClient::testDownload().
downloadResponse
void WebDAVReply::downloadResponse (QNetworkReply * downloadReply) signal
Referenced by Syncing::download(), sendDownloadResponseSignal(), and TestWebDAVClient::testDownload().
error
void WebDAVReply::error (QNetworkReply::NetworkError err) signal
Referenced by Syncing::createDir(), Syncing::download(), TestWebDAVClient::listDirOutputHandler(), Syncing::listDirOutputHandler(), sendError(), TestWebDAVClient::testCopyDir(), TestWebDAVClient::testCreateDir(), TestWebDAVClient::testDownload(), TestWebDAVClient::testMoveDir(), TestWebDAVClient::testRemove(), TestWebDAVClient::testRemoveDir(), TestWebDAVClient::testUpload(), and Syncing::upload().
listDirResponse
void WebDAVReply::listDirResponse (QNetworkReply * listDirReply, QList< WebDAVItem > items) signal
Referenced by TestWebDAVClient::listDirOutputHandler(), Syncing::listDirOutputHandler(), and sendListDirResponseSignal().
moveFinished
void WebDAVReply::moveFinished (QNetworkReply * moveReply) signal
Referenced by sendMoveResponseSignal(), and TestWebDAVClient::testMoveDir().
removeFinished
void WebDAVReply::removeFinished (QNetworkReply * removeReply) signal
Referenced by sendRemoveResponseSignal(), TestWebDAVClient::testRemove(), and TestWebDAVClient::testRemoveDir().
sendCopyResponseSignal()
void WebDAVReply::sendCopyResponseSignal (QNetworkReply * copyReply)
Definition at line 30 of file WebDAVReply.cpp.
{
   emit copyFinished(copyReply);
 }
References copyFinished().
Referenced by WebDAVClient::copy().
sendDirCreatedResponseSignal()
void WebDAVReply::sendDirCreatedResponseSignal (QNetworkReply * createDirReply)
Definition at line 26 of file WebDAVReply.cpp.
{
   emit createDirFinished(createDirReply);
 }
References createDirFinished().
Referenced by WebDAVClient::createDir().
sendDownloadProgressResponseSignal()
void WebDAVReply::sendDownloadProgressResponseSignal (qint64 bytesReceived, qint64 bytesTotal)
Definition at line 17 of file WebDAVReply.cpp.
{
   emit downloadProgressResponse(bytesReceived, bytesTotal);
 }
References downloadProgressResponse().
Referenced by WebDAVClient::downloadFrom().
sendDownloadResponseSignal()
void WebDAVReply::sendDownloadResponseSignal (QNetworkReply * downloadReply)
Definition at line 13 of file WebDAVReply.cpp.
{
   emit downloadResponse(downloadReply);
 }
References downloadResponse().
Referenced by WebDAVClient::downloadFrom().
sendError()
void WebDAVReply::sendError (QNetworkReply::NetworkError err)
Definition at line 42 of file WebDAVReply.cpp.
{
   emit error(err);
 }
References error().
Referenced by WebDAVClient::errorReplyHandler().
sendListDirResponseSignal()
void WebDAVReply::sendListDirResponseSignal (QNetworkReply * listDirReply, QList< WebDAVItem > items)
Definition at line 8 of file WebDAVReply.cpp.
{
   emit listDirResponse(listDirReply, items);
 }
References listDirResponse().
Referenced by WebDAVClient::listDir().
sendMoveResponseSignal()
void WebDAVReply::sendMoveResponseSignal (QNetworkReply * moveReply)
Definition at line 34 of file WebDAVReply.cpp.
{
   emit moveFinished(moveReply);
 }
References moveFinished().
Referenced by WebDAVClient::move().
sendRemoveResponseSignal()
void WebDAVReply::sendRemoveResponseSignal (QNetworkReply * removeReply)
Definition at line 38 of file WebDAVReply.cpp.
{
   emit removeFinished(removeReply);
 }
References removeFinished().
Referenced by WebDAVClient::remove().
sendUploadFinishedResponseSignal()
void WebDAVReply::sendUploadFinishedResponseSignal (QNetworkReply * uploadReply)
Definition at line 22 of file WebDAVReply.cpp.
{
   emit uploadFinished(uploadReply);
 }
References uploadFinished().
Referenced by WebDAVClient::uploadTo().
uploadFinished
void WebDAVReply::uploadFinished (QNetworkReply * uploadReply) signal
Referenced by sendUploadFinishedResponseSignal(), TestWebDAVClient::testUpload(), and Syncing::upload().
The documentation for this class was generated from the following files:
utils/syncing/libwebdavclient/lib/utils/WebDAVReply.hpp
utils/syncing/libwebdavclient/lib/utils/WebDAVReply.cpp