MauiKit: WebDAVClient Class Reference
WebDAVClient Class Reference
#include <WebDAVClient.hpp>
Public Member Functions
WebDAVClient (QString host, QString username, QString password)
WebDAVReply * listDir (QString path="/")
WebDAVReply * listDir (QString path, ListDepthEnum depth)
WebDAVReply * downloadFrom (QString path)
WebDAVReply * downloadFrom (QString path, qint64 startByte, qint64 endByte)
WebDAVReply * uploadTo (QString path, QString filename, QIODevice *file)
WebDAVReply * createDir (QString path, QString dirName)
WebDAVReply * copy (QString source, QString destination)
WebDAVReply * move (QString source, QString destination, bool overwrite=false)
WebDAVReply * remove (QString path)
~WebDAVClient ()
Private Member Functions
void errorReplyHandler (WebDAVReply *reply, QNetworkReply::NetworkError err)
Private Attributes
NetworkHelper * networkHelper
XMLHelper * xmlHelper
Detailed Description
Definition at line 24 of file WebDAVClient.hpp.
Constructor & Destructor Documentation
WebDAVClient()
WebDAVClient::WebDAVClient (QString host, QString username, QString password)
Definition at line 17 of file WebDAVClient.cpp.
{
   this->networkHelper = new NetworkHelper(host, username, password);
   this->xmlHelper = new XMLHelper();
   // TODO: Check for Timeout error in case of wrong host
 }
References networkHelper, and xmlHelper.
~WebDAVClient()
WebDAVClient::~WebDAVClient ()
Definition at line 229 of file WebDAVClient.cpp.
{
   this->networkHelper->deleteLater();
   delete this->xmlHelper;
 }
References networkHelper, and xmlHelper.
Member Function Documentation
copy()
WebDAVReply * WebDAVClient::copy (QString source, QString destination)
Definition at line 160 of file WebDAVClient.cpp.
{
   WebDAVReply* reply = new WebDAVReply();
   QMap<QString, QString> headers;
   QNetworkReply* copyReply;
   headers.insert("Destination", destination);
   copyReply = this->networkHelper->makeRequest("COPY", source, headers);
   connect(copyReply, &QNetworkReply::finished,
           [=]() { reply->sendCopyResponseSignal(copyReply); });
   connect(copyReply,
           QOverload<QNetworkReply::NetworkError>::of(&QNetworkReply::error),
           [=](QNetworkReply::NetworkError err) {
             this->errorReplyHandler(reply, err);
           });
   return reply;
 }
References errorReplyHandler(), NetworkHelper::makeRequest(), networkHelper, and WebDAVReply::sendCopyResponseSignal().
Referenced by WebDAVItem::copy(), and TestWebDAVClient::testCopyDir().
createDir()
WebDAVReply * WebDAVClient::createDir (QString path, QString dirName)
Definition at line 140 of file WebDAVClient.cpp.
{
   WebDAVReply* reply = new WebDAVReply();
   QMap<QString, QString> headers;
   QNetworkReply* createDirReply;
   createDirReply =
       this->networkHelper->makeRequest("MKCOL", path + "/" + dirName, headers);
   connect(createDirReply, &QNetworkReply::finished,
           [=]() { reply->sendDirCreatedResponseSignal(createDirReply); });
   connect(createDirReply,
           QOverload<QNetworkReply::NetworkError>::of(&QNetworkReply::error),
           [=](QNetworkReply::NetworkError err) {
             this->errorReplyHandler(reply, err);
           });
   return reply;
 }
References errorReplyHandler(), NetworkHelper::makeRequest(), networkHelper, and WebDAVReply::sendDirCreatedResponseSignal().
Referenced by WebDAVItem::createDir(), Syncing::createDir(), and TestWebDAVClient::testCreateDir().
downloadFrom() [1/2]
WebDAVReply * WebDAVClient::downloadFrom (QString path)
Definition at line 74 of file WebDAVClient.cpp.
{
   return this->downloadFrom(path, 0, -1);
 }
Referenced by WebDAVItem::download(), Syncing::download(), and TestWebDAVClient::testDownload().
downloadFrom() [2/2]
WebDAVReply * WebDAVClient::downloadFrom (QString path, qint64 startByte, qint64 endByte)
Definition at line 78 of file WebDAVClient.cpp.
{
   WebDAVReply* reply = new WebDAVReply();
   QString rangeVal;
   QTextStream stream(&rangeVal);
   QMap<QString, QString> headers;
   QNetworkReply* downloadReply;
   stream << "bytes=" << startByte << "-" << endByte;
   headers.insert("Range", rangeVal);
   downloadReply = this->networkHelper->makeRequest("GET", path, headers);
   connect(downloadReply, &QNetworkReply::finished,
           [=]() { reply->sendDownloadResponseSignal(downloadReply); });
   connect(
       downloadReply, &QNetworkReply::downloadProgress,
       [=](qint64 bytesReceived, qint64 bytesTotal) {
         if (bytesTotal == -1) {
           QString contentRange = QString(downloadReply->rawHeader(
               QByteArray::fromStdString("Content-Range")));
           QRegularExpression re("bytes (\\d*)-(\\d*)/(\\d*)");
           QRegularExpressionMatch match = re.match(contentRange);
           qint64 contentSize =
               match.captured(2).toInt() - match.captured(1).toInt();
           reply->sendDownloadProgressResponseSignal(bytesReceived, contentSize);
         } else {
           reply->sendDownloadProgressResponseSignal(bytesReceived, bytesTotal);
         }
       });
   connect(downloadReply,
           QOverload<QNetworkReply::NetworkError>::of(&QNetworkReply::error),
           [=](QNetworkReply::NetworkError err) {
             this->errorReplyHandler(reply, err);
           });
   return reply;
 }
References errorReplyHandler(), NetworkHelper::makeRequest(), networkHelper, WebDAVReply::sendDownloadProgressResponseSignal(), and WebDAVReply::sendDownloadResponseSignal().
errorReplyHandler()
void WebDAVClient::errorReplyHandler (WebDAVReply * reply, QNetworkReply::NetworkError err) private
Definition at line 224 of file WebDAVClient.cpp.
{
   reply->sendError(err);
 }
References WebDAVReply::sendError().
Referenced by copy(), createDir(), downloadFrom(), listDir(), move(), remove(), and uploadTo().
listDir() [1/2]
WebDAVReply * WebDAVClient::listDir (QString path = "/")
Definition at line 24 of file WebDAVClient.cpp.
{
   return this->listDir(path, ListDepthEnum::Infinity);
 }
References Infinity.
Referenced by Syncing::listContent(), WebDAVItem::listDir(), TestWebDAVClient::testListDir(), and TestWebDAVClient::testListDirWithDepth().
listDir() [2/2]
WebDAVReply * WebDAVClient::listDir (QString path, ListDepthEnum depth)
Definition at line 28 of file WebDAVClient.cpp.
{
   WebDAVReply* reply = new WebDAVReply();
   QString depthVal;
   QMap<QString, QString> headers;
   QNetworkReply* listDirReply;
   switch (depth) {
     case ListDepthEnum::Zero:
       depthVal = "0";
       break;
     case ListDepthEnum::One:
       depthVal = "1";
       break;
     case ListDepthEnum::Two:
       depthVal = "2";
       break;
     case ListDepthEnum::Infinity:
       depthVal = "infinity";
       break;
     default:
       break;
   }
   headers.insert("Depth", depthVal);
   listDirReply =
       this->networkHelper->makeRequest(QString("PROPFIND"), path, headers);
   connect(listDirReply, &QNetworkReply::finished, [=]() {
     reply->sendListDirResponseSignal(
         listDirReply,
         this->xmlHelper->parseListDirResponse(this, listDirReply->readAll()));
   });
   connect(listDirReply,
           QOverload<QNetworkReply::NetworkError>::of(&QNetworkReply::error),
           [=](QNetworkReply::NetworkError err) {
             this->errorReplyHandler(reply, err);
           });
   return reply;
 }
References errorReplyHandler(), Infinity, NetworkHelper::makeRequest(), networkHelper, One, XMLHelper::parseListDirResponse(), WebDAVReply::sendListDirResponseSignal(), Two, xmlHelper, and Zero.
move()
WebDAVReply * WebDAVClient::move (QString source, QString destination, bool overwrite = false)
Definition at line 181 of file WebDAVClient.cpp.
{
   WebDAVReply* reply = new WebDAVReply();
   QMap<QString, QString> headers;
   QNetworkReply* moveReply;
   QString overwriteVal = overwrite ? "T" : "F";
   headers.insert("Destination", destination);
   headers.insert("Overwrite", overwriteVal);
   moveReply = this->networkHelper->makeRequest("MOVE", source, headers);
   connect(moveReply, &QNetworkReply::finished,
           [=]() { reply->sendMoveResponseSignal(moveReply); });
   connect(moveReply,
           QOverload<QNetworkReply::NetworkError>::of(&QNetworkReply::error),
           [=](QNetworkReply::NetworkError err) {
             this->errorReplyHandler(reply, err);
           });
   return reply;
 }
References errorReplyHandler(), NetworkHelper::makeRequest(), networkHelper, and WebDAVReply::sendMoveResponseSignal().
Referenced by WebDAVItem::move(), and TestWebDAVClient::testMoveDir().
remove()
WebDAVReply * WebDAVClient::remove (QString path)
Definition at line 205 of file WebDAVClient.cpp.
{
   WebDAVReply* reply = new WebDAVReply();
   QMap<QString, QString> headers;
   QNetworkReply* removeReply;
   removeReply = this->networkHelper->makeRequest("DELETE", path, headers);
   connect(removeReply, &QNetworkReply::finished,
           [=]() { reply->sendRemoveResponseSignal(removeReply); });
   connect(removeReply,
           QOverload<QNetworkReply::NetworkError>::of(&QNetworkReply::error),
           [=](QNetworkReply::NetworkError err) {
             this->errorReplyHandler(reply, err);
           });
   return reply;
 }
References errorReplyHandler(), NetworkHelper::makeRequest(), networkHelper, and WebDAVReply::sendRemoveResponseSignal().
Referenced by WebDAVItem::remove(), TestWebDAVClient::testRemove(), and TestWebDAVClient::testRemoveDir().
uploadTo()
WebDAVReply * WebDAVClient::uploadTo (QString path, QString filename, QIODevice * file)
Definition at line 119 of file WebDAVClient.cpp.
{
   WebDAVReply* reply = new WebDAVReply();
   QMap<QString, QString> headers;
   QNetworkReply* uploadReply;
   uploadReply =
       this->networkHelper->makePutRequest(path + "/" + filename, headers, file);
   connect(uploadReply, &QNetworkReply::finished,
           [=]() { reply->sendUploadFinishedResponseSignal(uploadReply); });
   connect(uploadReply,
           QOverload<QNetworkReply::NetworkError>::of(&QNetworkReply::error),
           [=](QNetworkReply::NetworkError err) {
             this->errorReplyHandler(reply, err);
           });
   return reply;
 }
References errorReplyHandler(), NetworkHelper::makePutRequest(), networkHelper, and WebDAVReply::sendUploadFinishedResponseSignal().
Referenced by TestWebDAVClient::testUpload(), WebDAVItem::upload(), and Syncing::upload().
Field Documentation
networkHelper
NetworkHelper* WebDAVClient::networkHelper private
Definition at line 52 of file WebDAVClient.hpp.
Referenced by copy(), createDir(), downloadFrom(), listDir(), move(), remove(), uploadTo(), WebDAVClient(), and ~WebDAVClient().
xmlHelper
XMLHelper* WebDAVClient::xmlHelper private
Definition at line 53 of file WebDAVClient.hpp.
Referenced by listDir(), WebDAVClient(), and ~WebDAVClient().
The documentation for this class was generated from the following files:
utils/syncing/libwebdavclient/lib/WebDAVClient.hpp
utils/syncing/libwebdavclient/lib/WebDAVClient.cpp