MauiKit: PlacesModel Class Reference
PlacesModel Class Reference
#include <placesmodel.h>
Signals
void listChanged ()
Public Member Functions
PlacesModel (QObject *parent=nullptr)
~PlacesModel ()
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
virtual QHash< int, QByteArray > roleNames () const override
PlacesList * getList () const
void setList (PlacesList *value)
Properties
PlacesList list
Private Attributes
PlacesList * list
Detailed Description
Definition at line 27 of file placesmodel.h.
Constructor & Destructor Documentation
PlacesModel()
PlacesModel::PlacesModel (QObject * parent = nullptr)
Definition at line 26 of file placesmodel.cpp.
 : QAbstractListModel(parent), list(nullptr)
 {}
~PlacesModel()
PlacesModel::~PlacesModel ()
Definition at line 22 of file placesmodel.cpp.
 {
 }
Member Function Documentation
data()
QVariant PlacesModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 38 of file placesmodel.cpp.
 {
     if (!index.isValid() || !list)
         return QVariant();
     return list->items().at(index.row())[static_cast<FMH::MODEL_KEY>(role)];
 }
References PlacesList::items(), and list.
flags()
Qt::ItemFlags PlacesModel::flags (const QModelIndex & index) const override
Definition at line 55 of file placesmodel.cpp.
 {
     if (!index.isValid())
         return Qt::NoItemFlags;
     return Qt::ItemIsEditable; // FIXME: Implement me!
 }
getList()
PlacesList * PlacesModel::getList () const
Definition at line 73 of file placesmodel.cpp.
 {
     return this->list;
 }
References list.
listChanged
void PlacesModel::listChanged () signal
roleNames()
QHash< int, QByteArray > PlacesModel::roleNames () const override virtual
Definition at line 63 of file placesmodel.cpp.
 {
     QHash<int, QByteArray> names;
     for(auto key : FMH::MODEL_NAME.keys())
         names[key] = QString(FMH::MODEL_NAME[key]).toUtf8();
     return names;
 }
References FMH::MODEL_NAME.
rowCount()
int PlacesModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 30 of file placesmodel.cpp.
 {
     if (parent.isValid() || !list)
         return 0;
     return list->items().size();
 }
References PlacesList::items(), and list.
setData()
bool PlacesModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 46 of file placesmodel.cpp.
 {
     Q_UNUSED(index);
     Q_UNUSED(value);
     Q_UNUSED(role);
     return false;
 }
setList()
void PlacesModel::setList (PlacesList * value)
Definition at line 78 of file placesmodel.cpp.
 {
     beginResetModel();
     if(list)
         list->disconnect(this);
     list = value;
     if(list)
     {
         connect(this->list, &PlacesList::preItemAppended, this, [=]()
         {
             const int index = list->items().size();
             beginInsertRows(QModelIndex(), index, index);
         });
         connect(this->list, &PlacesList::postItemAppended, this, [=]()
         {
             endInsertRows();
         });
         connect(this->list, &PlacesList::preItemRemoved, this, [=](int index)
         {
             beginRemoveRows(QModelIndex(), index, index);
         });
         connect(this->list, &PlacesList::postItemRemoved, this, [=]()
         {
             endRemoveRows();
         });
         connect(this->list, &PlacesList::updateModel, this, [=](int index, QVector<int> roles)
         {
             emit this->dataChanged(this->index(index), this->index(index), roles);
         });
         //      connect(this->list, &PlacesList::pathChanged, this, [=]()
         //      {
         //          beginResetModel();
         //          endResetModel();
         //      });
         connect(this->list, &PlacesList::preListChanged, this, [=]()
         {
             beginResetModel();
         });
         connect(this->list, &PlacesList::postListChanged, this, [=]()
         {
             endResetModel();
         });
     }
     endResetModel();
 }
References PlacesList::items(), list, PlacesList::postItemAppended(), PlacesList::postItemRemoved(), PlacesList::postListChanged(), PlacesList::preItemAppended(), PlacesList::preItemRemoved(), PlacesList::preListChanged(), and PlacesList::updateModel().
Field Documentation
list
PlacesList* PlacesModel::list private
Definition at line 51 of file placesmodel.h.
Property Documentation
list
PlacesList PlacesModel::list read write
Definition at line 30 of file placesmodel.h.
Referenced by data(), getList(), rowCount(), and setList().
The documentation for this class was generated from the following files:
fm/placesmodel.h
fm/placesmodel.cpp