MauiKit: TAGDB Class Reference
TAGDB Class Reference
#include <tagdb.h>
Public Member Functions
Q_INVOKABLE bool checkExistance (const QString &tableName, const QString &searchId, const QString &search)
Q_INVOKABLE bool checkExistance (const QString &queryStr)
Protected Member Functions
TAGDB (QObject *parent=nullptr)
~ TAGDB ()
QSqlQuery getQuery (const QString &queryTxt)
void openDB (const QString &name)
void prepareCollectionDB () const
bool insert (const QString &tableName, const QVariantMap &insertData)
bool update (const QString &tableName, const TAG::DB &updateData, const QVariantMap &where)
bool update (const QString &table, const QString &column, const QVariant &newValue, const QVariant &op, const QString &id)
bool remove (const QString &tableName, const TAG::DB &removeData)
Private Attributes
QString name
QSqlDatabase m_db
Detailed Description
Definition at line 41 of file tagdb.h.
Constructor & Destructor Documentation
TAGDB()
TAGDB::TAGDB (QObject * parent = nullptr) protected
Definition at line 23 of file tagdb.cpp.
                             : QObject(parent)
 {
     QDir collectionDBPath_dir(TAG::TaggingPath);
     if (!collectionDBPath_dir.exists())
         collectionDBPath_dir.mkpath(".");
     this->name = QUuid::createUuid().toString();
     if(!UTIL::fileExists(TAG::TaggingPath + TAG::DBName))
     {
         this->openDB(this->name);
         qDebug()<<"Collection doesn't exists, trying to create it" << TAG::TaggingPath + TAG::DBName;
         this->prepareCollectionDB();
     }else this->openDB(this->name);
 }
References TAG::DBName, UTIL::fileExists(), name, openDB(), prepareCollectionDB(), and TAG::TaggingPath.
~ TAGDB()
TAGDB::~ TAGDB () protected
Member Function Documentation
checkExistance() [1/2]
bool TAGDB::checkExistance (const QString & tableName, const QString & searchId, const QString & search)
Definition at line 118 of file tagdb.cpp.
 {
     auto queryStr = QString("SELECT %1 FROM %2 WHERE %3 = \"%4\"").arg(searchId, tableName, searchId, search);
     auto query = this->getQuery(queryStr);
     if (query.exec())
     {
         if (query.next()) return true;
     }else qDebug()<<query.lastError().text();
     return false;
 }
References getQuery().
Referenced by Tagging::tagExists().
checkExistance() [2/2]
bool TAGDB::checkExistance (const QString & queryStr)
Definition at line 131 of file tagdb.cpp.
 {
     auto query = this->getQuery(queryStr);
     if (query.exec())
     {
         if (query.next()) return true;
     }else qDebug()<<query.lastError().text();
     return false;
 }
References getQuery().
getQuery()
QSqlQuery TAGDB::getQuery (const QString & queryTxt) protected
Definition at line 143 of file tagdb.cpp.
 {
     QSqlQuery query(queryTxt, this->m_db);
     return query;
 }
References m_db.
Referenced by checkExistance(), Tagging::get(), openDB(), remove(), and update().
insert()
bool TAGDB::insert (const QString & tableName, const QVariantMap & insertData) protected
Definition at line 149 of file tagdb.cpp.
 {
     if (tableName.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The table name is empty!");
         return false;
     } else if (insertData.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The insertData is empty!");
         return false;
     }
     QStringList strValues;
     QStringList fields = insertData.keys();
     QVariantList values = insertData.values();
     int totalFields = fields.size();
     for (int i = 0; i < totalFields; ++i)
         strValues.append("?");
     QString sqlQueryString = "INSERT INTO " + tableName + " (" + QString(fields.join(",")) + ") VALUES(" + QString(strValues.join(",")) + ")";
     QSqlQuery query(this->m_db);
     query.prepare(sqlQueryString);
     int k = 0;
     foreach (const QVariant &value, values)
         query.bindValue(k++, value);
     return query.exec();
 }
References m_db.
Referenced by Tagging::abstract(), Tagging::app(), Tagging::tag(), Tagging::tagAbstract(), Tagging::tagUrl(), and Tagging::user().
openDB()
void TAGDB::openDB (const QString & name) protected
Definition at line 43 of file tagdb.cpp.
 {
     if(!QSqlDatabase::contains(name))
     {
         this->m_db = QSqlDatabase::addDatabase(QStringLiteral("QSQLITE"), name);
         this->m_db.setDatabaseName(TAG::TaggingPath + TAG::DBName);
     }
     if (!this->m_db.isOpen())
     {
         if(!this->m_db.open())
             qDebug()<<"ERROR OPENING DB"<<this->m_db.lastError().text()<<m_db.connectionName();
     }
     auto query = this->getQuery("PRAGMA synchronous=OFF");
     query.exec();
 }
References TAG::DBName, getQuery(), m_db, name, and TAG::TaggingPath.
Referenced by TAGDB().
prepareCollectionDB()
void TAGDB::prepareCollectionDB () const protected
Definition at line 60 of file tagdb.cpp.
 {
     QSqlQuery query(this->m_db);
     QFile file(":/script.sql");
     if (!file.exists())
     {
         QString log = QStringLiteral("Fatal error on build database. The file '");
         log.append(file.fileName() + QStringLiteral("' for database and tables creation query cannot be not found!"));
         qDebug()<<log;
         return;
     }
     if (!file.open(QIODevice::ReadOnly))
     {
         qDebug()<<QStringLiteral("Fatal error on try to create database! The file with sql queries for database creation cannot be opened!");
         return;
     }
     bool hasText;
     QString line;
     QByteArray readLine;
     QString cleanedLine;
     QStringList strings;
     while (!file.atEnd())
     {
         hasText     = false;
         line        = "";
         readLine    = "";
         cleanedLine = "";
         strings.clear();
         while (!hasText)
         {
             readLine    = file.readLine();
             cleanedLine = readLine.trimmed();
             strings     = cleanedLine.split("--");
             cleanedLine = strings.at(0);
             if (!cleanedLine.startsWith("--") && !cleanedLine.startsWith("DROP") && !cleanedLine.isEmpty())
                 line += cleanedLine;
             if (cleanedLine.endsWith(";"))
                 break;
             if (cleanedLine.startsWith("COMMIT"))
                 hasText = true;
         }
         if (!line.isEmpty())
         {
             if (!query.exec(line))
             {
                 qDebug()<<"exec failed"<<query.lastQuery()<<query.lastError();
             }
         } else qDebug()<<"exec wrong"<<query.lastError();
     }
     file.close();
 }
References m_db.
Referenced by TAGDB().
remove()
bool TAGDB::remove (const QString & tableName, const TAG::DB & removeData) protected
Definition at line 213 of file tagdb.cpp.
 {
     if (tableName.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on removing! The table name is empty!");
         return false;
     } else if (removeData.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The removeData is empty!");
         return false;
     }
     QString strValues;
         auto i = 0;
     for (auto key : removeData.keys())
     {
         strValues.append(QString("%1 = \"%2\"").arg(TAG::KEYMAP[key], removeData[key]));
         i++;
         if(removeData.keys().size() > 1 && i<removeData.keys().size())
             strValues.append(" AND ");
     }
     QString sqlQueryString = "DELETE FROM " + tableName + " WHERE " + strValues;
     qDebug()<< sqlQueryString;
     return this->getQuery(sqlQueryString).exec();
 }
References getQuery(), and TAG::KEYMAP.
Referenced by Tagging::removeAbstractTag(), and Tagging::removeUrlTag().
update() [1/2]
bool TAGDB::update (const QString & tableName, const TAG::DB & updateData, const QVariantMap & where) protected
Definition at line 180 of file tagdb.cpp.
 {
     if (tableName.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The table name is empty!");
         return false;
     } else if (updateData.isEmpty())
     {
         qDebug()<<QStringLiteral("Fatal error on insert! The insertData is empty!");
         return false;
     }
     QStringList set;
     for (auto key : updateData.keys())
         set.append(TAG::KEYMAP[key]+" = '"+updateData[key]+"'");
     QStringList condition;
     for (auto key : where.keys())
         condition.append(key+" = '"+where[key].toString()+"'");
     QString sqlQueryString = "UPDATE " + tableName + " SET " + QString(set.join(",")) + " WHERE " + QString(condition.join(",")) ;
     auto query = this->getQuery(sqlQueryString);
     qDebug()<<sqlQueryString;
     return query.exec();
 }
References getQuery(), and TAG::KEYMAP.
update() [2/2]
bool TAGDB::update (const QString & table, const QString & column, const QVariant & newValue, const QVariant & op, const QString & id) protected
Definition at line 206 of file tagdb.cpp.
 {
     auto queryStr = QString("UPDATE %1 SET %2 = \"%3\" WHERE %4 = \"%5\"").arg(table, column, newValue.toString().replace("\"","\"\""), op.toString(), id);
     auto query = this->getQuery(queryStr);
     return query.exec();
 }
References getQuery().
Field Documentation
m_db
QSqlDatabase TAGDB::m_db private
Definition at line 46 of file tagdb.h.
Referenced by getQuery(), insert(), openDB(), and prepareCollectionDB().
name
QString TAGDB::name private
Definition at line 45 of file tagdb.h.
Referenced by openDB(), and TAGDB().
The documentation for this class was generated from the following files:
utils/tagging/tagdb.h
utils/tagging/tagdb.cpp