MauiKit: FMModel Class Reference
FMModel Class Reference
#include <fmmodel.h>
Signals
void listChanged ()
Public Member Functions
FMModel (QObject *parent=nullptr)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
virtual QHash< int, QByteArray > roleNames () const override
FMList * getList () const
void setList (FMList *value)
Properties
FMList list
Private Attributes
FMList * fmlist
Detailed Description
Definition at line 28 of file fmmodel.h.
Constructor & Destructor Documentation
FMModel()
FMModel::FMModel (QObject * parent = nullptr) explicit
Definition at line 4 of file fmmodel.cpp.
 : QAbstractListModel(parent), fmlist(nullptr)
 {}
Member Function Documentation
data()
QVariant FMModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 16 of file fmmodel.cpp.
 {
     if (!index.isValid() || !fmlist)
         return QVariant();
     return fmlist->items().at(index.row())[static_cast<FMH::MODEL_KEY>(role)];
 }
References fmlist, and FMList::items().
flags()
Qt::ItemFlags FMModel::flags (const QModelIndex & index) const override
Definition at line 34 of file fmmodel.cpp.
 {
     if (!index.isValid())
         return Qt::NoItemFlags;
     return Qt::ItemIsEditable; // FIXME: Implement me!
 }
getList()
FMList * FMModel::getList () const
Definition at line 52 of file fmmodel.cpp.
 {
     return this->fmlist;
 }
References fmlist.
listChanged
void FMModel::listChanged () signal
roleNames()
QHash< int, QByteArray > FMModel::roleNames () const override virtual
Definition at line 42 of file fmmodel.cpp.
 {
     QHash<int, QByteArray> names;
     for(auto key : FMH::MODEL_NAME.keys())
         names[key] = QString(FMH::MODEL_NAME[key]).toUtf8();
     return names;
 }
References FMH::MODEL_NAME.
rowCount()
int FMModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 8 of file fmmodel.cpp.
 {
     if (parent.isValid() || !fmlist)
         return 0;
     return fmlist->items().size();
 }
References fmlist, and FMList::items().
setData()
bool FMModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 25 of file fmmodel.cpp.
 {
     Q_UNUSED(index);
     Q_UNUSED(value);
     Q_UNUSED(role);
     return false;
 }
setList()
void FMModel::setList (FMList * value)
Definition at line 57 of file fmmodel.cpp.
 {
     beginResetModel();
     if(fmlist)
         fmlist->disconnect(this);
     fmlist = value;
     if(fmlist)
     {
         connect(this->fmlist, &FMList::preItemAppended, this, [=]()
         {
             const int index = fmlist->items().size();
             qDebug()<< "Inserting new item";
             beginInsertRows(QModelIndex(), index, index);
         });
         connect(this->fmlist, &FMList::postItemAppended, this, [=]()
         {
             endInsertRows();
         });
         connect(this->fmlist, &FMList::preItemRemoved, this, [=](int index)
         {
             beginRemoveRows(QModelIndex(), index, index);
         });
         connect(this->fmlist, &FMList::postItemRemoved, this, [=]()
         {
             endRemoveRows();
         });
         connect(this->fmlist, &FMList::updateModel, this, [=](int index, QVector<int> roles)
         {
             emit this->dataChanged(this->index(index), this->index(index), roles);
         });
 //      connect(this->fmlist, &FMList::pathChanged, this, [=]()
 //      {
 //          beginResetModel();
 //          endResetModel();
 //      });
         connect(this->fmlist, &FMList::preListChanged, this, [=]()
         {
             beginResetModel();
         });
         connect(this->fmlist, &FMList::postListChanged, this, [=]()
         {
             endResetModel();
         });
     }
     endResetModel();
 }
References fmlist, FMList::items(), FMList::postItemAppended(), FMList::postItemRemoved(), FMList::postListChanged(), FMList::preItemAppended(), FMList::preItemRemoved(), FMList::preListChanged(), and FMList::updateModel().
Field Documentation
fmlist
FMList* FMModel::fmlist private
Definition at line 52 of file fmmodel.h.
Referenced by data(), getList(), rowCount(), and setList().
Property Documentation
list
FMList FMModel::list read write
Definition at line 31 of file fmmodel.h.
The documentation for this class was generated from the following files:
fm/fmmodel.h
fm/fmmodel.cpp