MauiKit: NetworkHelper Class Reference
NetworkHelper Class Reference
#include <NetworkHelper.hpp>
Public Member Functions
NetworkHelper (QString host, QString username, QString password)
QNetworkReply * makeRequest (QString method, QString path, QMap< QString, QString > headers)
QNetworkReply * makePutRequest (QString path, QMap< QString, QString > headers, QIODevice *file)
Private Member Functions
void setRequestAuthHeader (QNetworkRequest *request)
void setRequestHeaders (QNetworkRequest *request, QMap< QString, QString > headers)
Private Attributes
QString host
QString username
QString password
QNetworkAccessManager * networkManager
Detailed Description
Definition at line 11 of file NetworkHelper.hpp.
Constructor & Destructor Documentation
NetworkHelper()
NetworkHelper::NetworkHelper (QString host, QString username, QString password)
Definition at line 9 of file NetworkHelper.cpp.
{
   this->host = host;
   this->username = username;
   this->password = password;
   this->networkManager = new QNetworkAccessManager(this);
 }
References host, networkManager, password, and username.
Member Function Documentation
makePutRequest()
QNetworkReply * NetworkHelper::makePutRequest (QString path, QMap< QString, QString > headers, QIODevice * file)
Definition at line 30 of file NetworkHelper.cpp.
{
   QNetworkRequest request(QUrl(this->host + "/" + path));
   this->setRequestAuthHeader(&request);
   this->setRequestHeaders(&request, headers);
   QNetworkReply* reply = this->networkManager->put(request, file);
   return reply;
 }
References host, networkManager, setRequestAuthHeader(), and setRequestHeaders().
Referenced by WebDAVClient::uploadTo().
makeRequest()
QNetworkReply * NetworkHelper::makeRequest (QString method, QString path, QMap< QString, QString > headers)
Definition at line 17 of file NetworkHelper.cpp.
{
   QNetworkRequest request(QUrl(this->host + "/" + path));
   this->setRequestAuthHeader(&request);
   this->setRequestHeaders(&request, headers);
   QNetworkReply* reply = this->networkManager->sendCustomRequest(
       request, QByteArray::fromStdString(method.toStdString()));
   return reply;
 }
References host, networkManager, setRequestAuthHeader(), and setRequestHeaders().
Referenced by WebDAVClient::copy(), WebDAVClient::createDir(), WebDAVClient::downloadFrom(), WebDAVClient::listDir(), WebDAVClient::move(), and WebDAVClient::remove().
setRequestAuthHeader()
void NetworkHelper::setRequestAuthHeader (QNetworkRequest * request) private
Definition at line 43 of file NetworkHelper.cpp.
{
   QString authData = this->username + ":" + this->password;
   QByteArray data = authData.toLocal8Bit().toBase64();
   QString headerData = "Basic " + data;
   request->setRawHeader("Authorization", headerData.toLocal8Bit());
 }
References password, and username.
Referenced by makePutRequest(), and makeRequest().
setRequestHeaders()
void NetworkHelper::setRequestHeaders (QNetworkRequest * request, QMap< QString, QString > headers) private
Definition at line 51 of file NetworkHelper.cpp.
{
   QMapIterator<QString, QString> headersIterator(headers);
   while (headersIterator.hasNext()) {
     headersIterator.next();
     request->setRawHeader(
         QByteArray::fromStdString(headersIterator.key().toStdString()),
         QByteArray::fromStdString(headersIterator.value().toStdString()));
   }
 }
Referenced by makePutRequest(), and makeRequest().
Field Documentation
host
QString NetworkHelper::host private
Definition at line 15 of file NetworkHelper.hpp.
Referenced by makePutRequest(), makeRequest(), and NetworkHelper().
networkManager
QNetworkAccessManager* NetworkHelper::networkManager private
Definition at line 18 of file NetworkHelper.hpp.
Referenced by makePutRequest(), makeRequest(), and NetworkHelper().
password
QString NetworkHelper::password private
Definition at line 17 of file NetworkHelper.hpp.
Referenced by NetworkHelper(), and setRequestAuthHeader().
username
QString NetworkHelper::username private
Definition at line 16 of file NetworkHelper.hpp.
Referenced by NetworkHelper(), and setRequestAuthHeader().
The documentation for this class was generated from the following files:
utils/syncing/libwebdavclient/lib/utils/NetworkHelper.hpp
utils/syncing/libwebdavclient/lib/utils/NetworkHelper.cpp