MauiKit: Store Class Reference
Store Class Reference
#include <store.h>
Public Slots
void providersChanged ()
void categoryListResult (Attica::BaseJob *j)
void projectListResult (Attica::BaseJob *j)
void contentListResult (Attica::BaseJob *j)
void contentDownloadReady (Attica::BaseJob *j)
void getPersonInfo (const QString &nick)
void perfomSearch ()
Signals
void storeReady ()
void contentReady (FMH::MODEL_LIST list)
void downloadReady (FMH::MODEL item)
void warning (QString warning)
void categoryIDsReady ()
Public Member Functions
Store (QObject *parent=nullptr)
~Store ()
void start ()
void setProvider (const STORE::PROVIDER &provider)
void setCategory (const STORE::CATEGORY_KEY &categoryKey)
void searchFor (const STORE::CATEGORY_KEY &categoryKey, const QString &query=QString(), const int &limit=10, const int &page=1, const Attica::Provider::SortMode &sortBy=Attica::Provider::SortMode::Rating)
void listProjects ()
void listCategories ()
void download (const QString &id)
void download (const FMH::MODEL &item)
QHash< QString, QString > getCategoryIDs ()
Private Member Functions
void downloadLink (const QString &url, const QString &fileName)
Private Attributes
Attica::ProviderManager m_manager
Attica::Provider m_provider
QHash< QString, QString > categoryID
STORE::CATEGORY_KEY m_category = STORE::CATEGORY_KEY::NONE
STORE::PROVIDER provider = STORE::KDELOOK_API
QString query
int limit = 10
int page = 0
Attica::Provider::SortMode sortBy = Attica::Provider::SortMode::Rating
Detailed Description
Definition at line 199 of file store.h.
Constructor & Destructor Documentation
Store()
Store::Store (QObject * parent = nullptr)
Definition at line 24 of file store.cpp.
                             : QObject(parent)
 {
 }
~Store()
Store::~Store ()
Definition at line 29 of file store.cpp.
 {
 }
Member Function Documentation
categoryIDsReady
void Store::categoryIDsReady () signal
Referenced by categoryListResult(), and searchFor().
categoryListResult
void Store::categoryListResult (Attica::BaseJob * j) slot
Definition at line 188 of file store.cpp.
 {
     qDebug() << "Category list job returned";
     if (j->metadata().error() == Attica::Metadata::NoError)
     {
         Attica::ListJob<Attica::Category> *listJob = static_cast<Attica::ListJob<Attica::Category> *>(j);
         qDebug() << "Yay, no errors ...";
         QStringList projectIds;
         foreach (const Attica::Category &p, listJob->itemList())
         {
             if(STORE::CATEGORIES[this->m_category].contains(p.name()))
                 this->categoryID[p.name()] = p.id();
             projectIds << p.id();
             qDebug()<< p.name() << p.id();
         }
         if (listJob->itemList().isEmpty())
         {
             emit this->warning(QLatin1String("No Categories found."));
         }
     } else if (j->metadata().error() == Attica::Metadata::OcsError)
     {
         emit this->warning(QString(QLatin1String("OCS Error: %1")).arg(j->metadata().message()));
     } else if (j->metadata().error() == Attica::Metadata::NetworkError)
     {
         emit this->warning(QString(QLatin1String("Network Error: %1")).arg(j->metadata().message()));
     } else
     {
         emit this->warning(QString(QLatin1String("Unknown Error: %1")).arg(j->metadata().message()));
     }
     qDebug()<< "CATEGORY IDS " << this->categoryID;
     emit this->categoryIDsReady();
 }
References STORE::CATEGORIES, categoryID, categoryIDsReady(), m_category, and warning().
Referenced by listCategories().
contentDownloadReady
void Store::contentDownloadReady (Attica::BaseJob * j) slot
Definition at line 278 of file store.cpp.
 {
     if (j->metadata().error() == Attica::Metadata::NoError)
     {
         Attica::ItemJob<Attica::DownloadItem> *res = static_cast<Attica::ItemJob<Attica::DownloadItem> *>(j);
         auto job  = res->result();
         auto url = job.url().toString();
         auto fileName = job.packageName();
         this->downloadLink(url, fileName);
     } else if (j->metadata().error() == Attica::Metadata::OcsError)
     {
         emit this->warning(QString(QLatin1String("OCS Error: %1")).arg(j->metadata().message()));
     } else if (j->metadata().error() == Attica::Metadata::NetworkError)
     {
         emit this->warning(QString(QLatin1String("Network Error: %1")).arg(j->metadata().message()));
     } else
     {
         emit this->warning(QString(QLatin1String("Unknown Error: %1")).arg(j->metadata().message()));
     }
 }
References downloadLink(), and warning().
Referenced by download().
contentListResult
void Store::contentListResult (Attica::BaseJob * j) slot
Definition at line 108 of file store.cpp.
 {
     qDebug() << "Content list job returned";
     FMH::MODEL_LIST list;
     if (j->metadata().error() == Attica::Metadata::NoError)
     {
         Attica::ListJob<Attica::Content> *listJob = static_cast<Attica::ListJob<Attica::Content> *>(j);
         foreach (const Attica::Content &p, listJob->itemList())
         {
             const auto att = p.attributes();
             list << FMH::MODEL {
                 {FMH::MODEL_KEY::ID, p.id()},
                 {FMH::MODEL_KEY::URL, att[STORE::ATTRIBUTE[STORE::ATTRIBUTE_KEY::DOWNLOAD_LINK]]},
                 {FMH::MODEL_KEY::THUMBNAIL, att[STORE::ATTRIBUTE[STORE::ATTRIBUTE_KEY::PREVIEW_SMALL_1]]},
                 {FMH::MODEL_KEY::THUMBNAIL_1, att[STORE::ATTRIBUTE[STORE::ATTRIBUTE_KEY::PREVIEW_1]]},
                 {FMH::MODEL_KEY::THUMBNAIL_2, att[STORE::ATTRIBUTE[STORE::ATTRIBUTE_KEY::PREVIEW_2]]},
                 {FMH::MODEL_KEY::THUMBNAIL_3, att[STORE::ATTRIBUTE[STORE::ATTRIBUTE_KEY::DOWNLOAD_LINK]]},
                 {FMH::MODEL_KEY::LABEL, p.name()},
                 {FMH::MODEL_KEY::OWNER, p.author()},
                 {FMH::MODEL_KEY::LICENSE, p.license()},
                 {FMH::MODEL_KEY::DESCRIPTION, p.description()},
                 {FMH::MODEL_KEY::RATE, QString::number(p.rating())},
                 {FMH::MODEL_KEY::DATE, p.created().toString()},
                 {FMH::MODEL_KEY::MODIFIED, p.updated().toString()},
                 {FMH::MODEL_KEY::TAG, p.tags().join(",")},
                 {FMH::MODEL_KEY::COUNT, QString::number(p.downloads())},
                 {FMH::MODEL_KEY::SOURCE, p.detailpage().toString()}
             };
         }
         emit this->contentReady(list);
         if (listJob->itemList().isEmpty())
         {
             emit this->warning(QLatin1String("No Content found."));
         }
     } else if (j->metadata().error() == Attica::Metadata::OcsError)
     {
         emit this->warning(QString(QLatin1String("OCS Error: %1")).arg(j->metadata().message()));
     } else if (j->metadata().error() == Attica::Metadata::NetworkError)
     {
         emit this->warning(QString(QLatin1String("Network Error: %1")).arg(j->metadata().message()));
     } else
     {
         emit this->warning(QString(QLatin1String("Unknown Error: %1")).arg(j->metadata().message()));
     }
 }
References STORE::ATTRIBUTE, contentReady(), FMH::COUNT, FMH::DATE, FMH::DESCRIPTION, STORE::DOWNLOAD_LINK, FMH::ID, FMH::LABEL, FMH::LICENSE, FMH::MODIFIED, FMH::OWNER, STORE::PREVIEW_1, STORE::PREVIEW_2, STORE::PREVIEW_SMALL_1, FMH::RATE, FMH::SOURCE, FMH::TAG, FMH::THUMBNAIL, FMH::THUMBNAIL_1, FMH::THUMBNAIL_2, FMH::THUMBNAIL_3, FMH::URL, and warning().
Referenced by perfomSearch().
contentReady
void Store::contentReady (FMH::MODEL_LIST list) signal
Referenced by contentListResult(), and StoreList::StoreList().
download() [1/2]
void Store::download (const QString & id)
Definition at line 266 of file store.cpp.
 {
     Attica::ItemJob<Attica::DownloadItem> *job = m_provider.downloadLink(id);
     connect(job, SIGNAL(finished(Attica::BaseJob*)), SLOT(contentDownloadReady(Attica::BaseJob*)));
     job->start();
 }
References contentDownloadReady(), and m_provider.
Referenced by StoreList::download().
download() [2/2]
void Store::download (const FMH::MODEL & item)
Definition at line 273 of file store.cpp.
 {
     this->downloadLink(item[FMH::MODEL_KEY::URL], item[FMH::MODEL_KEY::LABEL]);
 }
References downloadLink(), FMH::LABEL, and FMH::URL.
downloadLink()
void Store::downloadLink (const QString & url, const QString & fileName) private
Definition at line 302 of file store.cpp.
 {
         const auto downloader = new FMH::Downloader;
 //      QString _fileName = fileName;
         qDebug()<< "DOWNLOADING CONTENT FROM "<< url << fileName;
             QStringList filePathList = url.split('/');
             auto _fileName = filePathList.at(filePathList.count() - 1);
         connect(downloader, &FMH::Downloader::warning, [this](const QString &warning)
         {
             emit this->warning(warning);
         });
         connect(downloader, &FMH::Downloader::fileSaved, [this](const QString &fileName)
         {
             emit this->downloadReady(FMH::getFileInfoModel(fileName));
         });
 //      connect(downloader, &FMH::Downloader::downloadReady, [this]()
 //      {
 //
 //      });
 //
         downloader->setFile(url, FMH::DownloadsPath  + "/" + _fileName);
 }
References downloadReady(), FMH::DownloadsPath, FMH::Downloader::fileSaved(), FMH::getFileInfoModel(), FMH::Downloader::setFile(), warning(), and FMH::Downloader::warning().
Referenced by contentDownloadReady(), and download().
downloadReady
void Store::downloadReady (FMH::MODEL item) signal
Referenced by downloadLink(), and StoreList::StoreList().
getCategoryIDs()
QHash< QString, QString > Store::getCategoryIDs ()
Definition at line 367 of file store.cpp.
 {
     return this->categoryID;
 }
References categoryID.
getPersonInfo
void Store::getPersonInfo (const QString & nick) slot
Definition at line 228 of file store.cpp.
 {
     Attica::ItemJob<Attica::Person>* job = m_provider.requestPerson(nick);
     // connect that job
     connect(job, &Attica::BaseJob::finished, [](Attica::BaseJob* doneJob)
     {
         Attica::ItemJob<Attica::Person> *personJob = static_cast< Attica::ItemJob<Attica::Person> * >( doneJob );
         // check if the request actually worked
         if( personJob->metadata().error() == Attica::Metadata::NoError )
         {
             // use the data to fill the labels
             Attica::Person p(personJob->result());
             qDebug() << (p.firstName() + ' ' + p.lastName());
             qDebug() << p.city();
         } else
         {
             qDebug() << ("Could not fetch information.");
         }
     });
     // start the job
     job->start();
 }
References m_provider.
Referenced by StoreList::getPersonInfo().
listCategories()
void Store::listCategories ()
Definition at line 259 of file store.cpp.
 {
     Attica::ListJob<Attica::Category> *job = m_provider.requestCategories();
     connect(job, SIGNAL(finished(Attica::BaseJob*)), SLOT(categoryListResult(Attica::BaseJob*)));
     job->start();
 }
References categoryListResult(), and m_provider.
Referenced by setCategory().
listProjects()
void Store::listProjects ()
Definition at line 252 of file store.cpp.
 {
     Attica::ListJob<Attica::Project> *job = m_provider.requestProjects();
     connect(job, SIGNAL(finished(Attica::BaseJob*)), SLOT(projectListResult(Attica::BaseJob*)));
     job->start();
 }
References m_provider, and projectListResult().
perfomSearch
void Store::perfomSearch () slot
Definition at line 86 of file store.cpp.
 {
     Attica::Category::List categories;
     qDebug()<< "GOT THE CATEGORY IDS" << this->categoryID;
     for(auto key : this->categoryID.keys())
     {
         Attica::Category category;
         category.setId(this->categoryID[key]);
         category.setName(key);
         category.setDisplayName(key);
         categories << category;
         qDebug()<< category.name() << this->categoryID[key];
     }
     Attica::ListJob<Attica::Content> *job = this->m_provider.searchContents(categories, this->query, this->sortBy, this->page, this->limit);
     connect(job, SIGNAL(finished(Attica::BaseJob*)), SLOT(contentListResult(Attica::BaseJob*)));
     job->start();
 }
References categoryID, contentListResult(), limit, m_provider, page, query, and sortBy.
Referenced by searchFor().
projectListResult
void Store::projectListResult (Attica::BaseJob * j) slot
Definition at line 332 of file store.cpp.
 {
     qDebug() << "Project list job returned";
     QString output = QLatin1String("<b>Projects:</b>");
     if (j->metadata().error() == Attica::Metadata::NoError)
     {
         Attica::ListJob<Attica::Project> *listJob = static_cast<Attica::ListJob<Attica::Project> *>(j);
         qDebug() << "Yay, no errors ...";
         QStringList projectIds;
         foreach (const Attica::Project &p, listJob->itemList())
         {
             qDebug() << "New project:" << p.id() << p.name();
             output.append(QString(QLatin1String("<br />%1 (%2)")).arg(p.name(), p.id()));
             projectIds << p.id();
             // TODO: start project jobs here
         }
         if (listJob->itemList().isEmpty())
         {
             output.append(QLatin1String("No Projects found."));
         }
     } else if (j->metadata().error() == Attica::Metadata::OcsError)
     {
         output.append(QString(QLatin1String("OCS Error: %1")).arg(j->metadata().message()));
     } else if (j->metadata().error() == Attica::Metadata::NetworkError)
     {
         output.append(QString(QLatin1String("Network Error: %1")).arg(j->metadata().message()));
     } else
     {
         output.append(QString(QLatin1String("Unknown Error: %1")).arg(j->metadata().message()));
     }
     qDebug() << output;
 }
Referenced by listProjects().
providersChanged
void Store::providersChanged () slot
Definition at line 161 of file store.cpp.
 {
     if (!m_manager.providers().isEmpty())
     {
         qDebug()<< "Providers names:";
         for(auto prov : m_manager.providers())
             qDebug() << prov.name() << prov.baseUrl();
         m_provider = m_manager.providerByUrl(QUrl(this->provider));
         //      m_provider = m_manager.providerByUrl(QUrl(STORE::OPENDESKTOP_API));
         if (!m_provider.isValid())
         {
             qDebug() << "Could not find "<< this->provider << "provider.";
             return;
         }else
         {
             qDebug()<< "Found the Store provider for" << m_provider.name();
             qDebug()<< "Has content service" << m_provider.hasContentService();
             emit this->storeReady();
         }
     }else qDebug() << "Could not find any provider.";
 }
References m_manager, m_provider, provider, and storeReady().
Referenced by start().
searchFor()
void Store::searchFor (const STORE::CATEGORY_KEY & categoryKey, const QString & query = QString(), const int & limit = 10, const int & page = 1, const Attica::Provider::SortMode & sortBy = Attica::Provider::SortMode::Rating)
Definition at line 67 of file store.cpp.
 {
     this->query = query;
     this->limit = limit;
     this->page = page;
     this->sortBy = sortBy;
     qDebug() << "CATEGORY LIST" << STORE::CATEGORIES[this->m_category];
     //  if(this->m_category == categoryKey)
     //  {
     //      qDebug()<< "SEARCHIGN WITHIN SAME CATEGORY" << this->m_category;
     //      this->perfomSearch();
     //      return;
     //  }
     //
     connect(this, &Store::categoryIDsReady, this, &Store::perfomSearch);
     this->setCategory(categoryKey);
 }
References STORE::CATEGORIES, categoryIDsReady(), limit, m_category, page, perfomSearch(), query, setCategory(), and sortBy.
Referenced by StoreList::setList().
setCategory()
void Store::setCategory (const STORE::CATEGORY_KEY & categoryKey)
Definition at line 60 of file store.cpp.
 {
     qDebug()<< "SETTING CATEGORY OFR STORE";
     this->m_category = categoryKey;
     this->listCategories();
 }
References listCategories(), and m_category.
Referenced by searchFor().
setProvider()
void Store::setProvider (const STORE::PROVIDER & provider)
Definition at line 55 of file store.cpp.
 {
     this->provider = provider;
 }
References provider.
Referenced by StoreList::setProvider(), and StoreList::StoreList().
start()
void Store::start ()
Definition at line 33 of file store.cpp.
 {
     qDebug()<< "Setting up Store backend";
     if(!FMH::fileExists(FMH::DataPath+"/Store/providers.xml"))
     {
         QDir store_dir(FMH::DataPath+"/Store/");
         if (!store_dir.exists())
             store_dir.mkpath(".");
         QFile providersFile(":/store/providers.xml");
         providersFile.copy(FMH::DataPath+"/Store/providers.xml");
     }
     connect(&m_manager, SIGNAL(defaultProvidersLoaded()), SLOT(providersChanged()));
     //  qDebug()<< "provider local file exists?"<< FMH::fileExists(FMH::DataPath+"/Store/providers.xml");
     m_manager.addProviderFile(QUrl::fromLocalFile(FMH::DataPath+"/Store/providers.xml"));
     m_manager.addProviderFile(QUrl("https://autoconfig.kde.org/ocs/providers.xml"));
     m_manager.addProviderFile(QUrl("https://share.krita.org/ocs/providers.xml"));
     //      m_manager.loadDefaultProviders();
 }
References FMH::DataPath, FMH::fileExists(), m_manager, and providersChanged().
Referenced by StoreList::StoreList().
storeReady
void Store::storeReady () signal
Referenced by providersChanged(), and StoreList::StoreList().
warning
void Store::warning (QString warning) signal
Referenced by categoryListResult(), contentDownloadReady(), contentListResult(), downloadLink(), and StoreList::StoreList().
Field Documentation
categoryID
QHash<QString, QString> Store::categoryID private
Definition at line 235 of file store.h.
Referenced by categoryListResult(), getCategoryIDs(), and perfomSearch().
limit
int Store::limit = 10 private
Definition at line 241 of file store.h.
Referenced by perfomSearch(), and searchFor().
m_category
STORE::CATEGORY_KEY Store::m_category = STORE::CATEGORY_KEY::NONE private
Definition at line 236 of file store.h.
Referenced by categoryListResult(), searchFor(), and setCategory().
m_manager
Attica::ProviderManager Store::m_manager private
Definition at line 233 of file store.h.
Referenced by providersChanged(), and start().
m_provider
Attica::Provider Store::m_provider private
Definition at line 234 of file store.h.
Referenced by download(), getPersonInfo(), listCategories(), listProjects(), perfomSearch(), and providersChanged().
page
int Store::page = 0 private
Definition at line 242 of file store.h.
Referenced by perfomSearch(), and searchFor().
provider
STORE::PROVIDER Store::provider = STORE::KDELOOK_API private
Definition at line 238 of file store.h.
Referenced by providersChanged(), and setProvider().
query
QString Store::query private
Definition at line 240 of file store.h.
Referenced by perfomSearch(), and searchFor().
sortBy
Attica::Provider::SortMode Store::sortBy = Attica::Provider::SortMode::Rating private
Definition at line 244 of file store.h.
Referenced by perfomSearch(), and searchFor().
The documentation for this class was generated from the following files:
utils/store/store.h
utils/store/store.cpp