MauiKit: StoreModel Class Reference
StoreModel Class Reference
#include <storemodel.h>
Signals
void listChanged ()
Public Member Functions
StoreModel (QObject *parent=nullptr)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
virtual QHash< int, QByteArray > roleNames () const override
StoreList * getList () const
void setList (StoreList *value)
Properties
StoreList list
Private Attributes
StoreList * mList
Detailed Description
Definition at line 27 of file storemodel.h.
Constructor & Destructor Documentation
StoreModel()
StoreModel::StoreModel (QObject * parent = nullptr) explicit
Definition at line 23 of file storemodel.cpp.
 : QAbstractListModel(parent),
 mList(nullptr)
 {}
Member Function Documentation
data()
QVariant StoreModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 36 of file storemodel.cpp.
 {
     if (!index.isValid() || !mList)
         return QVariant();
     return mList->items().at(index.row())[static_cast<FMH::MODEL_KEY>(role)];
 }
References StoreList::items(), and mList.
flags()
Qt::ItemFlags StoreModel::flags (const QModelIndex & index) const override
Definition at line 50 of file storemodel.cpp.
 {
     if (!index.isValid())
         return Qt::NoItemFlags;
     return Qt::ItemIsEditable; // FIXME: Implement me!
 }
getList()
StoreList * StoreModel::getList () const
Definition at line 68 of file storemodel.cpp.
 {
     return this->mList;
 }
References mList.
listChanged
void StoreModel::listChanged () signal
roleNames()
QHash< int, QByteArray > StoreModel::roleNames () const override virtual
Definition at line 58 of file storemodel.cpp.
 {
     QHash<int, QByteArray> names;
     for(auto key : FMH::MODEL_NAME.keys())
         names[key] = QString(FMH::MODEL_NAME[key]).toUtf8();
     return names;
 }
References FMH::MODEL_NAME.
rowCount()
int StoreModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 28 of file storemodel.cpp.
 {
     if (parent.isValid() || !mList)
         return 0;
     return mList->items().size();
 }
References StoreList::items(), and mList.
setData()
bool StoreModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 44 of file storemodel.cpp.
 {
     return false;
 }
setList()
void StoreModel::setList (StoreList * value)
Definition at line 73 of file storemodel.cpp.
 {
     beginResetModel();
     if(mList)
         mList->disconnect(this);
     mList = value;
     if(mList)
     {
         connect(this->mList, &StoreList::preItemAppended, this, [=]()
         {
             const int index = mList->items().size();
             beginInsertRows(QModelIndex(), index, index);
         });
         connect(this->mList, &StoreList::postItemAppended, this, [=]()
         {
             endInsertRows();
         });
         connect(this->mList, &StoreList::preItemRemoved, this, [=](int index)
         {
             beginRemoveRows(QModelIndex(), index, index);
         });
         connect(this->mList, &StoreList::postItemRemoved, this, [=]()
         {
             endRemoveRows();
         });
         connect(this->mList, &StoreList::updateModel, this, [=](int index, QVector<int> roles)
         {
             emit this->dataChanged(this->index(index), this->index(index), roles);
         });
         connect(this->mList, &StoreList::preListChanged, this, [=]()
         {
             beginResetModel();
         });
         connect(this->mList, &StoreList::postListChanged, this, [=]()
         {
             endResetModel();
         });
     }
     endResetModel();
 }
References StoreList::items(), mList, StoreList::postItemAppended(), StoreList::postItemRemoved(), StoreList::postListChanged(), StoreList::preItemAppended(), StoreList::preItemRemoved(), StoreList::preListChanged(), and StoreList::updateModel().
Field Documentation
mList
StoreList* StoreModel::mList private
Definition at line 51 of file storemodel.h.
Referenced by data(), getList(), rowCount(), and setList().
Property Documentation
list
StoreList StoreModel::list read write
Definition at line 30 of file storemodel.h.
The documentation for this class was generated from the following files:
utils/store/storemodel.h
utils/store/storemodel.cpp