MauiKit: TagsList Class Reference
TagsList Class Reference
#include <tagslist.h>
Public Types
enum KEYS : uint_fast8_t {
URL = TAG::URL, APP = TAG::APP, URI = TAG::URI, MAC = TAG::MAC,
LAST_SYNC = TAG::LAST_SYNC, NAME = TAG::NAME, VERSION = TAG::VERSION, LOT = TAG::LOT,
TAG = TAG::TAG, COLOR = TAG::COLOR, ADD_DATE = TAG::ADD_DATE, COMMENT = TAG::COMMENT,
MIME = TAG::MIME, TITLE = TAG::TITLE, DEVICE = TAG::DEVICE, KEY = TAG::KEY
}
Public Slots
QVariantMap get (const int &index) const
void append (const QString &tag)
bool insert (const QString &tag)
void insertToUrls (const QString &tag)
void insertToAbstract (const QString &tag)
void updateToUrls (const QStringList &tags)
void updateToAbstract (const QStringList &tags)
bool remove (const int &index)
void removeFrom (const int &index, const QString &url)
void removeFrom (const int &index, const QString &key, const QString &lot)
void removeFromUrls (const int &index)
void removeFromAbstract (const int &index)
void erase (const int &index)
void refresh ()
Signals
void preItemAppended ()
void postItemAppended ()
void preItemRemoved (int index)
void postItemRemoved ()
void updateModel (int index, QVector< int > roles)
void preListChanged ()
void postListChanged ()
void abstractChanged ()
void strictChanged ()
void urlsChanged ()
void lotChanged ()
void keyChanged ()
void sortByChanged ()
Public Member Functions
Q_ENUM (TagsList::KEYS) explicit TagsList(QObject *parent
TAG::DB_LIST items () const
TAG::KEYS getSortBy () const
void setSortBy (const TAG::KEYS &key)
bool getAbstract () const
void setAbstract (const bool &value)
bool getStrict () const
void setStrict (const bool &value)
QStringList getUrls () const
void setUrls (const QStringList &value)
QString getLot () const
void setLot (const QString &value)
QString getKey () const
void setKey (const QString &value)
Properties
bool abstract
bool strict = true
QStringList urls = QStringList()
QString lot
QString key
TAG::KEYS sortBy = TAG::KEYS::ADD_DATE
Private Member Functions
void setList ()
void sortList ()
TAG::DB_LIST toModel (const QVariantList &data)
Private Attributes
TAG::DB_LIST list
Tagging * tag
abstract bool = false
Detailed Description
Definition at line 9 of file tagslist.h.
Member Enumeration Documentation
KEYS
enum TagsList::KEYS : uint_fast8_t
Enumerator
URL
APP
URI
MAC
LAST_SYNC
NAME
VERSION
LOT
TAG
COLOR
ADD_DATE
COMMENT
MIME
TITLE
DEVICE
KEY
Definition at line 22 of file tagslist.h.
               : uint_fast8_t
     {
         URL = TAG::URL,
         APP = TAG::APP,
         URI = TAG::URI,
         MAC = TAG::MAC,
         LAST_SYNC = TAG::LAST_SYNC,
         NAME = TAG::NAME,
         VERSION = TAG::VERSION,
         LOT = TAG::LOT,
         TAG = TAG::TAG,
         COLOR = TAG::COLOR,
         ADD_DATE = TAG::ADD_DATE,
         COMMENT = TAG::COMMENT,
         MIME = TAG::MIME,
         TITLE = TAG::TITLE,
         DEVICE = TAG::DEVICE,
         KEY = TAG::KEY
     }; Q_ENUM(TagsList::KEYS)
Member Function Documentation
abstractChanged
void TagsList::abstractChanged () signal
Referenced by setAbstract().
append
void TagsList::append (const QString & tag) slot
Definition at line 354 of file tagslist.cpp.
 {
     if(!this->insert(tag))
     {
         emit this->preItemAppended();
         this->list << TAG::DB {{TAG::KEYS::TAG, tag}};
         this->sortList();
         emit this->postItemAppended();
     }
 }
References insert(), list, postItemAppended(), preItemAppended(), sortList(), tag, and FMH::TAG.
erase
void TagsList::erase (const int & index) slot
Definition at line 246 of file tagslist.cpp.
 {
 }
get
QVariantMap TagsList::get (const int & index) const slot
Definition at line 95 of file tagslist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return QVariantMap();
     const auto folder = this->list.at(index);
     QVariantMap res;
     for(auto key : folder.keys())
         res.insert(TAG::KEYMAP[key], folder[key]);
     return res;
 }
References key, TAG::KEYMAP, and list.
getAbstract()
bool TagsList::getAbstract () const
Definition at line 274 of file tagslist.cpp.
 {
     return this->abstract;
 }
getKey()
QString TagsList::getKey () const
Definition at line 304 of file tagslist.cpp.
 {
     return this->key;
 }
References key.
getLot()
QString TagsList::getLot () const
Definition at line 320 of file tagslist.cpp.
 {
     return this->lot;
 }
References lot.
getSortBy()
TAG::KEYS TagsList::getSortBy () const
Definition at line 255 of file tagslist.cpp.
 {
     return this->sortBy;
 }
References sortBy.
getStrict()
bool TagsList::getStrict () const
Definition at line 289 of file tagslist.cpp.
 {
     return this->strict;
 }
References strict.
getUrls()
QStringList TagsList::getUrls () const
Definition at line 336 of file tagslist.cpp.
 {
     return this->urls;
 }
References urls.
insert
bool TagsList::insert (const QString & tag) slot
Definition at line 114 of file tagslist.cpp.
 {
     auto _tag = tag.trimmed();
     if(this->tag->tag(_tag))
     {
         emit this->preItemAppended();
         this->list << TAG::DB {{TAG::KEYS::TAG, _tag}};
 //      this->sortList();
         emit this->postItemAppended();
         return true;
     }
     return false;
 }
References list, postItemAppended(), preItemAppended(), tag, and FMH::TAG.
Referenced by append().
insertToAbstract
void TagsList::insertToAbstract (const QString & tag) slot
Definition at line 143 of file tagslist.cpp.
 {
     if(this->key.isEmpty() || this->lot.isEmpty())
         return;
     if(this->tag->tagAbstract(tag, this->key, this->lot))
         this->refresh();
 }
References key, lot, refresh(), and tag.
insertToUrls
void TagsList::insertToUrls (const QString & tag) slot
Definition at line 130 of file tagslist.cpp.
 {
     if(this->urls.isEmpty())
         return;
     for(auto url : this->urls)
     {
         this->tag->tagUrl(url, tag);
     }
     this->refresh();
 }
References refresh(), tag, and urls.
items()
TAG::DB_LIST TagsList::items () const
Definition at line 250 of file tagslist.cpp.
 {
     return this->list;
 }
References list.
Referenced by TagsModel::data(), TagsModel::rowCount(), and TagsModel::setList().
keyChanged
void TagsList::keyChanged () signal
Referenced by setKey().
lotChanged
void TagsList::lotChanged () signal
Referenced by setLot().
postItemAppended
void TagsList::postItemAppended () signal
Referenced by append(), insert(), and TagsModel::setList().
postItemRemoved
void TagsList::postItemRemoved () signal
Referenced by remove(), removeFrom(), removeFromAbstract(), removeFromUrls(), and TagsModel::setList().
postListChanged
void TagsList::postListChanged () signal
Referenced by TagsModel::setList(), setList(), and setSortBy().
preItemAppended
void TagsList::preItemAppended () signal
Referenced by append(), insert(), and TagsModel::setList().
preItemRemoved
void TagsList::preItemRemoved (int index) signal
Referenced by remove(), removeFrom(), removeFromAbstract(), removeFromUrls(), and TagsModel::setList().
preListChanged
void TagsList::preListChanged () signal
Referenced by TagsModel::setList(), setList(), and setSortBy().
Q_ENUM()
TagsList::Q_ENUM (TagsList::KEYS)
refresh
void TagsList::refresh () slot
Definition at line 109 of file tagslist.cpp.
 {
     this->setList();
 }
References setList().
Referenced by insertToAbstract(), insertToUrls(), updateToAbstract(), and updateToUrls().
remove
bool TagsList::remove (const int & index) slot
Definition at line 208 of file tagslist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return false;
     emit this->preItemRemoved(index);
     this->list.removeAt(index);
     emit this->postItemRemoved();
     return true;
 }
References list, postItemRemoved(), and preItemRemoved().
removeFrom [1/2]
void TagsList::removeFrom (const int & index, const QString & url) slot
Definition at line 233 of file tagslist.cpp.
 {
     if(index >= this->list.size() || index < 0)
             return;
     if(this->tag->removeUrlTag(url, this->list[index][TAG::KEYS::TAG]))
     {
         emit this->preItemRemoved(index);
         this->list.removeAt(index);
         emit this->postItemRemoved();
     }
 }
References list, postItemRemoved(), preItemRemoved(), Tagging::removeUrlTag(), tag, and FMH::TAG.
removeFrom [2/2]
void TagsList::removeFrom (const int & index, const QString & key, const QString & lot) slot
Definition at line 220 of file tagslist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return;
     if(this->tag->removeAbstractTag(key, lot, this->list[index][TAG::KEYS::TAG]))
     {
         emit this->preItemRemoved(index);
         this->list.removeAt(index);
         emit this->postItemRemoved();
     }
 }
References list, lot, postItemRemoved(), preItemRemoved(), Tagging::removeAbstractTag(), tag, and FMH::TAG.
removeFromAbstract
void TagsList::removeFromAbstract (const int & index) slot
Definition at line 173 of file tagslist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return;
     if(this->key.isEmpty() || this->lot.isEmpty())
         return;
     const auto tag =  this->list[index][TAG::KEYS::TAG];
     if(this->tag->removeAbstractTag(this->key, this->lot, tag))
     {
         emit this->preItemRemoved(index);
         this->list.removeAt(index);
         emit this->postItemRemoved();
     }
 }
References key, list, lot, postItemRemoved(), preItemRemoved(), Tagging::removeAbstractTag(), tag, and FMH::TAG.
removeFromUrls
void TagsList::removeFromUrls (const int & index) slot
Definition at line 190 of file tagslist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return;
     if(this->urls.isEmpty())
         return;
     const auto tag =  this->list[index][TAG::KEYS::TAG];
     for(auto url : this->urls)
         this->tag->removeUrlTag(url, tag);
     emit this->preItemRemoved(index);
     this->list.removeAt(index);
     emit this->postItemRemoved();
 }
References list, postItemRemoved(), preItemRemoved(), Tagging::removeUrlTag(), tag, FMH::TAG, and urls.
setAbstract()
void TagsList::setAbstract (const bool & value)
Definition at line 279 of file tagslist.cpp.
 {
     if(this->abstract == value)
         return;
     this->abstract = value;
     this->setList();
     emit this->abstractChanged();
 }
References abstractChanged(), and setList().
setKey()
void TagsList::setKey (const QString & value)
Definition at line 309 of file tagslist.cpp.
 {
     if(this->key == value)
         return;
     this->urls.clear();
     this->key = value;
     this->setList();
     emit this->keyChanged();
 }
References key, keyChanged(), setList(), and urls.
setList()
void TagsList::setList () private
Definition at line 26 of file tagslist.cpp.
 {
     emit this->preListChanged();
     if(this->abstract)
     {
         if(this->lot.isEmpty() || this->key.isEmpty())
             this->list = this->toModel(this->tag->getAbstractsTags(this->strict));
         else
             this->list = this->toModel(this->tag->getAbstractTags(this->key, this->lot, this->strict));
     }else
     {
         if(this->urls.isEmpty())
             this->list = this->toModel(this->tag->getAllTags(this->strict));
         else
         {
             this->list.clear();
             for(auto url : this->urls)
                 this->list << this->toModel(this->tag->getUrlTags(url, this->strict));
         }
     }
     this->sortList();
     emit this->postListChanged();
 }
References Tagging::getAbstractsTags(), Tagging::getAbstractTags(), Tagging::getAllTags(), Tagging::getUrlTags(), key, list, lot, postListChanged(), preListChanged(), sortList(), tag, toModel(), and urls.
Referenced by refresh(), setAbstract(), setKey(), setLot(), setStrict(), and setUrls().
setLot()
void TagsList::setLot (const QString & value)
Definition at line 325 of file tagslist.cpp.
 {
     if(this->lot == value)
         return;
     this->urls.clear();
     this->lot = value;
     this->setList();
     emit this->lotChanged();
 }
References lot, lotChanged(), setList(), and urls.
setSortBy()
void TagsList::setSortBy (const TAG::KEYS & key)
Definition at line 260 of file tagslist.cpp.
 {
     if(this->sortBy == key)
         return;
     this->sortBy = key;
     emit this->preListChanged();
     this->sortList();
     emit this->sortByChanged();
     emit this->postListChanged();
 }
References key, postListChanged(), preListChanged(), sortBy, sortByChanged(), and sortList().
setStrict()
void TagsList::setStrict (const bool & value)
Definition at line 294 of file tagslist.cpp.
 {
     if(this->strict == value)
         return;
     this->strict = value;
     this->setList();
     emit this->strictChanged();
 }
References setList(), strict, and strictChanged().
setUrls()
void TagsList::setUrls (const QStringList & value)
Definition at line 341 of file tagslist.cpp.
 {
     if(this->urls == value)
         return;
     this->key.clear();
     this->lot.clear();
     this->urls = value;
     this->setList();
     emit this->urlsChanged();
 }
References key, lot, setList(), urls, and urlsChanged().
sortByChanged
void TagsList::sortByChanged () signal
Referenced by setSortBy().
sortList()
void TagsList::sortList () private
Definition at line 54 of file tagslist.cpp.
 {
     const auto key = this->sortBy;
     qSort(this->list.begin(), this->list.end(), [key](const TAG::DB & e1, const TAG::DB & e2) -> bool
     {
         auto role = key;
         switch(role)
         {
             case TAG::KEYS::ADD_DATE:
             {
                 auto currentTime = QDateTime::currentDateTime();
                 auto date1 = QDateTime::fromString(e1[role], Qt::TextDate);
                 auto date2 = QDateTime::fromString(e2[role], Qt::TextDate);
                 if(date1.secsTo(currentTime) <  date2.secsTo(currentTime))
                     return true;
                 break;
             }
             case TAG::KEYS::TAG:
             {
                 const auto str1 = QString(e1[role]).toLower();
                 const auto str2 = QString(e2[role]).toLower();
                 if(str1 < str2)
                     return true;
                 break;
             }
             default:
                 if(e1[role] < e2[role])
                     return true;
         }
         return false;
     });
 }
References TAG::ADD_DATE, key, list, sortBy, and FMH::TAG.
Referenced by append(), setList(), and setSortBy().
strictChanged
void TagsList::strictChanged () signal
Referenced by setStrict().
toModel()
TAG::DB_LIST TagsList::toModel (const QVariantList & data) private
Definition at line 10 of file tagslist.cpp.
 {
     TAG::DB_LIST res;
     for(auto item : data)
     {
         const auto map = item.toMap();
         TAG::DB model;
         for(auto key : map.keys())
             model.insert(TAG::MAPKEY[key], map[key].toString());
         res << model;
     }
     return res;
 }
References key, and TAG::MAPKEY.
Referenced by setList().
updateModel
void TagsList::updateModel (int index, QVector< int > roles) signal
Referenced by TagsModel::setList().
updateToAbstract
void TagsList::updateToAbstract (const QStringList & tags) slot
Definition at line 163 of file tagslist.cpp.
 {
     if(this->key.isEmpty() || this->lot.isEmpty())
         return;
     this->tag->updateAbstractTags(this->key, this->lot, tags);
     this->refresh();
 }
References key, lot, refresh(), tag, and Tagging::updateAbstractTags().
updateToUrls
void TagsList::updateToUrls (const QStringList & tags) slot
Definition at line 152 of file tagslist.cpp.
 {
     if(this->urls.isEmpty())
         return;
     for(auto url : this->urls)
         this->tag->updateUrlTags(url, tags);
     this->refresh();
 }
References refresh(), tag, Tagging::updateUrlTags(), and urls.
urlsChanged
void TagsList::urlsChanged () signal
Referenced by setUrls().
Field Documentation
bool
abstract TagsList::bool = false private
Definition at line 72 of file tagslist.h.
list
TAG::DB_LIST TagsList::list private
Definition at line 65 of file tagslist.h.
Referenced by append(), get(), insert(), items(), remove(), removeFrom(), removeFromAbstract(), removeFromUrls(), setList(), and sortList().
tag
Tagging* TagsList::tag private
Definition at line 68 of file tagslist.h.
Referenced by append(), insert(), insertToAbstract(), insertToUrls(), removeFrom(), removeFromAbstract(), removeFromUrls(), setList(), updateToAbstract(), and updateToUrls().
Property Documentation
abstract
bool TagsList::abstract read write
Definition at line 12 of file tagslist.h.
key
QString TagsList::key read write
Definition at line 16 of file tagslist.h.
Referenced by get(), getKey(), insertToAbstract(), removeFromAbstract(), setKey(), setList(), setSortBy(), setUrls(), sortList(), toModel(), and updateToAbstract().
lot
QString TagsList::lot read write
Definition at line 15 of file tagslist.h.
Referenced by getLot(), insertToAbstract(), removeFrom(), removeFromAbstract(), setList(), setLot(), setUrls(), and updateToAbstract().
sortBy
TAG::KEYS TagsList::sortBy = TAG::KEYS::ADD_DATE read write
Definition at line 18 of file tagslist.h.
Referenced by getSortBy(), setSortBy(), and sortList().
strict
bool TagsList::strict = true read write
Definition at line 13 of file tagslist.h.
Referenced by getStrict(), and setStrict().
urls
QStringList TagsList::urls = QStringList() read write
Definition at line 14 of file tagslist.h.
Referenced by getUrls(), insertToUrls(), removeFromUrls(), setKey(), setList(), setLot(), setUrls(), and updateToUrls().
The documentation for this class was generated from the following files:
utils/tagging/tagslist.h
utils/tagging/tagslist.cpp