MauiKit: PlacesList Class Reference
PlacesList Class Reference
#include <placeslist.h>
Public Slots
QVariantMap get (const int &index) const
void refresh ()
void clearBadgeCount (const int &index)
Signals
void groupsChanged ()
void preItemAppended ()
void postItemAppended ()
void preItemRemoved (int index)
void postItemRemoved ()
void updateModel (int index, QVector< int > roles)
void preListChanged ()
void postListChanged ()
Public Member Functions
PlacesList (QObject *parent=nullptr)
~PlacesList ()
FMH::MODEL_LIST items () const
QList< int > getGroups () const
void setGroups (const QList< int > &value)
Protected Member Functions
void setList ()
void reset ()
Properties
QList< int > groups
Private Member Functions
void watchPath (const QString &path)
void setCount ()
int indexOf (const QString &path)
Private Attributes
FM * fm
FMH::MODEL_LIST list
QHash< QString, int > count
QFileSystemWatcher * watcher
Detailed Description
Definition at line 27 of file placeslist.h.
Constructor & Destructor Documentation
PlacesList()
PlacesList::PlacesList (QObject * parent = nullptr)
Definition at line 26 of file placeslist.cpp.
                                       : QObject(parent)
 {
     this->fm = new FM(this);
     this->watcher = new QFileSystemWatcher(this);
     connect(watcher, &QFileSystemWatcher::directoryChanged, [this](const QString &path)
     {
         if(this->count.contains(path))
         {
             //          QEventLoop loop;
             //          QTimer timer;
             //          connect(&timer, &QTimer::timeout, &loop, &QEventLoop::quit);
             //
             //          timer.setSingleShot(true);
             //          timer.setInterval(1000);
             auto oldCount =  this->count[path];
             const auto index = this->indexOf(path);
             //          timer.start();
             //          loop.exec();
             //          timer.stop();
             auto newCount = FM::getPathContent(path, true, false).size();
             auto count = newCount - oldCount;
             this->list[index][FMH::MODEL_KEY::COUNT] = QString::number(count);
             emit this->updateModel(index, {FMH::MODEL_KEY::COUNT});
         }
     });
     connect(fm, &FM::bookmarkInserted, this, &PlacesList::reset);
     connect(fm, &FM::bookmarkRemoved, this, &PlacesList::reset);
     connect(fm, &FM::cloudAccountInserted, this, &PlacesList::reset);
     connect(fm, &FM::cloudAccountRemoved, this, &PlacesList::reset);
     connect(this, &PlacesList::groupsChanged, this, &PlacesList::reset);
     this->setList();
 }
References FM::bookmarkInserted(), FM::bookmarkRemoved(), FM::cloudAccountInserted(), FM::cloudAccountRemoved(), count, FMH::COUNT, fm, FM::getPathContent(), groupsChanged(), indexOf(), list, reset(), setList(), updateModel(), and watcher.
~PlacesList()
PlacesList::~PlacesList ()
Definition at line 77 of file placeslist.cpp.
 {
 }
Member Function Documentation
clearBadgeCount
void PlacesList::clearBadgeCount (const int & index) slot
Definition at line 191 of file placeslist.cpp.
 {
     this->list[index][FMH::MODEL_KEY::COUNT] = "0";
     emit this->updateModel(index, {FMH::MODEL_KEY::COUNT});
 }
References FMH::COUNT, list, and updateModel().
get
QVariantMap PlacesList::get (const int & index) const slot
Definition at line 172 of file placeslist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return QVariantMap();
     QVariantMap res;
     const auto model = this->list.at(index);
     for(auto key : model.keys())
         res.insert(FMH::MODEL_NAME[key], model[key]);
     return res;
 }
References list, and FMH::MODEL_NAME.
getGroups()
QList< int > PlacesList::getGroups () const
Definition at line 157 of file placeslist.cpp.
 {
     return this->groups;
 }
References groups.
groupsChanged
void PlacesList::groupsChanged () signal
Referenced by PlacesList(), and setGroups().
indexOf()
int PlacesList::indexOf (const QString & path) private
Definition at line 137 of file placeslist.cpp.
 {
     int i = -1;
     for(auto data : this->list)
     {
         i++;
         if(data[FMH::MODEL_KEY::PATH] == path)
             break;
     }
     return i;
 }
References list, and FMH::PATH.
Referenced by PlacesList().
items()
FMH::MODEL_LIST PlacesList::items () const
Definition at line 81 of file placeslist.cpp.
 {
     return this->list;
 }
References list.
Referenced by PlacesModel::data(), PlacesModel::rowCount(), and PlacesModel::setList().
postItemAppended
void PlacesList::postItemAppended () signal
Referenced by PlacesModel::setList().
postItemRemoved
void PlacesList::postItemRemoved () signal
Referenced by PlacesModel::setList().
postListChanged
void PlacesList::postListChanged () signal
Referenced by reset(), and PlacesModel::setList().
preItemAppended
void PlacesList::preItemAppended () signal
Referenced by PlacesModel::setList().
preItemRemoved
void PlacesList::preItemRemoved (int index) signal
Referenced by PlacesModel::setList().
preListChanged
void PlacesList::preListChanged () signal
Referenced by reset(), and PlacesModel::setList().
refresh
void PlacesList::refresh () slot
Definition at line 186 of file placeslist.cpp.
 {
     this->reset();
 }
References reset().
reset()
void PlacesList::reset () protected
Definition at line 150 of file placeslist.cpp.
 {
     emit this->preListChanged();
     this->setList();
     emit this->postListChanged();
 }
References postListChanged(), preListChanged(), and setList().
Referenced by PlacesList(), and refresh().
setCount()
void PlacesList::setCount () private
Definition at line 121 of file placeslist.cpp.
 {
     this->watcher->removePaths(this->watcher->directories());
     for(auto &data : this->list)
     {
         auto path = data[FMH::MODEL_KEY::PATH];
         if(FM::isDir(path))
         {
             auto count = FM::getPathContent(path, true, false).size();
             data.insert(FMH::MODEL_KEY::COUNT, "0");
             this->count.insert(path, count);
             this->watchPath(path);
         }
     }
 }
References count, FMH::COUNT, FM::getPathContent(), FM::isDir(), list, FMH::PATH, watcher, and watchPath().
Referenced by setList().
setGroups()
void PlacesList::setGroups (const QList< int > & value)
Definition at line 162 of file placeslist.cpp.
 {
     if(this->groups == value)
         return;
     this->groups = value;
     emit this->groupsChanged();
 }
References groups, and groupsChanged().
setList()
void PlacesList::setList () protected
Definition at line 86 of file placeslist.cpp.
 {
     this->list.clear();
     for(auto group : this->groups)
         switch(group)
         {
         case FMH::PATHTYPE_KEY::PLACES_PATH:
             this->list << FM::getDefaultPaths();
             break;
         case FMH::PATHTYPE_KEY::APPS_PATH:
             this->list << FM::getCustomPaths();
             break;
         case FMH::PATHTYPE_KEY::BOOKMARKS_PATH:
             this->list << this->fm->getBookmarks();
             break;
         case FMH::PATHTYPE_KEY::DRIVES_PATH:
             this->list << FM::getDevices();
             break;
         case FMH::PATHTYPE_KEY::TAGS_PATH:
             this->list << this->fm->getTags();
             break;
         case FMH::PATHTYPE_KEY::CLOUD_PATH:
             this->list << this->fm->getCloudAccounts();
             break;
         }
     this->setCount();
 }
References FMH::APPS_PATH, FMH::BOOKMARKS_PATH, FMH::CLOUD_PATH, FMH::DRIVES_PATH, fm, FM::getBookmarks(), FM::getCloudAccounts(), FM::getCustomPaths(), FM::getDefaultPaths(), FM::getDevices(), FM::getTags(), groups, list, FMH::PLACES_PATH, setCount(), and FMH::TAGS_PATH.
Referenced by PlacesList(), and reset().
updateModel
void PlacesList::updateModel (int index, QVector< int > roles) signal
Referenced by clearBadgeCount(), PlacesList(), and PlacesModel::setList().
watchPath()
void PlacesList::watchPath (const QString & path) private
Definition at line 69 of file placeslist.cpp.
 {
     if(path.isEmpty() || !FMH::fileExists(path))
         return;
     this->watcher->addPath(path);
 }
References FMH::fileExists(), and watcher.
Referenced by setCount().
Field Documentation
count
QHash<QString, int> PlacesList::count private
Definition at line 53 of file placeslist.h.
Referenced by PlacesList(), and setCount().
fm
FM* PlacesList::fm private
Definition at line 51 of file placeslist.h.
Referenced by PlacesList(), and setList().
list
FMH::MODEL_LIST PlacesList::list private
Definition at line 52 of file placeslist.h.
Referenced by clearBadgeCount(), get(), indexOf(), items(), PlacesList(), setCount(), and setList().
watcher
QFileSystemWatcher* PlacesList::watcher private
Definition at line 56 of file placeslist.h.
Referenced by PlacesList(), setCount(), and watchPath().
Property Documentation
groups
QList< int > PlacesList::groups read write
Definition at line 30 of file placeslist.h.
Referenced by getGroups(), setGroups(), and setList().
The documentation for this class was generated from the following files:
fm/placeslist.h
fm/placeslist.cpp