MauiKit: MauiKit Class Reference
MauiKit Class Reference
#include <mauikit.h>
Public Member Functions
void registerTypes (const char *uri) Q_DECL_OVERRIDE
Static Public Member Functions
static MauiKit & getInstance ()
static void registerTypes ()
Private Member Functions
QUrl componentUrl (const QString &fileName) const
QString resolveFilePath (const QString &path) const
QString resolveFileUrl (const QString &filePath) const
Detailed Description
Definition at line 28 of file mauikit.h.
Member Function Documentation
componentUrl()
QUrl MauiKit::componentUrl (const QString & fileName) const private
Definition at line 54 of file mauikit.cpp.
 {
 #ifdef MAUI_APP
     return QUrl(QStringLiteral("qrc:/maui/kit/") + fileName);
 #else
     return QUrl(resolveFileUrl(fileName));
 #endif
 }
References resolveFileUrl().
Referenced by registerTypes().
getInstance()
static MauiKit& MauiKit::getInstance () inline static
Definition at line 39 of file mauikit.h.
     {
         static MauiKit instance;
         return instance;
     }
registerTypes() [1/2]
void MauiKit::registerTypes (const char * uri)
STORE CONTROLS
BROWSING CONTROLS
FM CONTROLS
EDITOR CONTROLS
Definition at line 63 of file mauikit.cpp.
 {
     Q_ASSERT(uri == QLatin1String("org.kde.mauikit"));
     qmlRegisterSingletonType(componentUrl(QStringLiteral("Style.qml")), uri, 1, 0, "Style");
     qmlRegisterType(componentUrl(QStringLiteral("ToolBar.qml")), uri, 1, 0, "ToolBar");
     qmlRegisterType(componentUrl(QStringLiteral("ToolButton.qml")), uri, 1, 0, "ToolButton");
     qmlRegisterType(componentUrl(QStringLiteral("ApplicationWindow.qml")), uri, 1, 0, "ApplicationWindow");
     qmlRegisterType(componentUrl(QStringLiteral("Page.qml")), uri, 1, 0, "Page");
     qmlRegisterType(componentUrl(QStringLiteral("ShareDialog.qml")), uri, 1, 0, "ShareDialog");
     qmlRegisterType(componentUrl(QStringLiteral("PieButton.qml")), uri, 1, 0, "PieButton");
     qmlRegisterType(componentUrl(QStringLiteral("SideBar.qml")), uri, 1, 0, "SideBar");
     qmlRegisterType(componentUrl(QStringLiteral("Holder.qml")), uri, 1, 0, "Holder");
     qmlRegisterType(componentUrl(QStringLiteral("Drawer.qml")), uri, 1, 0, "Drawer");
     qmlRegisterType(componentUrl(QStringLiteral("GlobalDrawer.qml")), uri, 1, 0, "GlobalDrawer");
     qmlRegisterType(componentUrl(QStringLiteral("ListDelegate.qml")), uri, 1, 0, "ListDelegate");
     qmlRegisterType(componentUrl(QStringLiteral("SelectionBar.qml")), uri, 1, 0, "SelectionBar");
     qmlRegisterType(componentUrl(QStringLiteral("IconDelegate.qml")), uri, 1, 0, "IconDelegate");
     qmlRegisterType(componentUrl(QStringLiteral("LabelDelegate.qml")), uri, 1, 0, "LabelDelegate");
     qmlRegisterType(componentUrl(QStringLiteral("NewDialog.qml")), uri, 1, 0, "NewDialog");
     qmlRegisterType(componentUrl(QStringLiteral("Dialog.qml")), uri, 1, 0, "Dialog");
     qmlRegisterType(componentUrl(QStringLiteral("Button.qml")), uri, 1, 0, "Button");
     qmlRegisterType(componentUrl(QStringLiteral("AboutDialog.qml")), uri, 1, 0, "AboutDialog");
     qmlRegisterType(componentUrl(QStringLiteral("Popup.qml")), uri, 1, 0, "Popup");
     qmlRegisterType(componentUrl(QStringLiteral("TextField.qml")), uri, 1, 0, "TextField");
     qmlRegisterType(componentUrl(QStringLiteral("SearchBar.qml")), uri, 1, 0, "SearchBar");
     qmlRegisterType(componentUrl(QStringLiteral("TagsBar.qml")), uri, 1, 0, "TagsBar");
     qmlRegisterType(componentUrl(QStringLiteral("TagsDialog.qml")), uri, 1, 0, "TagsDialog");
     qmlRegisterType(componentUrl(QStringLiteral("Badge.qml")), uri, 1, 0, "Badge");
     qmlRegisterType(componentUrl(QStringLiteral("GridView.qml")), uri, 1, 0, "GridView");
     qmlRegisterType(componentUrl(QStringLiteral("Item.qml")), uri, 1, 0, "Item");
     qmlRegisterType(componentUrl(QStringLiteral("Menu.qml")), uri, 1, 0, "Menu");
     qmlRegisterType(componentUrl(QStringLiteral("MenuItem.qml")), uri, 1, 0, "MenuItem");
     qmlRegisterType(componentUrl(QStringLiteral("ColorsBar.qml")), uri, 1, 0, "ColorsBar");
     qmlRegisterType(componentUrl(QStringLiteral("ComboBox.qml")), uri, 1, 0, "ComboBox");
     qmlRegisterType(componentUrl(QStringLiteral("ImageViewer.qml")), uri, 1, 0, "ImageViewer");
     qmlRegisterType(componentUrl(QStringLiteral("private/TagList.qml")), uri, 1, 0, "TagList");
     qmlRegisterType(componentUrl(QStringLiteral("private/StoreDelegate.qml")), uri, 1, 0, "StoreDelegate");
     qmlRegisterType(componentUrl(QStringLiteral("Store.qml")), uri, 1, 0, "Store");
     qmlRegisterType(componentUrl(QStringLiteral("ListBrowser.qml")), uri, 1, 0, "ListBrowser");
     qmlRegisterType(componentUrl(QStringLiteral("GridBrowser.qml")), uri, 1, 0, "GridBrowser");
     qmlRegisterType(componentUrl(QStringLiteral("FileBrowser.qml")), uri, 1, 0, "FileBrowser");
     qmlRegisterType(componentUrl(QStringLiteral("PlacesSidebar.qml")), uri, 1, 0, "PlacesSidebar");
     qmlRegisterType(componentUrl(QStringLiteral("FilePreviewer.qml")), uri, 1, 0, "FilePreviewer");
     qmlRegisterType(componentUrl(QStringLiteral("FileDialog.qml")), uri, 1, 0, "FileDialog");
     qmlRegisterType(componentUrl(QStringLiteral("PathBar.qml")), uri, 1, 0, "PathBar");
     qmlRegisterType(componentUrl(QStringLiteral("SyncDialog.qml")), uri, 1, 0, "SyncDialog");
         qmlRegisterType(componentUrl(QStringLiteral("SyncDialog.qml")), uri, 1, 0, "SyncDialog");
     qmlRegisterType(componentUrl(QStringLiteral("Editor.qml")), uri, 1, 0, "Editor");
 #ifdef Q_OS_ANDROID
     qmlRegisterSingletonType<MAUIAndroid>(uri, 1, 0, "Android",
                                           [](QQmlEngine*, QJSEngine*) -> QObject* {
         MAUIAndroid *android = new MAUIAndroid;
         return android;
     });
 #else
     qmlRegisterType(componentUrl(QStringLiteral("Terminal.qml")), uri, 1, 0, "Terminal");
     qmlRegisterSingletonType<MAUIKDE>(uri, 1, 0, "KDE",
                                       [](QQmlEngine*, QJSEngine*) -> QObject* {
         MAUIKDE *kde = new MAUIKDE;
         return kde;
     });
 #endif
     qmlRegisterType<PlacesList>("PlacesList", 1, 0, "PlacesList");
     qmlRegisterType<PlacesModel>("PlacesModel", 1, 0, "PlacesModel");
     qmlRegisterType<FMModel>("FMModel", 1, 0, "FMModel");
     qmlRegisterType<FMList>("FMList", 1, 0, "FMList");
     qmlRegisterType<SyncingList>("SyncingList", 1, 0, "SyncingList");
     qmlRegisterType<SyncingModel>("SyncingModel", 1, 0, "SyncingModel");
     qmlRegisterType<TagsList>("TagsList", 1, 0, "TagsList");
     qmlRegisterType<TagsModel>("TagsModel", 1, 0, "TagsModel");
     qmlRegisterType<StoreList>("StoreList", 1, 0, "StoreList");
     qmlRegisterType<StoreModel>("StoreModel", 1, 0, "StoreModel");
     qmlRegisterType<DocumentHandler>("DocumentHandler", 1, 0, "DocumentHandler");
     qmlRegisterSingletonType<FM>(uri, 1, 0, "FM",
                                       [](QQmlEngine*, QJSEngine*) -> QObject* {
         auto fm = new FM();
         return fm;
     });
      qmlRegisterSingletonType<Handy>(uri, 1, 0, "Handy",
                                       [](QQmlEngine*, QJSEngine*) -> QObject* {
        auto handy = new Handy;
         return handy;
     });
      #ifdef Q_OS_ANDROID
      QIcon::setThemeSearchPaths({":/icons/luv-icon-theme"});
      QIcon::setThemeName("Luv");
      QQuickStyle::setStyle(":/style");
 //   #else
 //   QQuickStyle::setStyle("maui-style");
      #endif
     qmlProtectModule(uri, 1);
 }
References componentUrl().
Referenced by registerTypes().
registerTypes() [2/2]
static void MauiKit::registerTypes () inline static
Definition at line 45 of file mauikit.h.
     {
         static MauiKit instance;
         instance.registerTypes("org.kde.mauikit");
     }
References registerTypes().
resolveFilePath()
QString MauiKit::resolveFilePath (const QString & path) const inline private
Definition at line 53 of file mauikit.h.
     {
 #ifdef STATIC_MAUIKIT
         return QStringLiteral(":/org/kde/mauikit/") + path;
 #else
         return baseUrl().toLocalFile() + QLatin1Char('/') + path;
 #endif
     }
resolveFileUrl()
QString MauiKit::resolveFileUrl (const QString & filePath) const inline private
Definition at line 62 of file mauikit.h.
     {
 #ifdef STATIC_MAUIKIT
         return filePath;
 #else
         return baseUrl().toString() + QLatin1Char('/') + filePath;
 #endif
     }
Referenced by componentUrl().
The documentation for this class was generated from the following files:
mauikit.h
mauikit.cpp