MauiKit: SyncingModel Class Reference
SyncingModel Class Reference
#include <syncingmodel.h>
Signals
void listChanged ()
Public Member Functions
SyncingModel (QObject *parent=nullptr)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
virtual QHash< int, QByteArray > roleNames () const override
SyncingList * getList () const
void setList (SyncingList *value)
Properties
SyncingList list
Private Attributes
SyncingList * mList
Detailed Description
Definition at line 8 of file syncingmodel.h.
Constructor & Destructor Documentation
SyncingModel()
SyncingModel::SyncingModel (QObject * parent = nullptr) explicit
Definition at line 6 of file syncingmodel.cpp.
     : QAbstractListModel(parent),
       mList(nullptr)
 {}
Member Function Documentation
data()
QVariant SyncingModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 19 of file syncingmodel.cpp.
 {
     if (!index.isValid() || !mList)
         return QVariant();
     return mList->items().at(index.row())[static_cast<FMH::MODEL_KEY>(role)];
 }
References SyncingList::items(), and mList.
flags()
Qt::ItemFlags SyncingModel::flags (const QModelIndex & index) const override
Definition at line 33 of file syncingmodel.cpp.
 {
     if (!index.isValid())
         return Qt::NoItemFlags;
     return Qt::ItemIsEditable; // FIXME: Implement me!
 }
getList()
SyncingList * SyncingModel::getList () const
Definition at line 51 of file syncingmodel.cpp.
 {
     return this->mList;
 }
References mList.
listChanged
void SyncingModel::listChanged () signal
roleNames()
QHash< int, QByteArray > SyncingModel::roleNames () const override virtual
Definition at line 41 of file syncingmodel.cpp.
 {
     QHash<int, QByteArray> names;
         for(auto key : FMH::MODEL_NAME.keys())
             names[key] = QString(FMH::MODEL_NAME[key]).toUtf8();
         return names;
 }
References FMH::MODEL_NAME.
rowCount()
int SyncingModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 11 of file syncingmodel.cpp.
 {
     if (parent.isValid() || !mList)
         return 0;
     return mList->items().size();
 }
References SyncingList::items(), and mList.
setData()
bool SyncingModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 27 of file syncingmodel.cpp.
 {
     return false;
 }
setList()
void SyncingModel::setList (SyncingList * value)
Definition at line 56 of file syncingmodel.cpp.
 {
     beginResetModel();
     if(mList)
         mList->disconnect(this);
     mList = value;
     if(mList)
     {
         connect(this->mList, &SyncingList::preItemAppended, this, [=]()
         {
             const int index = mList->items().size();
             beginInsertRows(QModelIndex(), index, index);
         });
         connect(this->mList, &SyncingList::postItemAppended, this, [=]()
         {
             endInsertRows();
         });
         connect(this->mList, &SyncingList::preItemRemoved, this, [=](int index)
         {
             beginRemoveRows(QModelIndex(), index, index);
         });
         connect(this->mList, &SyncingList::postItemRemoved, this, [=]()
         {
             endRemoveRows();
         });
         connect(this->mList, &SyncingList::updateModel, this, [=](int index, QVector<int> roles)
         {
             emit this->dataChanged(this->index(index), this->index(index), roles);
         });
         connect(this->mList, &SyncingList::preListChanged, this, [=]()
         {
             beginResetModel();
         });
         connect(this->mList, &SyncingList::postListChanged, this, [=]()
         {
             endResetModel();
         });
     }
     endResetModel();
 }
References SyncingList::items(), mList, SyncingList::postItemAppended(), SyncingList::postItemRemoved(), SyncingList::postListChanged(), SyncingList::preItemAppended(), SyncingList::preItemRemoved(), SyncingList::preListChanged(), and SyncingList::updateModel().
Field Documentation
mList
SyncingList* SyncingModel::mList private
Definition at line 32 of file syncingmodel.h.
Referenced by data(), getList(), rowCount(), and setList().
Property Documentation
list
SyncingList SyncingModel::list read write
Definition at line 11 of file syncingmodel.h.
The documentation for this class was generated from the following files:
utils/syncing/syncingmodel.h
utils/syncing/syncingmodel.cpp