MauiKit: Tagging Class Reference
Tagging Class Reference
#include <tagging.h>
Signals
void urlTagged (const QString &url, const QString &tag)
void abstractTagged (const QString &key, const QString &lot, const QString &tag)
void tagged (const QString &tag)
Public Member Functions
Q_INVOKABLE QVariantList get (const QString &query)
Q_INVOKABLE bool tagExists (const QString &tag, const bool &strict=false)
Q_INVOKABLE bool tag (const QString &tag, const QString &color=QString(), const QString &comment=QString())
Q_INVOKABLE bool tagUrl (const QString &url, const QString &tag, const QString &color=QString(), const QString &comment=QString())
Q_INVOKABLE bool tagAbstract (const QString &tag, const QString &key, const QString &lot, const QString &color=QString(), const QString &comment=QString())
Q_INVOKABLE bool updateUrlTags (const QString &url, const QStringList &tags)
Q_INVOKABLE bool updateAbstractTags (const QString &key, const QString &lot, const QStringList &tags)
Q_INVOKABLE QVariantList getUrlsTags (const bool &strict=true)
Q_INVOKABLE QVariantList getAbstractsTags (const bool &strict=true)
Q_INVOKABLE QVariantList getAllTags (const bool &strict=true)
Q_INVOKABLE QVariantList getUrls (const QString &tag, const bool &strict=true)
Q_INVOKABLE QVariantList getUrlTags (const QString &url, const bool &strict=true)
Q_INVOKABLE QVariantList getAbstractTags (const QString &key, const QString &lot, const bool &strict=true)
Q_INVOKABLE bool removeAbstractTag (const QString &key, const QString &lot, const QString &tag)
Q_INVOKABLE bool removeAbstractTags (const QString &key, const QString &lot)
Q_INVOKABLE bool removeUrlTags (const QString &url)
Q_INVOKABLE bool removeUrlTag (const QString &url, const QString &tag)
Public Member Functions inherited from TAGDB
Q_INVOKABLE bool checkExistance (const QString &tableName, const QString &searchId, const QString &search)
Q_INVOKABLE bool checkExistance (const QString &queryStr)
Static Public Member Functions
static Tagging * getInstance ()
static QString mac ()
static QString device ()
static QString id ()
Protected Member Functions
bool abstract (const QString &key, const QString &lot, const QString &comment)
Protected Member Functions inherited from TAGDB
TAGDB (QObject *parent=nullptr)
~ TAGDB ()
QSqlQuery getQuery (const QString &queryTxt)
void openDB (const QString &name)
void prepareCollectionDB () const
bool insert (const QString &tableName, const QVariantMap &insertData)
bool update (const QString &tableName, const TAG::DB &updateData, const QVariantMap &where)
bool update (const QString &table, const QString &column, const QVariant &newValue, const QVariant &op, const QString &id)
bool remove (const QString &tableName, const TAG::DB &removeData)
Private Member Functions
Tagging (QObject *parent=nullptr)
~Tagging ()
void setApp ()
bool app ()
bool user ()
Private Attributes
QString application = QString()
QString version = QString()
QString comment = QString()
QString uri = QString()
Static Private Attributes
static Tagging * instance = nullptr
Detailed Description
Definition at line 35 of file tagging.h.
Constructor & Destructor Documentation
Tagging()
Tagging::Tagging (QObject * parent = nullptr) private
Definition at line 26 of file tagging.cpp.
                                 : TAGDB(parent)
 {
     this->setApp();
 }
References setApp().
Referenced by getInstance().
~Tagging()
Tagging::~Tagging () private
Definition at line 31 of file tagging.cpp.
 {
 //  delete this->instance;
 }
Member Function Documentation
abstract()
bool Tagging::abstract (const QString & key, const QString & lot, const QString & comment) protected
Definition at line 347 of file tagging.cpp.
 {
     QVariantMap abstract_map
     {
         {TAG::KEYMAP[TAG::KEYS::APP], this->application},
         {TAG::KEYMAP[TAG::KEYS::URI], this->uri},
         {TAG::KEYMAP[TAG::KEYS::KEY], key},
         {TAG::KEYMAP[TAG::KEYS::LOT], lot},
         {TAG::KEYMAP[TAG::KEYS::ADD_DATE], QDateTime::currentDateTime()},
         {TAG::KEYMAP[TAG::KEYS::COMMENT], comment},
     };
     return this->insert(TAG::TABLEMAP[TAG::TABLE::ABSTRACT], abstract_map);
 }
References TAG::ABSTRACT, TAG::ADD_DATE, TAG::APP, application, comment, FMH::COMMENT, TAGDB::insert(), TAG::KEY, TAG::KEYMAP, TAG::LOT, TAG::TABLEMAP, TAG::URI, and uri.
abstractTagged
void Tagging::abstractTagged (const QString & key, const QString & lot, const QString & tag) signal
Referenced by tagAbstract().
app()
bool Tagging::app () private
Definition at line 305 of file tagging.cpp.
 {
     qDebug()<<"REGISTER APP" << this->application<< this->uri<< this->version<< this->comment;
     QVariantMap app_map
     {
         {TAG::KEYMAP[TAG::KEYS::APP], this->application},
         {TAG::KEYMAP[TAG::KEYS::URI], this->uri},
         {TAG::KEYMAP[TAG::KEYS::VERSION], this->version},
         {TAG::KEYMAP[TAG::KEYS::ADD_DATE], QDateTime::currentDateTime()},
         {TAG::KEYMAP[TAG::KEYS::COMMENT], this->comment},
     };
     this->insert(TAG::TABLEMAP[TAG::TABLE::APPS], app_map);
     this->user();
     QVariantMap users_apps_map
     {
         {TAG::KEYMAP[TAG::KEYS::APP], this->application},
         {TAG::KEYMAP[TAG::KEYS::URI], this->uri},
         {TAG::KEYMAP[TAG::KEYS::MAC], this->id()},
         {TAG::KEYMAP[TAG::KEYS::ADD_DATE], QDateTime::currentDateTime()},
     };
     return this->insert(TAG::TABLEMAP[TAG::TABLE::APPS_USERS], users_apps_map);
 }
References TAG::ADD_DATE, TAG::APP, application, TAG::APPS, TAG::APPS_USERS, comment, FMH::COMMENT, id(), TAGDB::insert(), TAG::KEYMAP, TAG::MAC, TAG::TABLEMAP, TAG::URI, uri, user(), version, and FMH::VERSION.
Referenced by setApp().
device()
QString Tagging::device () static
Definition at line 287 of file tagging.cpp.
 {
     return QSysInfo::prettyProductName();
 }
Referenced by user().
get()
QVariantList Tagging::get (const QString & query)
Definition at line 51 of file tagging.cpp.
 {
     QVariantList mapList;
     auto query = this->getQuery(queryTxt);
     if(query.exec())
     {
         while(query.next())
         {
             QVariantMap data;
             for(auto key : TAG::KEYMAP.keys())
                 if(query.record().indexOf(TAG::KEYMAP[key]) > -1)
                     data[TAG::KEYMAP[key]] = query.value(TAG::KEYMAP[key]).toString();
             mapList<< data;
         }
     }else qDebug()<< query.lastError()<< query.lastQuery();
     return mapList;
 }
References TAGDB::getQuery(), and TAG::KEYMAP.
Referenced by getAbstractsTags(), getAbstractTags(), getAllTags(), getUrls(), getUrlsTags(), and getUrlTags().
getAbstractsTags()
QVariantList Tagging::getAbstractsTags (const bool & strict = true)
Definition at line 197 of file tagging.cpp.
 {
     auto res = !strict ? this->get("select t.* from tags t inner join TAGS_ABSTRACT tab on tab.tag = t.tag") :
                          this->get(QString("select t.* from TAGS t inner join TAGS_USERS tu on t.tag = tu.tag "
                                            "inner join APPS_USERS au on au.mac = tu.mac "
                                            "inner join TAGS_ABSTRACT tab on tab.tag = t.tag "
                                            "where au.app = '%1' and au.uri = '%2'").arg(this->application, this->uri));
     return res;
 }
References application, get(), and uri.
Referenced by TagsList::setList().
getAbstractTags()
QVariantList Tagging::getAbstractTags (const QString & key, const QString & lot, const bool & strict = true)
Definition at line 236 of file tagging.cpp.
 {
     auto res = !strict ? this->get(QString("select t.* from TAGS t inner join TAGS_ABSTRACT ta on ta.tag = t.tag where ta.key = '%1' and ta.lot = '%2'").arg(key, lot)) :
                          this->get(QString("select distinct t.*  from TAGS t inner join TAGS_ABSTRACT ta on ta.tag = t.tag "
                                            "inner join TAGS_USERS tu on t.tag = tu.tag "
                                            "inner join APPS_USERS au on au.mac = tu.mac "
                                            "where au.app = '%1' and au.uri = '%2' and ta.key = '%3' and ta.lot = '%4'").arg(this->application, this->uri, key, lot));
     return res;
 }
References application, get(), and uri.
Referenced by removeAbstractTags(), and TagsList::setList().
getAllTags()
QVariantList Tagging::getAllTags (const bool & strict = true)
Definition at line 207 of file tagging.cpp.
 {
     auto res = !strict ? this->get("select * from tags") :
                          this->get(QString("select t.* from TAGS t inner join TAGS_USERS tu on t.tag = tu.tag inner join APPS_USERS au on au.mac = tu.mac "
                                            "where au.app = '%1' and au.uri = '%2'").arg(this->application, this->uri));
     return res;
 }
References application, get(), and uri.
Referenced by TagsList::setList().
getInstance()
Tagging * Tagging::getInstance () static
Definition at line 37 of file tagging.cpp.
 {
     if(!instance)
     {
         instance = new Tagging();
         qDebug() << "getInstance(): First instance\n";
         return instance;
     } else
     {
         qDebug()<< "getInstance(): previous instance\n";
         return instance;
     }
 }
References instance, and Tagging().
Referenced by FM::init().
getUrls()
QVariantList Tagging::getUrls (const QString & tag, const bool & strict = true)
Definition at line 215 of file tagging.cpp.
 {
     auto res =  !strict ? this->get(QString("select turl.*, t.color, t.comment as tagComment from TAGS t inner join TAGS_URLS turl on turl.tag = t.tag where t.tag = '%1'").arg(tag)):
                           this->get(QString("select distinct turl.*, t.color, t.comment as tagComment from TAGS t "
                                             "inner join TAGS_USERS tu on t.tag = tu.tag "
                                             "inner join APPS_USERS au on au.mac = tu.mac "
                                             "inner join TAGS_URLS turl on turl.tag = t.tag "
                                             "where au.app = '%1' and au.uri = '%2' "
                                             "and t.tag = '%3'").arg(this->application, this->uri, tag));
     return res;
 }
References application, get(), tag(), and uri.
getUrlsTags()
QVariantList Tagging::getUrlsTags (const bool & strict = true)
Definition at line 183 of file tagging.cpp.
 {
     auto query = QString("select distinct t.* from TAGS t inner join TAGS_USERS tu on t.tag = tu.tag "
                          "inner join APPS_USERS au on au.mac = tu.mac "
                          "inner join TAGS_URLS turl on turl.tag = t.tag "
                          "where au.app = '%1' and au.uri = '%2'").arg(this->application, this->uri);
     qDebug()<<"URL TAGS QUEY"<<query;
     auto res = !strict ? this->get("select distinct t.* from tags t inner join TAGS_URLS turl on turl.tag = t.tag") :
                          this->get(query);
     return res;
 }
References application, get(), and uri.
Referenced by FM::getTags().
getUrlTags()
QVariantList Tagging::getUrlTags (const QString & url, const bool & strict = true)
Definition at line 227 of file tagging.cpp.
 {
     auto res = !strict ? this->get(QString("select turl.*, t.color, t.comment as tagComment from tags t inner join TAGS_URLS turl on turl.tag = t.tag where turl.url  = '%1'").arg(url)) :
                          this->get(QString("select distinct t.* from TAGS t inner join TAGS_USERS tu on t.tag = tu.tag inner join APPS_USERS au on au.mac = tu.mac inner join TAGS_URLS turl on turl.tag = t.tag "
                                            "where au.app = '%1' and au.uri = '%2' and turl.url = '%3'").arg(this->application, this->uri, url));
     return res;
 }
References application, get(), and uri.
Referenced by removeUrlTags(), and TagsList::setList().
id()
QString Tagging::id () static
Definition at line 292 of file tagging.cpp.
 {
     return QSysInfo::machineHostName();
     //    qDebug()<< "VERSION IS LES THAN "<< QT_VERSION;
     //#if QT_VERSION < QT_VERSION_CHECK(5, 1, 1)
     //    return QSysInfo::machineHostName();
     //#else
     //    return QString(QSysInfo::machineUniqueId());
     //#endif
 }
Referenced by app(), tag(), and user().
mac()
QString Tagging::mac () static
Definition at line 280 of file tagging.cpp.
 {
     QNetworkInterface mac;
     qDebug()<< "MAC ADDRES:"<< mac.hardwareAddress();
     return mac.hardwareAddress();
 }
removeAbstractTag()
bool Tagging::removeAbstractTag (const QString & key, const QString & lot, const QString & tag)
Definition at line 246 of file tagging.cpp.
 {
     TAG::DB data {{TAG::KEYS::KEY, key}, {TAG::KEYS::LOT, lot}, {TAG::KEYS::TAG, tag}};
     return this->remove(TAG::TABLEMAP[TAG::TABLE::TAGS_ABSTRACT], data);
 }
References TAG::KEY, TAG::LOT, TAGDB::remove(), TAG::TABLEMAP, tag(), FMH::TAG, and TAG::TAGS_ABSTRACT.
Referenced by removeAbstractTags(), TagsList::removeFrom(), and TagsList::removeFromAbstract().
removeAbstractTags()
bool Tagging::removeAbstractTags (const QString & key, const QString & lot)
Definition at line 252 of file tagging.cpp.
 {
     for(auto map : this->getAbstractTags(key, lot))
     {
         auto tag = map.toMap().value(TAG::KEYMAP[TAG::KEYS::TAG]).toString();
         this->removeAbstractTag(key, lot, tag);
     }
     return true;
 }
References getAbstractTags(), TAG::KEYMAP, removeAbstractTag(), tag(), and FMH::TAG.
Referenced by updateAbstractTags().
removeUrlTag()
bool Tagging::removeUrlTag (const QString & url, const QString & tag)
Definition at line 274 of file tagging.cpp.
 {
     TAG::DB data {{TAG::KEYS::URL, url}, {TAG::KEYS::TAG, tag}};
     return this->remove(TAG::TABLEMAP[TAG::TABLE::TAGS_URLS], data);
 }
References TAGDB::remove(), TAG::TABLEMAP, tag(), FMH::TAG, TAG::TAGS_URLS, and FMH::URL.
Referenced by TagsList::removeFrom(), TagsList::removeFromUrls(), and removeUrlTags().
removeUrlTags()
bool Tagging::removeUrlTags (const QString & url)
Definition at line 263 of file tagging.cpp.
 {
     for(auto map : this->getUrlTags(url))
     {
         auto tag = map.toMap().value(TAG::KEYMAP[TAG::KEYS::TAG]).toString();
         this->removeUrlTag(url, tag);
     }
     return true;
 }
References getUrlTags(), TAG::KEYMAP, removeUrlTag(), tag(), and FMH::TAG.
Referenced by updateUrlTags().
setApp()
void Tagging::setApp () private
Definition at line 83 of file tagging.cpp.
 {
     this->application = UTIL::app->applicationName();
     this->version = UTIL::app->applicationVersion();
     this->comment = QString();
     this->uri = UTIL::app->organizationName().isEmpty() ? QString("org.maui.%1").arg(this->application) : UTIL::app->organizationName();
     this->app();
 }
References UTIL::app, app(), application, comment, uri, and version.
Referenced by Tagging().
tag()
bool Tagging::tag (const QString & tag, const QString & color = QString(), const QString & comment = QString())
Definition at line 92 of file tagging.cpp.
 {
     if(tag.isEmpty()) return false;
     QVariantMap tag_map
     {
         {TAG::KEYMAP[TAG::KEYS::TAG], tag},
         {TAG::KEYMAP[TAG::KEYS::COLOR], color},
         {TAG::KEYMAP[TAG::KEYS::ADD_DATE], QDateTime::currentDateTime()},
         {TAG::KEYMAP[TAG::KEYS::COMMENT], comment},
     };
     this->insert(TAG::TABLEMAP[TAG::TABLE::TAGS], tag_map);
     QVariantMap tag_user_map
     {
         {TAG::KEYMAP[TAG::KEYS::TAG], tag},
         {TAG::KEYMAP[TAG::KEYS::MAC], this->id()}
     };
     if(this->insert(TAG::TABLEMAP[TAG::TABLE::TAGS_USERS], tag_user_map))
     {
         emit this->tagged(tag);
         return true;
     }
     return false;
 }
References TAG::ADD_DATE, FMH::COLOR, comment, FMH::COMMENT, id(), TAGDB::insert(), TAG::KEYMAP, TAG::MAC, TAG::TABLEMAP, FMH::TAG, tagged(), TAG::TAGS, and TAG::TAGS_USERS.
Referenced by getUrls(), removeAbstractTag(), removeAbstractTags(), removeUrlTag(), removeUrlTags(), tagAbstract(), tagUrl(), updateAbstractTags(), and updateUrlTags().
tagAbstract()
bool Tagging::tagAbstract (const QString & tag, const QString & key, const QString & lot, const QString & color = QString(), const QString & comment = QString())
Definition at line 144 of file tagging.cpp.
 {
     this->abstract(key, lot, comment);
     this->tag(tag, color, comment);
     QVariantMap tag_abstract_map
     {
         {TAG::KEYMAP[TAG::KEYS::APP], this->application},
         {TAG::KEYMAP[TAG::KEYS::URI], this->uri},
         {TAG::KEYMAP[TAG::KEYS::TAG], tag},
         {TAG::KEYMAP[TAG::KEYS::KEY], key},
         {TAG::KEYMAP[TAG::KEYS::LOT], lot},
         {TAG::KEYMAP[TAG::KEYS::ADD_DATE], QDateTime::currentDateTime()},
         {TAG::KEYMAP[TAG::KEYS::COMMENT], comment},
     };
     emit this->abstractTagged(key, lot, tag);
     return this->insert(TAG::TABLEMAP[TAG::TABLE::TAGS_ABSTRACT], tag_abstract_map);
 }
References abstractTagged(), TAG::ADD_DATE, TAG::APP, application, comment, FMH::COMMENT, TAGDB::insert(), TAG::KEY, TAG::KEYMAP, TAG::LOT, TAG::TABLEMAP, tag(), FMH::TAG, TAG::TAGS_ABSTRACT, TAG::URI, and uri.
Referenced by updateAbstractTags().
tagExists()
bool Tagging::tagExists (const QString & tag, const bool & strict = false)
Definition at line 75 of file tagging.cpp.
 {
     return !strict ? this->checkExistance(TAG::TABLEMAP[TAG::TABLE::TAGS], TAG::KEYMAP[TAG::KEYS::TAG], tag) :
             this->checkExistance(QString("select t.tag from TAGS t inner join TAGS_USERS tu on t.tag = tu.tag inner join APPS_USERS au on au.mac = tu.mac "
             "where au.app = '%1' and au.uri = '%2' and t.tag = '%3'").arg(this->application, this->uri, tag));
 }
References application, TAGDB::checkExistance(), TAG::KEYMAP, TAG::TABLEMAP, FMH::TAG, TAG::TAGS, and uri.
tagged
void Tagging::tagged (const QString & tag) signal
Referenced by tag().
tagUrl()
bool Tagging::tagUrl (const QString & url, const QString & tag, const QString & color = QString(), const QString & comment = QString())
Definition at line 121 of file tagging.cpp.
 {
     auto myTag = tag.trimmed();
     this->tag(myTag, color, comment);
     QMimeDatabase mimedb;
     auto mime = mimedb.mimeTypeForFile(url);
     QVariantMap tag_url_map
     {
         {TAG::KEYMAP[TAG::KEYS::URL], url},
         {TAG::KEYMAP[TAG::KEYS::TAG], myTag},
         {TAG::KEYMAP[TAG::KEYS::TITLE], QFileInfo(url).baseName()},
         {TAG::KEYMAP[TAG::KEYS::MIME], mime.name()},
         {TAG::KEYMAP[TAG::KEYS::ADD_DATE], QDateTime::currentDateTime()},
         {TAG::KEYMAP[TAG::KEYS::COMMENT], comment}
     };
     emit this->urlTagged(url, myTag);
     return this->insert(TAG::TABLEMAP[TAG::TABLE::TAGS_URLS], tag_url_map);
 }
References TAG::ADD_DATE, comment, FMH::COMMENT, TAGDB::insert(), TAG::KEYMAP, FMH::MIME, TAG::TABLEMAP, tag(), FMH::TAG, TAG::TAGS_URLS, FMH::TITLE, FMH::URL, and urlTagged().
Referenced by updateUrlTags().
updateAbstractTags()
bool Tagging::updateAbstractTags (const QString & key, const QString & lot, const QStringList & tags)
Definition at line 173 of file tagging.cpp.
 {
     this->removeAbstractTags(key, lot);
     for(auto tag : tags)
         this->tagAbstract(tag, key, lot);
     return true;
 }
References removeAbstractTags(), tag(), and tagAbstract().
Referenced by TagsList::updateToAbstract().
updateUrlTags()
bool Tagging::updateUrlTags (const QString & url, const QStringList & tags)
Definition at line 164 of file tagging.cpp.
 {
     this->removeUrlTags(url);
     for(auto tag : tags)
         this->tagUrl(url, tag);
     return true;
 }
References removeUrlTags(), tag(), and tagUrl().
Referenced by TagsList::updateToUrls().
urlTagged
void Tagging::urlTagged (const QString & url, const QString & tag) signal
Referenced by tagUrl().
user()
bool Tagging::user () private
Definition at line 333 of file tagging.cpp.
 {
     QVariantMap user_map
     {
         {TAG::KEYMAP[TAG::KEYS::MAC], this->id()},
         {TAG::KEYMAP[TAG::KEYS::NAME], UTIL::whoami()},
         {TAG::KEYMAP[TAG::KEYS::LAST_SYNC], QDateTime::currentDateTime()},
         {TAG::KEYMAP[TAG::KEYS::ADD_DATE], QDateTime::currentDateTime()},
         {TAG::KEYMAP[TAG::KEYS::DEVICE], this->device()},
     };
     return this->insert(TAG::TABLEMAP[TAG::TABLE::USERS], user_map);
 }
References TAG::ADD_DATE, device(), TAG::DEVICE, id(), TAGDB::insert(), TAG::KEYMAP, TAG::LAST_SYNC, TAG::MAC, FMH::NAME, TAG::TABLEMAP, TAG::USERS, and UTIL::whoami().
Referenced by app().
Field Documentation
application
QString Tagging::application = QString() private
Definition at line 84 of file tagging.h.
Referenced by abstract(), app(), getAbstractsTags(), getAbstractTags(), getAllTags(), getUrls(), getUrlsTags(), getUrlTags(), setApp(), tagAbstract(), and tagExists().
comment
QString Tagging::comment = QString() private
Definition at line 86 of file tagging.h.
Referenced by abstract(), app(), setApp(), tag(), tagAbstract(), and tagUrl().
instance
Tagging * Tagging::instance = nullptr static private
Definition at line 81 of file tagging.h.
Referenced by getInstance().
uri
QString Tagging::uri = QString() private
Definition at line 87 of file tagging.h.
Referenced by abstract(), app(), getAbstractsTags(), getAbstractTags(), getAllTags(), getUrls(), getUrlsTags(), getUrlTags(), setApp(), tagAbstract(), and tagExists().
version
QString Tagging::version = QString() private
Definition at line 85 of file tagging.h.
Referenced by app(), and setApp().
The documentation for this class was generated from the following files:
utils/tagging/tagging.h
utils/tagging/tagging.cpp