MauiKit: Environment Class Reference
Environment Class Reference
#include <Environment.hpp>
Static Public Member Functions
static QString get (QString key)
Detailed Description
Definition at line 6 of file Environment.hpp.
Member Function Documentation
get()
QString Environment::get (QString key) static
Definition at line 5 of file Environment.cpp.
{
   char* val = getenv(key.toStdString().c_str());
   return val == NULL ? QString("") : QString(val);
 }
Referenced by TestWebDAVClient::initTestCase(), TestWebDAVClient::testCopyDir(), TestWebDAVClient::testCreateDir(), TestWebDAVClient::testListDir(), TestWebDAVClient::testListDirWithDepth(), TestWebDAVClient::testMoveDir(), TestWebDAVClient::testRemove(), TestWebDAVClient::testRemoveDir(), and TestWebDAVClient::testUpload().
The documentation for this class was generated from the following files:
utils/syncing/libwebdavclient/lib/utils/Environment.hpp
utils/syncing/libwebdavclient/lib/utils/Environment.cpp