MauiKit: TagsModel Class Reference
TagsModel Class Reference
#include <tagsmodel.h>
Signals
void listChanged ()
Public Member Functions
TagsModel (QObject *parent=nullptr)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
virtual QHash< int, QByteArray > roleNames () const override
TagsList * getList () const
void setList (TagsList *value)
Properties
TagsList list
Private Attributes
TagsList * mList
Detailed Description
Definition at line 8 of file tagsmodel.h.
Constructor & Destructor Documentation
TagsModel()
TagsModel::TagsModel (QObject * parent = nullptr) explicit
Definition at line 6 of file tagsmodel.cpp.
     : QAbstractListModel(parent),
       mList(nullptr)
 {}
Member Function Documentation
data()
QVariant TagsModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 19 of file tagsmodel.cpp.
 {
     if (!index.isValid() || !mList)
         return QVariant();
     return this->mList->items().at(index.row())[static_cast<TAG::KEYS>(role)];
 }
References TagsList::items(), and mList.
flags()
Qt::ItemFlags TagsModel::flags (const QModelIndex & index) const override
Definition at line 33 of file tagsmodel.cpp.
 {
     if (!index.isValid())
         return Qt::NoItemFlags;
     return Qt::ItemIsEditable; // FIXME: Implement me!
 }
getList()
TagsList * TagsModel::getList () const
Definition at line 51 of file tagsmodel.cpp.
 {
     return this->mList;
 }
References mList.
listChanged
void TagsModel::listChanged () signal
roleNames()
QHash< int, QByteArray > TagsModel::roleNames () const override virtual
Definition at line 41 of file tagsmodel.cpp.
 {
     QHash<int, QByteArray> names;
         for(auto key : TAG::KEYMAP.keys())
             names[key] = QString(TAG::KEYMAP[key]).toUtf8();
         return names;
 }
References TAG::KEYMAP.
rowCount()
int TagsModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 11 of file tagsmodel.cpp.
 {
     if (parent.isValid() || !mList)
         return 0;
     return mList->items().size();
 }
References TagsList::items(), and mList.
setData()
bool TagsModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 27 of file tagsmodel.cpp.
 {
     return false;
 }
setList()
void TagsModel::setList (TagsList * value)
Definition at line 56 of file tagsmodel.cpp.
 {
     beginResetModel();
     if(mList)
         mList->disconnect(this);
     mList = value;
     if(mList)
     {
         connect(this->mList, &TagsList::preItemAppended, this, [=]()
         {
             const int index = mList->items().size();
             beginInsertRows(QModelIndex(), index, index);
         });
         connect(this->mList, &TagsList::postItemAppended, this, [=]()
         {
             endInsertRows();
         });
         connect(this->mList, &TagsList::preItemRemoved, this, [=](int index)
         {
             beginRemoveRows(QModelIndex(), index, index);
         });
         connect(this->mList, &TagsList::postItemRemoved, this, [=]()
         {
             endRemoveRows();
         });
         connect(this->mList, &TagsList::updateModel, this, [=](int index, QVector<int> roles)
         {
             emit this->dataChanged(this->index(index), this->index(index), roles);
         });
         connect(this->mList, &TagsList::preListChanged, this, [=]()
         {
             beginResetModel();
         });
         connect(this->mList, &TagsList::postListChanged, this, [=]()
         {
             endResetModel();
         });
     }
     endResetModel();
 }
References TagsList::items(), mList, TagsList::postItemAppended(), TagsList::postItemRemoved(), TagsList::postListChanged(), TagsList::preItemAppended(), TagsList::preItemRemoved(), TagsList::preListChanged(), and TagsList::updateModel().
Field Documentation
mList
TagsList* TagsModel::mList private
Definition at line 32 of file tagsmodel.h.
Referenced by data(), getList(), rowCount(), and setList().
Property Documentation
list
TagsList TagsModel::list read write
Definition at line 11 of file tagsmodel.h.
The documentation for this class was generated from the following files:
utils/tagging/tagsmodel.h
utils/tagging/tagsmodel.cpp