MauiKit: TestWebDAVClient Class Reference
TestWebDAVClient Class Reference
Private Slots
void initTestCase ()
void testListDir ()
void testListDirWithDepth ()
void testDownload ()
void testUpload ()
void testCreateDir ()
void testCopyDir ()
void testMoveDir ()
void testRemove ()
void testRemoveDir ()
void cleanupTestCase ()
Private Member Functions
void listDirOutputHandler (WebDAVReply *reply)
Private Attributes
QCoreApplication * app
WebDAVClient * client
Detailed Description
Definition at line 14 of file TestWebDAVClient.cpp.
Member Function Documentation
cleanupTestCase
void TestWebDAVClient::cleanupTestCase () inline private slot
Definition at line 241 of file TestWebDAVClient.cpp.
 { delete this->app; }
References app.
initTestCase
void TestWebDAVClient::initTestCase () inline private slot
Definition at line 42 of file TestWebDAVClient.cpp.
                       {
     int argc = 1;
     char *argv[] = {"test"};
     this->app = new QCoreApplication(argc, argv);
     this->client =
         new WebDAVClient(Environment::get("LIBWEBDAV_TEST_HOST"),
                          Environment::get("LIBWEBDAV_TEST_USER"),
                          Environment::get("LIBWEBDAV_TEST_PASSWORD"));
   }
References Environment::get().
listDirOutputHandler()
void TestWebDAVClient::listDirOutputHandler (WebDAVReply * reply) inline private
Definition at line 21 of file TestWebDAVClient.cpp.
{
     connect(reply, &WebDAVReply::listDirResponse,
             [=](QNetworkReply *listDirReply, QList<WebDAVItem> items) {
               qDebug() << "URL :" << listDirReply->url();
               qDebug() << "Received List of" << items.length() << "items";
               qDebug() << endl << "---------------------------------------";
               for (WebDAVItem item : items) {
                 qDebug().noquote() << endl << item.toString();
                 qDebug() << endl << "---------------------------------------";
               }
               QCoreApplication::exit(0);
             });
     connect(reply, &WebDAVReply::error, [=](QNetworkReply::NetworkError err) {
       qDebug() << err;
       QCoreApplication::exit(1);
     });
   }
References WebDAVReply::error(), and WebDAVReply::listDirResponse().
Referenced by testListDir(), and testListDirWithDepth().
testCopyDir
void TestWebDAVClient::testCopyDir () inline private slot
Definition at line 144 of file TestWebDAVClient.cpp.
                      {
     QString dirName = QDate::currentDate().toString(Qt::DateFormat::ISODate);
     WebDAVReply *reply = this->client->copy(
         Environment::get("LIBWEBDAV_TEST_PATH") + "/tttt.cpp",
         Environment::get("LIBWEBDAV_TEST_PATH") + "/" + dirName +
             "/tttt-copy.cpp");
     connect(reply, &WebDAVReply::copyFinished, [=](QNetworkReply *reply) {
       if (!reply->error()) {
         qDebug() << "\nItem Copied"
                  << "\nURL  :" << reply->url();
       } else {
         qDebug() << "ERROR(COPY)" << reply->error();
       }
       QCoreApplication::exit(0);
     });
     connect(reply, &WebDAVReply::error, [=](QNetworkReply::NetworkError err) {
       qDebug() << "ERROR" << err;
       QCoreApplication::exit(1);
     });
     this->app->exec();
   }
References WebDAVClient::copy(), WebDAVReply::copyFinished(), WebDAVReply::error(), and Environment::get().
testCreateDir
void TestWebDAVClient::testCreateDir () inline private slot
Definition at line 121 of file TestWebDAVClient.cpp.
{
     QString dirName = QDate::currentDate().toString(Qt::DateFormat::ISODate);
     WebDAVReply *reply = this->client->createDir(
         Environment::get("LIBWEBDAV_TEST_PATH"), dirName);
     connect(reply, &WebDAVReply::createDirFinished, [=](QNetworkReply *reply) {
       if (!reply->error()) {
         qDebug() << "\nDir Created"
                  << "\nURL  :" << reply->url();
       } else {
         qDebug() << "ERROR(CREATE DIR)" << reply->error();
       }
       QCoreApplication::exit(0);
     });
     connect(reply, &WebDAVReply::error, [=](QNetworkReply::NetworkError err) {
       qDebug() << "ERROR" << err;
       QCoreApplication::exit(1);
     });
     this->app->exec();
   }
References WebDAVClient::createDir(), WebDAVReply::createDirFinished(), WebDAVReply::error(), and Environment::get().
testDownload
void TestWebDAVClient::testDownload () inline private slot
Definition at line 66 of file TestWebDAVClient.cpp.
                       {
     QString url = "/remote.php/webdav/Nextcloud%20Manual.pdf";
     WebDAVReply *reply = this->client->downloadFrom(url);
     connect(reply, &WebDAVReply::downloadResponse, [=](QNetworkReply *reply) {
       if (!reply->error()) {
         qDebug() << "\nDownload Success"
                  << "\nURL  :" << reply->url() << "\nSize :" << reply->size();
       } else {
         qDebug() << "ERROR(DOWNLOAD)" << reply->error();
       }
       QCoreApplication::exit(0);
     });
     connect(reply, &WebDAVReply::downloadProgressResponse,
             [=](qint64 bytesReceived, qint64 bytesTotal) {
               int percent = ((float)bytesReceived / bytesTotal) * 100;
               qDebug() << "\nReceived : " << bytesReceived
                        << "\nTotal    : " << bytesTotal
                        << "\nPercent  : " << percent;
             });
     connect(reply, &WebDAVReply::error, [=](QNetworkReply::NetworkError err) {
       qDebug() << "ERROR" << err;
       QCoreApplication::exit(1);
     });
     this->app->exec();
   }
References WebDAVClient::downloadFrom(), WebDAVReply::downloadProgressResponse(), WebDAVReply::downloadResponse(), and WebDAVReply::error().
testListDir
void TestWebDAVClient::testListDir () inline private slot
Definition at line 53 of file TestWebDAVClient.cpp.
                      {
     this->listDirOutputHandler(
         this->client->listDir(Environment::get("LIBWEBDAV_TEST_PATH")));
     this->app->exec();
   }
References Environment::get(), WebDAVClient::listDir(), and listDirOutputHandler().
testListDirWithDepth
void TestWebDAVClient::testListDirWithDepth () inline private slot
Definition at line 59 of file TestWebDAVClient.cpp.
{
     this->listDirOutputHandler(this->client->listDir(
         Environment::get("LIBWEBDAV_TEST_PATH"), ListDepthEnum::One));
     this->app->exec();
   }
References Environment::get(), WebDAVClient::listDir(), listDirOutputHandler(), and One.
testMoveDir
void TestWebDAVClient::testMoveDir () inline private slot
Definition at line 169 of file TestWebDAVClient.cpp.
                      {
     QString dirName = QDate::currentDate().toString(Qt::DateFormat::ISODate);
     WebDAVReply *reply = this->client->move(
         Environment::get("LIBWEBDAV_TEST_PATH") + "/tttt.cpp",
         Environment::get("LIBWEBDAV_TEST_PATH") + "/" + dirName + "/tttt.cpp",
         true);
     connect(reply, &WebDAVReply::moveFinished, [=](QNetworkReply *reply) {
       if (!reply->error()) {
         qDebug() << "\nItem Moved"
                  << "\nURL  :" << reply->url();
       } else {
         qDebug() << "ERROR(MOVE DIR)" << reply->error();
       }
       QCoreApplication::exit(0);
     });
     connect(reply, &WebDAVReply::error, [=](QNetworkReply::NetworkError err) {
       qDebug() << "ERROR" << err;
       QCoreApplication::exit(1);
     });
     this->app->exec();
   }
References WebDAVReply::error(), Environment::get(), WebDAVClient::move(), and WebDAVReply::moveFinished().
testRemove
void TestWebDAVClient::testRemove () inline private slot
Definition at line 194 of file TestWebDAVClient.cpp.
                     {
     QString dirName = QDate::currentDate().toString(Qt::DateFormat::ISODate);
     WebDAVReply *reply = this->client->remove(
         Environment::get("LIBWEBDAV_TEST_PATH") + "/" + dirName + "/tttt.cpp");
     connect(reply, &WebDAVReply::removeFinished, [=](QNetworkReply *reply) {
       if (!reply->error()) {
         qDebug() << "\nItem Removed"
                  << "\nURL  :" << reply->url();
       } else {
         qDebug() << "ERROR(REMOVE File)" << reply->error();
       }
       QCoreApplication::exit(0);
     });
     connect(reply, &WebDAVReply::error, [=](QNetworkReply::NetworkError err) {
       qDebug() << "ERROR" << err;
       QCoreApplication::exit(1);
     });
     this->app->exec();
   }
References WebDAVReply::error(), Environment::get(), WebDAVClient::remove(), and WebDAVReply::removeFinished().
testRemoveDir
void TestWebDAVClient::testRemoveDir () inline private slot
Definition at line 218 of file TestWebDAVClient.cpp.
{
     QString dirName = QDate::currentDate().toString(Qt::DateFormat::ISODate);
     WebDAVReply *reply = this->client->remove(
         Environment::get("LIBWEBDAV_TEST_PATH") + "/" + dirName);
     connect(reply, &WebDAVReply::removeFinished, [=](QNetworkReply *reply) {
       if (!reply->error()) {
         qDebug() << "\nItem Removed"
                  << "\nURL  :" << reply->url();
       } else {
         qDebug() << "ERROR(REMOVE Dir)" << reply->error();
       }
       QCoreApplication::exit(0);
     });
     connect(reply, &WebDAVReply::error, [=](QNetworkReply::NetworkError err) {
       qDebug() << "ERROR" << err;
       QCoreApplication::exit(1);
     });
     this->app->exec();
   }
References WebDAVReply::error(), Environment::get(), WebDAVClient::remove(), and WebDAVReply::removeFinished().
testUpload
void TestWebDAVClient::testUpload () inline private slot
Definition at line 96 of file TestWebDAVClient.cpp.
                     {
     QString url = Environment::get("LIBWEBDAV_TEST_PATH");
     QFile file("/home/anupam/libwebdav/lib/WebDAVClient.cpp");
     file.open(QIODevice::ReadOnly);
     WebDAVReply *reply = this->client->uploadTo(url, "tttt.cpp", &file);
     connect(reply, &WebDAVReply::uploadFinished, [=](QNetworkReply *reply) {
       if (!reply->error()) {
         qDebug() << "\nUpload Success"
                  << "\nURL  :" << reply->url() << "\nSize :" << reply->size();
       } else {
         qDebug() << "ERROR(UPLOAD)" << reply->error();
       }
       QCoreApplication::exit(0);
     });
     connect(reply, &WebDAVReply::error, [=](QNetworkReply::NetworkError err) {
       qDebug() << "ERROR" << err;
       QCoreApplication::exit(1);
     });
     this->app->exec();
   }
References WebDAVReply::error(), Environment::get(), WebDAVReply::uploadFinished(), and WebDAVClient::uploadTo().
Field Documentation
app
QCoreApplication* TestWebDAVClient::app private
Definition at line 18 of file TestWebDAVClient.cpp.
Referenced by cleanupTestCase().
client
WebDAVClient* TestWebDAVClient::client private
Definition at line 19 of file TestWebDAVClient.cpp.
The documentation for this class was generated from the following file:
utils/syncing/libwebdavclient/lib/tests/TestWebDAVClient.cpp