MauiKit: StoreList Class Reference
StoreList Class Reference
#include <storelist.h>
Public Types
enum PROVIDER : uint_fast8_t { OPENDESKTOP, KDELOOK, KRITA, OPENDESKTOPCC }
Public Slots
void getPersonInfo (const QString &nick)
QVariantList getCategoryList ()
QVariantMap get (const int &index) const
void download (const int &index)
bool fileExists (const int &index)
QString itemLocalPath (const int &index)
Signals
void preItemAppended ()
void postItemAppended ()
void preItemRemoved (int index)
void postItemRemoved ()
void updateModel (int index, QVector< int > roles)
void preListChanged ()
void postListChanged ()
void categoryChanged ()
void limitChanged ()
void queryChanged ()
void orderChanged ()
void pageChanged ()
void contentReadyChanged ()
void contentEmptyChanged ()
void sortByChanged ()
void providerChanged ()
void warning (QString warning)
void downloadReady (QVariantMap item)
Public Member Functions
StoreList (QObject *parent=nullptr)
FMH::MODEL_LIST items () const
void setLimit (const int &value)
int getLimit () const
void setPage (const int &value)
int getPage () const
void setQuery (const QString &value)
QString getQuery () const
void setOrder (const StoreList::ORDER &value)
StoreList::ORDER getOrder () const
bool getContentReady () const
bool getContentEmpty () const
StoreList::SORTBY getSortBy () const
void setSortBy (const StoreList::SORTBY &key)
StoreList::PROVIDER getProvider () const
void setProvider (const StoreList::PROVIDER &key)
Properties
StoreList::CATEGORY category
int limit = 10
int page = 0
QString query
StoreList::ORDER order
bool contentReady = false
bool contentEmpty = true
StoreList::SORTBY sortBy = StoreList::SORTBY::DATE
StoreList::PROVIDER provider = StoreList::PROVIDER::KDELOOK
Private Member Functions
void setList ()
void sortList ()
Private Attributes
FMH::MODEL_LIST list
Store * store
Detailed Description
Definition at line 26 of file storelist.h.
Member Enumeration Documentation
PROVIDER
enum StoreList::PROVIDER : uint_fast8_t
Enumerator
OPENDESKTOP
KDELOOK
KRITA
OPENDESKTOPCC
Definition at line 43 of file storelist.h.
                   : uint_fast8_t
     {
         OPENDESKTOP,
         KDELOOK,
         KRITA,
         OPENDESKTOPCC
     };Q_ENUM(PROVIDER)
Constructor & Destructor Documentation
StoreList()
StoreList::StoreList (QObject * parent = nullptr)
Definition at line 22 of file storelist.cpp.
                                     : QObject(parent)
 {
     this->store = new Store(this);
     this->store->setProvider(STORE::KDELOOK_API);
     this->store->start();
     connect(this->store, &Store::contentReady, [this](const FMH::MODEL_LIST &list)
     {
         emit this->preListChanged();
         this->list = list;
         this->sortList();
         qDebug()<< "STORE LIST READY" << list;
         emit this->postListChanged();
         this->contentReady = true;
         emit this->contentReadyChanged();
         this->contentEmpty = this->list.isEmpty();
         emit this->contentEmptyChanged();
     });
     connect(this->store, &Store::warning, [this](const QString warning)
     {
         emit this->warning(warning);
     });
     connect(this->store, &Store::downloadReady, [this] (const FMH::MODEL &item)
     {
         emit this->downloadReady(FM::toMap(item));
     });
     connect(this->store, &Store::storeReady, this, &StoreList::setList);
 }
References contentEmpty, contentEmptyChanged(), Store::contentReady(), contentReady, contentReadyChanged(), downloadReady(), Store::downloadReady(), STORE::KDELOOK_API, list, postListChanged(), preListChanged(), setList(), Store::setProvider(), sortList(), Store::start(), store, Store::storeReady(), FM::toMap(), warning(), and Store::warning().
Member Function Documentation
categoryChanged
void StoreList::categoryChanged () signal
contentEmptyChanged
void StoreList::contentEmptyChanged () signal
Referenced by setList(), and StoreList().
contentReadyChanged
void StoreList::contentReadyChanged () signal
Referenced by setList(), and StoreList().
download
void StoreList::download (const int & index) slot
Definition at line 70 of file storelist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return;
     //  this->store->download(this->list[index][FMH::MODEL_KEY::ID]);
     this->store->download(this->list[index]);
 }
References Store::download(), list, and store.
downloadReady
void StoreList::downloadReady (QVariantMap item) signal
Referenced by StoreList().
fileExists
bool StoreList::fileExists (const int & index) slot
Definition at line 306 of file storelist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return false;
     const auto url = this->list[index][FMH::MODEL_KEY::URL];
     const QStringList filePathList = url.split('/');
     const auto fileName = filePathList.at(filePathList.count() - 1);
     qDebug() << "Check if file exists" << FMH::DownloadsPath+"/"+fileName;
     return FMH::fileExists(FMH::DownloadsPath+"/"+fileName);
 }
References FMH::DownloadsPath, FMH::fileExists(), list, and FMH::URL.
Referenced by itemLocalPath().
get
QVariantMap StoreList::get (const int & index) const slot
Definition at line 56 of file storelist.cpp.
 {
     if(index >= this->list.size() || index < 0)
         return QVariantMap();
     QVariantMap res;
     const auto model = this->list.at(index);
     for(auto key : model.keys())
         res.insert(FMH::MODEL_NAME[key], model[key]);
     return res;
 }
References list, and FMH::MODEL_NAME.
getCategoryList
QVariantList StoreList::getCategoryList () slot
Definition at line 182 of file storelist.cpp.
 {
     QVariantList res;
     auto data = STORE::CATEGORIES[static_cast<STORE::CATEGORY_KEY>(this->category)];
     for(auto category : data)
         res << QVariantMap {{FMH::MODEL_NAME[FMH::MODEL_KEY::LABEL], category}};
     return res;
 }
References STORE::CATEGORIES, category, FMH::LABEL, and FMH::MODEL_NAME.
getContentEmpty()
bool StoreList::getContentEmpty () const
Definition at line 198 of file storelist.cpp.
 {
     return this->contentEmpty;
 }
References contentEmpty.
getContentReady()
bool StoreList::getContentReady () const
Definition at line 193 of file storelist.cpp.
 {
     return this->contentReady;
 }
References contentReady.
getLimit()
int StoreList::getLimit () const
Definition at line 119 of file storelist.cpp.
 {
     return this->limit;
 }
References limit.
getOrder()
StoreList::ORDER StoreList::getOrder () const
Definition at line 149 of file storelist.cpp.
 {
     return this->order;
 }
References order.
getPage()
int StoreList::getPage () const
Definition at line 134 of file storelist.cpp.
 {
     return this->page;
 }
References page.
getPersonInfo
void StoreList::getPersonInfo (const QString & nick) slot
Definition at line 84 of file storelist.cpp.
 {
     this->store->getPersonInfo(nick);
 }
References Store::getPersonInfo(), and store.
getProvider()
StoreList::PROVIDER StoreList::getProvider () const
Definition at line 273 of file storelist.cpp.
 {
     return this->provider;
 }
References provider.
getQuery()
QString StoreList::getQuery () const
Definition at line 163 of file storelist.cpp.
 {
     return this->query;
 }
References query.
getSortBy()
StoreList::SORTBY StoreList::getSortBy () const
Definition at line 203 of file storelist.cpp.
 {
     return this->sortBy;
 }
References sortBy.
itemLocalPath
QString StoreList::itemLocalPath (const int & index) slot
Definition at line 322 of file storelist.cpp.
 {
     if(!this->fileExists(index))
         return QString();
     const auto url = this->list[index][FMH::MODEL_KEY::URL];
     const QStringList filePathList = url.split('/');
     const auto fileName = filePathList.at(filePathList.count() - 1);
     return FMH::DownloadsPath+"/"+fileName;
 }
References FMH::DownloadsPath, fileExists(), list, and FMH::URL.
items()
FMH::MODEL_LIST StoreList::items () const
Definition at line 79 of file storelist.cpp.
 {
     return this->list;
 }
References list.
Referenced by StoreModel::data(), StoreModel::rowCount(), and StoreModel::setList().
limitChanged
void StoreList::limitChanged () signal
Referenced by setLimit().
orderChanged
void StoreList::orderChanged () signal
Referenced by setOrder().
pageChanged
void StoreList::pageChanged () signal
Referenced by setPage(), and setQuery().
postItemAppended
void StoreList::postItemAppended () signal
Referenced by StoreModel::setList().
postItemRemoved
void StoreList::postItemRemoved () signal
Referenced by StoreModel::setList().
postListChanged
void StoreList::postListChanged () signal
Referenced by StoreModel::setList(), setList(), and StoreList().
preItemAppended
void StoreList::preItemAppended () signal
Referenced by StoreModel::setList().
preItemRemoved
void StoreList::preItemRemoved (int index) signal
Referenced by StoreModel::setList().
preListChanged
void StoreList::preListChanged () signal
Referenced by StoreModel::setList(), setList(), and StoreList().
providerChanged
void StoreList::providerChanged () signal
Referenced by setProvider().
queryChanged
void StoreList::queryChanged () signal
Referenced by setQuery().
setLimit()
void StoreList::setLimit (const int & value)
Definition at line 124 of file storelist.cpp.
 {
     if(this->limit == value)
         return;
     this->limit = value;
     emit this->limitChanged();
     this->setList();
 }
References limit, limitChanged(), and setList().
setList()
void StoreList::setList () private
Definition at line 89 of file storelist.cpp.
 {
     emit this->preListChanged();
     this->list.clear();
     emit this->postListChanged();
     this->contentEmpty = this->list.isEmpty();
     emit this->contentEmptyChanged();
     this->contentReady = false;
     emit this->contentReadyChanged();
     this->store->searchFor(static_cast<STORE::CATEGORY_KEY>(this->category), this->query, this->limit, this->page, static_cast<Attica::Provider::SortMode>(this->sortBy));
 }
References category, contentEmpty, contentEmptyChanged(), contentReady, contentReadyChanged(), limit, list, page, postListChanged(), preListChanged(), query, Store::searchFor(), sortBy, and store.
Referenced by setLimit(), setPage(), setQuery(), setSortBy(), and StoreList().
setOrder()
void StoreList::setOrder (const StoreList::ORDER & value)
Definition at line 154 of file storelist.cpp.
 {
     if(this->order == value)
         return;
     this->order = value;
     emit this->orderChanged();
 }
References order, and orderChanged().
setPage()
void StoreList::setPage (const int & value)
Definition at line 139 of file storelist.cpp.
 {
     if(this->page == value)
         return;
     this->page = value;
     emit this->pageChanged();
     this->setList();
 }
References page, pageChanged(), and setList().
setProvider()
void StoreList::setProvider (const StoreList::PROVIDER & key)
Definition at line 278 of file storelist.cpp.
 {
     if(this->provider == key)
         return;
     this->provider = key;
     STORE::PROVIDER value;
     switch(this->provider)
     {
         case StoreList::PROVIDER::KDELOOK:
             value = STORE::KDELOOK_API;
             break;
         case StoreList::PROVIDER::OPENDESKTOP:
             value = STORE::OPENDESKTOP_API;
             break;
         case StoreList::PROVIDER::OPENDESKTOPCC:
             value = STORE::OPENDESKTOPCC_API;
             break;
         case StoreList::PROVIDER::KRITA:
             value = STORE::KRITA_API;
             break;
     }
     this->store->setProvider(value);
     emit this->providerChanged();
 }
References STORE::KDELOOK_API, STORE::KRITA_API, STORE::OPENDESKTOP_API, STORE::OPENDESKTOPCC_API, provider, providerChanged(), Store::setProvider(), and store.
setQuery()
void StoreList::setQuery (const QString & value)
Definition at line 168 of file storelist.cpp.
 {
     if(this->query == value)
         return;
     this->query = value;
     emit this->queryChanged();
     this->page = 0;
     emit this->pageChanged();
     this->setList();
 }
References page, pageChanged(), query, queryChanged(), and setList().
setSortBy()
void StoreList::setSortBy (const StoreList::SORTBY & key)
Definition at line 208 of file storelist.cpp.
 {
     if(this->sortBy == key)
         return;
     this->sortBy = key;
     emit this->sortByChanged();
     this->setList();
 }
References setList(), sortBy, and sortByChanged().
sortByChanged
void StoreList::sortByChanged () signal
Referenced by setSortBy().
sortList()
void StoreList::sortList () private
Definition at line 219 of file storelist.cpp.
 {
     qDebug()<< "TRYING TO SORT LIST" << this->list.size();
     qSort(this->list.begin(), this->list.begin(), [this](const FMH::MODEL& e1, const FMH::MODEL& e2) -> bool
     {
         qDebug()<< "TRYIT LIST";
         auto role = static_cast<FMH::MODEL_KEY>(this->sortBy);;
         switch(role)
         {
             case FMH::MODEL_KEY::RATE:
             case FMH::MODEL_KEY::COUNT:
             {
                 if(e1[role].toDouble() > e2[role].toDouble())
                     return true;
                 break;
             }
             case FMH::MODEL_KEY::MODIFIED:
             case FMH::MODEL_KEY::DATE:
             {
                 auto currentTime = QDateTime::currentDateTime();
                 auto date1 = QDateTime::fromString(e1[role], Qt::TextDate);
                 auto date2 = QDateTime::fromString(e2[role], Qt::TextDate);
                 if(date1.secsTo(currentTime) <  date2.secsTo(currentTime))
                     return true;
                 break;
             }
             case FMH::MODEL_KEY::LABEL:
             case FMH::MODEL_KEY::USER:
             case FMH::MODEL_KEY::OWNER:
             {
                 const auto str1 = QString(e1[role]).toLower();
                 const auto str2 = QString(e2[role]).toLower();
                 if(str1 < str2)
                     return true;
                 break;
             }
             default:
                 if(e1[role] < e2[role])
                     return true;
         }
         return false;
     });
 }
References FMH::COUNT, FMH::DATE, FMH::LABEL, list, FMH::MODIFIED, FMH::OWNER, FMH::RATE, sortBy, and FMH::USER.
Referenced by StoreList().
updateModel
void StoreList::updateModel (int index, QVector< int > roles) signal
Referenced by StoreModel::setList().
warning
void StoreList::warning (QString warning) signal
Referenced by StoreList().
Field Documentation
list
FMH::MODEL_LIST StoreList::list private
Definition at line 115 of file storelist.h.
Referenced by download(), fileExists(), get(), itemLocalPath(), items(), setList(), sortList(), and StoreList().
store
Store* StoreList::store private
Definition at line 116 of file storelist.h.
Referenced by download(), getPersonInfo(), setList(), setProvider(), and StoreList().
Property Documentation
category
StoreList::CATEGORY StoreList::category read write
Definition at line 29 of file storelist.h.
Referenced by getCategoryList(), and setList().
contentEmpty
bool StoreList::contentEmpty = true read
Definition at line 35 of file storelist.h.
Referenced by getContentEmpty(), setList(), and StoreList().
contentReady
bool StoreList::contentReady = false read
Definition at line 34 of file storelist.h.
Referenced by getContentReady(), setList(), and StoreList().
limit
int StoreList::limit = 10 read write
Definition at line 30 of file storelist.h.
Referenced by getLimit(), setLimit(), and setList().
order
StoreList::ORDER StoreList::order read write
Definition at line 33 of file storelist.h.
Referenced by getOrder(), and setOrder().
page
int StoreList::page = 0 read write
Definition at line 31 of file storelist.h.
Referenced by getPage(), setList(), setPage(), and setQuery().
provider
StoreList::PROVIDER StoreList::provider = StoreList::PROVIDER::KDELOOK read write
Definition at line 37 of file storelist.h.
Referenced by getProvider(), and setProvider().
query
QString StoreList::query read write
Definition at line 32 of file storelist.h.
Referenced by getQuery(), setList(), and setQuery().
sortBy
StoreList::SORTBY StoreList::sortBy = StoreList::SORTBY::DATE read write
Definition at line 36 of file storelist.h.
Referenced by getSortBy(), setList(), setSortBy(), and sortList().
The documentation for this class was generated from the following files:
utils/store/storelist.h
utils/store/storelist.cpp