MauiKit: UTIL Namespace Reference
UTIL Namespace Reference
Functions
bool fileExists (const QString &url)
QString whoami ()
void saveSettings (const QString &key, const QVariant &value, const QString &group, QString app=UTIL::app->applicationName(), const QString organization=UTIL::app->organizationName())
QVariant loadSettings (const QString &key, const QString &group, const QVariant &defaultValue, const QString app=UTIL::app->applicationName(), const QString organization=UTIL::app->organizationName())
Variables
const auto app = QCoreApplication::instance()
Function Documentation
fileExists()
bool UTIL::fileExists (const QString & url) inline
Definition at line 43 of file utils.h.
     {
         QFileInfo path(url);
         if (path.exists()) return true;
         else return false;
     }
Referenced by FM::copy(), FM::cut(), FMDB::FMDB(), FM::packItems(), and TAGDB::TAGDB().
loadSettings()
QVariant UTIL::loadSettings (const QString & key, const QString & group, const QVariant & defaultValue, const QString app = UTIL::app->applicationName(), const QString organization = UTIL::app->organizationName()) inline
Definition at line 67 of file utils.h.
     {
         QVariant variant;
         QSettings setting(organization.isEmpty() ?  QString("org.kde.maui") : organization, app);
         setting.beginGroup(group);
         variant = setting.value(key,defaultValue);
         setting.endGroup();
         return variant;
     }
References app.
Referenced by FM::loadSettings(), and FMList::reset().
saveSettings()
void UTIL::saveSettings (const QString & key, const QVariant & value, const QString & group, QString app = UTIL::app->applicationName(), const QString organization = UTIL::app->organizationName()) inline
Definition at line 59 of file utils.h.
     {
         QSettings setting(organization.isEmpty() ?  QString("org.kde.maui") : organization, app);
         setting.beginGroup(group);
         setting.setValue(key,value);
         setting.endGroup();
     }
References app.
Referenced by FM::saveSettings(), FMList::setFoldersFirst(), FMList::setHidden(), FMList::setPreview(), FMList::setSaveDirProps(), FMList::setSortBy(), and FMList::setViewType().
whoami()
QString UTIL::whoami () inline
Definition at line 50 of file utils.h.
     {
 #ifdef Q_OS_UNIX
         return qgetenv("USER");
 #else
         return  qgetenv("USERNAME"); //for windows
 #endif
     }
Referenced by Tagging::user().
Variable Documentation
app
const auto UTIL::app = QCoreApplication::instance()
Definition at line 41 of file utils.h.
Referenced by Handy::appInfo(), MAUIKDE::launchApp(), loadSettings(), saveSettings(), and Tagging::setApp().