MauiKit: FMH Namespace Reference
FMH Namespace Reference
Data Structures
class Downloader
Typedefs
typedef QHash< FMH::MODEL_KEY, QString > MODEL
typedef QList< MODEL > MODEL_LIST
typedef QMap< FMH::MODEL_KEY, QString > DB
Enumerations
enum FILTER_TYPE : uint_fast8_t {
AUDIO, VIDEO, TEXT, IMAGE,
DOCUMENT, NONE
}
enum MODEL_KEY : uint_fast8_t {
ICON, LABEL, PATH, URL,
TYPE, GROUP, OWNER, SUFFIX,
NAME, DATE, SIZE, MODIFIED,
MIME, TAG, PERMISSIONS, THUMBNAIL,
THUMBNAIL_1, THUMBNAIL_2, THUMBNAIL_3, HIDDEN,
ICONSIZE, DETAILVIEW, SHOWTHUMBNAIL, SHOWTERMINAL,
COUNT, SORTBY, USER, PASSWORD,
SERVER, FOLDERSFIRST, VIEWTYPE, ADDDATE,
FAV, COLOR, RATE, FORMAT,
PLACE, LOCATION, ALBUM, ARTIST,
TRACK, DURATION, ARTWORK, PLAYLIST,
LYRICS, WIKI, MOOD, SOURCETYPE,
GENRE, NOTE, COMMENT, CONTEXT,
SOURCE, TITLE, ID, RELEASEDATE,
LICENSE, DESCRIPTION, BOOKMARK, ACCOUNT,
VERSION, DOMAIN, N, PHOTO,
GENDER, ADR, ADR_2, ADR_3,
EMAIL, EMAIL_2, EMAIL_3, LANG,
NICKNAME, ORG, PROFILE, TZ,
TEL, TEL_2, TEL_3, IM,
CITY, STATE, COUNTRY
}
enum PATHTYPE_KEY : uint_fast8_t {
PLACES_PATH, DRIVES_PATH, BOOKMARKS_PATH, TAGS_PATH,
APPS_PATH, TRASH_PATH, SEARCH_PATH, CLOUD_PATH
}
enum TABLE : uint8_t { TABLE::BOOKMARKS, TABLE::CLOUDS }
Functions
bool isAndroid ()
bool fileExists (const QString &url)
QVariantMap dirConf (const QString &path)
void setDirConf (const QString &path, const QString &group, const QString &key, const QVariant &value)
QString getIconName (const QString &path)
QString getMime (const QString &path)
QVariantMap getDirInfo (const QString &path, const QString &type=QString())
FMH::MODEL getFileInfoModel (const QString &path)
QVariantMap getFileInfo (const QString &path)
Variables
static const QHash< FMH::FILTER_TYPE, QStringList > FILTER_LIST
static const QHash< FMH::MODEL_KEY, QString > MODEL_NAME
static const QHash< QString, FMH::MODEL_KEY > MODEL_NAME_KEY
static const QHash< PATHTYPE_KEY, QString > PATHTYPE_NAME
const QString DataPath = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation)
const QString CloudCachePath = FMH::DataPath+"/Cloud/"
const QString PicturesPath = QStandardPaths::writableLocation(QStandardPaths::PicturesLocation)
const QString DownloadsPath = QStandardPaths::writableLocation(QStandardPaths::DownloadLocation)
const QString DocumentsPath = QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation)
const QString HomePath = QStandardPaths::writableLocation(QStandardPaths::HomeLocation)
const QString MusicPath = QStandardPaths::writableLocation(QStandardPaths::MusicLocation)
const QString VideosPath = QStandardPaths::writableLocation(QStandardPaths::MoviesLocation)
const QString DesktopPath = QStandardPaths::writableLocation(QStandardPaths::DesktopLocation)
const QString AppsPath = QStandardPaths::writableLocation(QStandardPaths::ApplicationsLocation)
const QString RootPath = "/"
const QStringList defaultPaths
const QMap< QString, QString > folderIcon
static const QMap< FMH::TABLE, QString > TABLEMAP
const QString FMPath = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation)+"/maui/fm/"
const QString DBName = "fm.db"
Typedef Documentation
DB
typedef QMap<FMH::MODEL_KEY, QString> FMH::DB
Definition at line 582 of file fmh.h.
MODEL
typedef QHash<FMH::MODEL_KEY, QString> FMH::MODEL
Definition at line 361 of file fmh.h.
MODEL_LIST
typedef QList<MODEL> FMH::MODEL_LIST
Definition at line 362 of file fmh.h.
Enumeration Type Documentation
FILTER_TYPE
enum FMH::FILTER_TYPE : uint_fast8_t
Enumerator
AUDIO
VIDEO
TEXT
IMAGE
DOCUMENT
NONE
Definition at line 66 of file fmh.h.
                      : uint_fast8_t
     {
         AUDIO,
         VIDEO,
         TEXT,
         IMAGE,
         DOCUMENT,
         NONE
     };
MODEL_KEY
enum FMH::MODEL_KEY : uint_fast8_t
Enumerator
ICON
LABEL
PATH
URL
TYPE
GROUP
OWNER
SUFFIX
NAME
DATE
SIZE
MODIFIED
MIME
TAG
PERMISSIONS
THUMBNAIL
THUMBNAIL_1
THUMBNAIL_2
THUMBNAIL_3
HIDDEN
ICONSIZE
DETAILVIEW
SHOWTHUMBNAIL
SHOWTERMINAL
COUNT
SORTBY
USER
PASSWORD
SERVER
FOLDERSFIRST
VIEWTYPE
ADDDATE
FAV
COLOR
RATE
FORMAT
PLACE
LOCATION
ALBUM
ARTIST
TRACK
DURATION
ARTWORK
PLAYLIST
LYRICS
WIKI
MOOD
SOURCETYPE
GENRE
NOTE
COMMENT
CONTEXT
SOURCE
TITLE
ID
RELEASEDATE
LICENSE
DESCRIPTION
BOOKMARK
ACCOUNT
VERSION
DOMAIN
N
ccdav keys
PHOTO
GENDER
ADR
ADR_2
ADR_3
EMAIL
EMAIL_2
EMAIL_3
LANG
NICKNAME
ORG
PROFILE
TZ
TEL
TEL_2
TEL_3
IM
CITY
other keys
STATE
COUNTRY
Definition at line 86 of file fmh.h.
                    : uint_fast8_t
     {
         ICON,
         LABEL,
         PATH,
         URL,
         TYPE,
         GROUP,
         OWNER,
         SUFFIX,
         NAME,
         DATE,
         SIZE,
         MODIFIED,
         MIME,
         TAG,
         PERMISSIONS,
         THUMBNAIL,
         THUMBNAIL_1,
         THUMBNAIL_2,
         THUMBNAIL_3,
         HIDDEN,
         ICONSIZE,
         DETAILVIEW,
         SHOWTHUMBNAIL,
         SHOWTERMINAL,
         COUNT,
         SORTBY,
         USER,
         PASSWORD,
         SERVER,
         FOLDERSFIRST,
         VIEWTYPE,
         ADDDATE,
         FAV,
         COLOR,
         RATE,
         FORMAT,
         PLACE,
         LOCATION,
         ALBUM,
         ARTIST,
         TRACK,
         DURATION,
         ARTWORK,
         PLAYLIST,
         LYRICS,
         WIKI,
         MOOD,
         SOURCETYPE,
         GENRE,
         NOTE,
         COMMENT,
         CONTEXT,
         SOURCE,
         TITLE,
         ID,
         RELEASEDATE,
         LICENSE,
         DESCRIPTION,
         BOOKMARK,
         ACCOUNT,
         VERSION,
         DOMAIN,
         N,
         PHOTO,
         GENDER,
         ADR,
         ADR_2,
         ADR_3,
         EMAIL,
         EMAIL_2,
         EMAIL_3,
         LANG,
         NICKNAME,
         ORG,
         PROFILE,
         TZ,
         TEL,
         TEL_2,
         TEL_3,
         IM,
         CITY,
         STATE,
         COUNTRY
     };
PATHTYPE_KEY
enum FMH::PATHTYPE_KEY : uint_fast8_t
Enumerator
PLACES_PATH
DRIVES_PATH
BOOKMARKS_PATH
TAGS_PATH
APPS_PATH
TRASH_PATH
SEARCH_PATH
CLOUD_PATH
Definition at line 364 of file fmh.h.
                       : uint_fast8_t
     {
         PLACES_PATH,
         DRIVES_PATH,
         BOOKMARKS_PATH,
         TAGS_PATH,
         APPS_PATH,
         TRASH_PATH,
         SEARCH_PATH,
         CLOUD_PATH
     };
TABLE
enum FMH::TABLE : uint8_t strong
Enumerator
BOOKMARKS
CLOUDS
Definition at line 570 of file fmh.h.
                      : uint8_t
     {
         BOOKMARKS,
         CLOUDS
     };
Function Documentation
dirConf()
QVariantMap FMH::dirConf (const QString & path) inline
Definition at line 462 of file fmh.h.
     {
         if(!FMH::fileExists(path))
             return QVariantMap();
         QString icon, iconsize, hidden, detailview, showthumbnail, showterminal;
         uint count = 0, sortby = FMH::MODEL_KEY::MODIFIED, viewType = 0;
         bool foldersFirst = false;
         #ifdef Q_OS_ANDROID
         QSettings file(path, QSettings::Format::NativeFormat);
         file.beginGroup(QString("Desktop Entry"));
         icon = file.value("Icon").toString();
         file.endGroup();
         file.beginGroup(QString("Settings"));
         hidden = file.value("HiddenFilesShown").toString();
         file.endGroup();
         file.beginGroup(QString("MAUIFM"));
         iconsize =  file.value("IconSize").toString();
         detailview = file.value("DetailView").toString();
         showthumbnail = file.value("ShowThumbnail").toString();
         showterminal = file.value("ShowTerminal").toString();
         count = file.value("Count").toInt();
         sortby = file.value("SortBy").toInt();
         foldersFirst = file.value("FoldersFirst").toBool();
         viewType = file.value("ViewType").toInt();
         file.endGroup();
         #else
         KConfig file(path);
         icon =  file.entryMap(QString("Desktop Entry"))["Icon"];
         hidden = file.entryMap(QString("Settings"))["HiddenFilesShown"];
         iconsize = file.entryMap(QString("MAUIFM"))["IconSize"];
         detailview = file.entryMap(QString("MAUIFM"))["DetailView"];
         showthumbnail = file.entryMap(QString("MAUIFM"))["ShowThumbnail"];
         showterminal = file.entryMap(QString("MAUIFM"))["ShowTerminal"];
         count = file.entryMap(QString("MAUIFM"))["Count"].toInt();
         sortby = file.entryMap(QString("MAUIFM"))["SortBy"].toInt();
         foldersFirst = file.entryMap(QString("MAUIFM"))["FoldersFirst"] == "true" ? true : false;
         viewType = file.entryMap(QString("MAUIFM"))["ViewType"].toInt();
         #endif
         auto res = QVariantMap({
             {FMH::MODEL_NAME[FMH::MODEL_KEY::ICON], icon.isEmpty() ? "folder" : icon},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::ICONSIZE], iconsize},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::COUNT], count},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::SHOWTERMINAL], showterminal.isEmpty() ? "false" : showterminal},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::SHOWTHUMBNAIL], showthumbnail.isEmpty() ? "false" : showthumbnail},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::DETAILVIEW], detailview.isEmpty() ? "false" : detailview},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::HIDDEN], hidden.isEmpty() ? false : (hidden == "true" ? true : false)},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::SORTBY], sortby},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::FOLDERSFIRST], foldersFirst},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::VIEWTYPE], viewType}
         });
         return res;
     }
References COUNT, DETAILVIEW, fileExists(), FOLDERSFIRST, HIDDEN, ICON, ICONSIZE, MODEL_NAME, MODIFIED, SHOWTERMINAL, SHOWTHUMBNAIL, SORTBY, and VIEWTYPE.
Referenced by FM::dirConf(), getIconName(), and FMList::reset().
fileExists()
bool FMH::fileExists (const QString & url) inline
Definition at line 455 of file fmh.h.
     {
         QFileInfo path(url);
         if (path.exists()) return true;
         else return false;
     }
Referenced by FM::bookmark(), dirConf(), StoreList::fileExists(), FM::fileExists(), Syncing::getCacheFile(), Syncing::resolveFile(), MAUIKDE::setColorScheme(), FMList::setPath(), Store::start(), Syncing::upload(), PlacesList::watchPath(), and FMList::watchPath().
getDirInfo()
QVariantMap FMH::getDirInfo (const QString & path, const QString & type = QString()) inline
Definition at line 587 of file fmh.h.
     {
         QFileInfo file (path);
         if(!file.exists()) return QVariantMap();
         QVariantMap data =
         {
             {FMH::MODEL_NAME[FMH::MODEL_KEY::ICON], FMH::getIconName(path)},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::LABEL], file.baseName()},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::PATH], path},
             {FMH::MODEL_NAME[FMH::MODEL_KEY::TYPE], type}
         };
         return data;
     }
References getIconName(), ICON, LABEL, MODEL_NAME, PATH, and TYPE.
Referenced by FM::getDirInfo().
getFileInfo()
QVariantMap FMH::getFileInfo (const QString & path) inline
Definition at line 631 of file fmh.h.
     {
         QFileInfo file(path);
         if(!file.exists()) return QVariantMap();
         auto data = FMH::getFileInfoModel(path);
         QVariantMap res;
         for(auto key : data.keys())
             res.insert(FMH::MODEL_NAME[key], data[key]);
         return res;
     }
References getFileInfoModel(), and MODEL_NAME.
Referenced by FM::getFileInfo().
getFileInfoModel()
FMH::MODEL FMH::getFileInfoModel (const QString & path) inline
Definition at line 603 of file fmh.h.
     {
         QFileInfo file(path);
         if(!file.exists()) return FMH::MODEL();
         auto mime = FMH::getMime(path);
 //      QLocale locale;
         FMH::MODEL res =
         {
             {FMH::MODEL_KEY::GROUP, file.group()},
             {FMH::MODEL_KEY::OWNER, file.owner()},
             {FMH::MODEL_KEY::SUFFIX, file.completeSuffix()},
             {FMH::MODEL_KEY::LABEL, /*file.isDir() ? file.baseName() :*/ path == FMH::HomePath ? QStringLiteral("Home") : file.fileName()},
             {FMH::MODEL_KEY::NAME, file.fileName()},
             {FMH::MODEL_KEY::DATE,  file.birthTime().toString(Qt::TextDate)},
             {FMH::MODEL_KEY::MODIFIED, file.lastModified().toString(Qt::TextDate)},
             {FMH::MODEL_KEY::MIME, mime },
             {FMH::MODEL_KEY::ICON, FMH::getIconName(path)},
             {FMH::MODEL_KEY::SIZE, QString::number(file.size()) /*locale.formattedDataSize(file.size())*/},
             {FMH::MODEL_KEY::PATH, path},
             {FMH::MODEL_KEY::THUMBNAIL, path},
             {FMH::MODEL_KEY::COUNT, file.isDir() ? QString::number(QDir(path).count() - 2) : "0"}
         };
         return res;
     }
References COUNT, DATE, getIconName(), getMime(), GROUP, HomePath, ICON, LABEL, MIME, MODIFIED, NAME, OWNER, PATH, SIZE, SUFFIX, and THUMBNAIL.
Referenced by FM::copy(), Store::downloadLink(), getFileInfo(), FM::getPathContent(), FM::getTagContent(), FM::packItems(), Syncing::resolveFile(), Syncing::saveTo(), FM::search(), FMList::search(), and Syncing::upload().
getIconName()
QString FMH::getIconName (const QString & path) inline
Definition at line 537 of file fmh.h.
     {
         if(QFileInfo(path).isDir())
         {
             if(folderIcon.contains(path))
                 return folderIcon[path];
             else
             {
                 auto icon = FMH::dirConf(QString(path+"/%1").arg(".directory"))[FMH::MODEL_NAME[FMH::MODEL_KEY::ICON]].toString();
                 return icon.isEmpty() ? "folder" : icon;
             }
         }else {
             #if defined(Q_OS_ANDROID)
             QMimeDatabase mime;
             auto type = mime.mimeTypeForFile(path);
             return type.iconName();
             #else
             KFileItem mime(path);
             return mime.iconName();
             #endif
         }
     }
References dirConf(), folderIcon, ICON, and MODEL_NAME.
Referenced by getDirInfo(), getFileInfoModel(), and Syncing::listDirOutputHandler().
getMime()
QString FMH::getMime (const QString & path) inline
Definition at line 562 of file fmh.h.
     {
         QMimeDatabase mimedb;
         auto mime = mimedb.mimeTypeForFile(path).name();
         return mime;
     }
Referenced by getFileInfoModel().
isAndroid()
bool FMH::isAndroid () inline
Definition at line 47 of file fmh.h.
     {
         #if defined(Q_OS_ANDROID)
         return true;
         #elif defined(Q_OS_LINUX)
         return false;
         #elif defined(Q_OS_WIN32)
         return false;
         #elif defined(Q_OS_WIN64)
         return false;
         #elif defined(Q_OS_MACOS)
         return false;
         #elif defined(Q_OS_IOS)
         return false;
         #elif defined(Q_OS_HAIKU)
         return false;
         #endif
     }
setDirConf()
void FMH::setDirConf (const QString & path, const QString & group, const QString & key, const QVariant & value) inline
Definition at line 522 of file fmh.h.
     {
         #ifdef Q_OS_ANDROID
         QSettings file(path, QSettings::Format::IniFormat);
         file.beginGroup(group);
         file.setValue(key, value);
         file.endGroup();
         file.sync();
         #else
         KConfig file(path);
         auto kgroup = file.group(group);
         kgroup.writeEntry(key, value);
         #endif
     }
Referenced by FM::setDirConf(), FMList::setFoldersFirst(), FMList::setHidden(), FMList::setPreview(), FMList::setSortBy(), and FMList::setViewType().
Variable Documentation
AppsPath
const QString FMH::AppsPath = QStandardPaths::writableLocation(QStandardPaths::ApplicationsLocation)
Definition at line 427 of file fmh.h.
CloudCachePath
const QString FMH::CloudCachePath = FMH::DataPath+"/Cloud/"
Definition at line 389 of file fmh.h.
Referenced by Syncing::download(), Syncing::localToAbstractCloudPath(), FM::resolveUserCloudCachePath(), and Syncing::saveToCache().
DataPath
const QString FMH::DataPath = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation)
Definition at line 388 of file fmh.h.
Referenced by MAUIKDE::setColorScheme(), and Store::start().
DBName
const QString FMH::DBName = "fm.db"
Definition at line 585 of file fmh.h.
Referenced by FMDB::FMDB(), and FMDB::openDB().
defaultPaths
const QStringList FMH::defaultPaths
Initial value:
=
    {
        HomePath,
        DesktopPath,
        DocumentsPath,
        PicturesPath,
        MusicPath,
        VideosPath,
        DownloadsPath
    }
Definition at line 429 of file fmh.h.
Referenced by FM::bookmark(), FM::getDefaultPaths(), and FM::isDefaultPath().
DesktopPath
const QString FMH::DesktopPath = QStandardPaths::writableLocation(QStandardPaths::DesktopLocation)
Definition at line 426 of file fmh.h.
DocumentsPath
const QString FMH::DocumentsPath = QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation)
Definition at line 422 of file fmh.h.
DownloadsPath
const QString FMH::DownloadsPath = QStandardPaths::writableLocation(QStandardPaths::DownloadLocation)
Definition at line 421 of file fmh.h.
Referenced by Store::downloadLink(), StoreList::fileExists(), and StoreList::itemLocalPath().
FILTER_LIST
const QHash<FMH::FILTER_TYPE, QStringList> FMH::FILTER_LIST static
Initial value:
=
    {
        {FILTER_TYPE::AUDIO, QStringList {"*.mp3", "*.mp4", "*.wav", "*.ogg", "*.flac"}},
        {FILTER_TYPE::VIDEO, QStringList {"*.mp4", "*.mkv", "*.mov", "*.avi", "*.flv"}},
        {FILTER_TYPE::TEXT, QStringList {"*.txt", "*.cpp", "*.js", "*.doc", "*.h", "*.json", "*.html", "*.rtf"}},
        {FILTER_TYPE::DOCUMENT, QStringList {"*.pdf", "*.txt", "*.cbz", "*.cbr", "*.epub", "*.cbt", "*.cba", "*.cb7"}},
        {FILTER_TYPE::IMAGE, QStringList {"*.png", "*.jpg", "*.jpeg", "*.gif", "*.svg", "*.bmp"}},
        {FILTER_TYPE::NONE, QStringList()}
    }
Definition at line 76 of file fmh.h.
Referenced by FMList::setFilterType().
FMPath
const QString FMH::FMPath = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation)+"/maui/fm/"
Definition at line 584 of file fmh.h.
Referenced by FMDB::FMDB(), and FMDB::openDB().
folderIcon
const QMap<QString, QString> FMH::folderIcon
Initial value:
{
        {PicturesPath, "folder-pictures"},
        {DownloadsPath, "folder-download"},
        {DocumentsPath, "folder-documents"},
        {HomePath, "user-home"},
        {MusicPath, "folder-music"},
        {VideosPath, "folder-videos"},
        {DesktopPath, "user-desktop"},
        {AppsPath, "system-run"},
        {RootPath, "folder-root"}
    }
Definition at line 441 of file fmh.h.
Referenced by getIconName().
HomePath
const QString FMH::HomePath = QStandardPaths::writableLocation(QStandardPaths::HomeLocation)
Definition at line 423 of file fmh.h.
Referenced by getFileInfoModel(), and FM::homePath().
MODEL_NAME
const QHash<FMH::MODEL_KEY, QString> FMH::MODEL_NAME static
Definition at line 178 of file fmh.h.
Referenced by FM::addCloudAccount(), Handy::appInfo(), FM::bookmark(), dirConf(), SyncingList::get(), PlacesList::get(), FM::get(), StoreList::get(), FMList::get(), FM::getBookmarks(), StoreList::getCategoryList(), FM::getCloudAccounts(), FM::getCloudAccountsList(), FM::getCloudServerContent(), getDirInfo(), getFileInfo(), getIconName(), FM::init(), FMDB::remove(), FMList::reset(), SyncingModel::roleNames(), PlacesModel::roleNames(), StoreModel::roleNames(), FMModel::roleNames(), FM::toMap(), FMDB::update(), and Handy::userInfo().
MODEL_NAME_KEY
const QHash<QString, FMH::MODEL_KEY> FMH::MODEL_NAME_KEY static
Definition at line 272 of file fmh.h.
Referenced by FM::copy(), FM::cut(), FM::getCloudItem(), SyncingList::insert(), FM::openCloudItem(), and FM::toModel().
MusicPath
const QString FMH::MusicPath = QStandardPaths::writableLocation(QStandardPaths::MusicLocation)
Definition at line 424 of file fmh.h.
PATHTYPE_NAME
const QHash<PATHTYPE_KEY, QString> FMH::PATHTYPE_NAME static
Initial value:
=
    {
        {PATHTYPE_KEY::PLACES_PATH, "Places"},
        {PATHTYPE_KEY::DRIVES_PATH, "Drives"},
        {PATHTYPE_KEY::BOOKMARKS_PATH, "Bookmarks"},
        {PATHTYPE_KEY::APPS_PATH, "Apps"},
        {PATHTYPE_KEY::TRASH_PATH, "Trash"},
        {PATHTYPE_KEY::TAGS_PATH, "Tags"},
        {PATHTYPE_KEY::SEARCH_PATH, "Search"},
        {PATHTYPE_KEY::CLOUD_PATH, "Cloud"}
    }
Definition at line 376 of file fmh.h.
Referenced by FMList::createDir(), MAUIKDE::getApps(), FM::getAppsContent(), FM::getBookmarks(), FM::getCloudAccounts(), FM::getCustomPaths(), FM::getDefaultPaths(), FM::getDevices(), FM::getTags(), FM::isCloud(), Syncing::localToAbstractCloudPath(), FM::resolveLocalCloudPath(), and FMList::setPath().
PicturesPath
const QString FMH::PicturesPath = QStandardPaths::writableLocation(QStandardPaths::PicturesLocation)
Definition at line 420 of file fmh.h.
RootPath
const QString FMH::RootPath = "/"
Definition at line 428 of file fmh.h.
TABLEMAP
const QMap<FMH::TABLE, QString> FMH::TABLEMAP static
Initial value:
=
    {
        {TABLE::BOOKMARKS, "bookmarks"},
        {TABLE::CLOUDS, "clouds"}
    }
Definition at line 576 of file fmh.h.
Referenced by FM::addCloudAccount(), FM::bookmark(), FM::removeBookmark(), and FM::removeCloudAccount().
VideosPath
const QString FMH::VideosPath = QStandardPaths::writableLocation(QStandardPaths::MoviesLocation)
Definition at line 425 of file fmh.h.